NAS-128457: Reorganizing enclosure pages
truenas/webui pull request #10064
Opened 2024-05-14 16:44 UTC by undsoft

Reorganizes enclosure pages using router into different views, which can be seen by clicking in Elements menu.

2024-05-14 16:45 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128457

2024-05-15 14:23 UTC, RehanY147 requested changes
Architecture looks good. A couple issues in code pointed out. Also, when elements select changes value, the "Disks" option stays highlighted.

2024-05-15 14:23 UTC, RehanY147 commented on src/app/pages/system/enclosure/components/enclosure-header/view-elements-menu/view-elements-menu.component.ts
> +      .filter((view) => this.enclosure().elements[view])
Should declare a constant at the start and save the value and reuse it so it's clear this is a dependency for the computed signal.

2024-05-15 14:23 UTC, RehanY147 commented on src/app/pages/system/enclosure/enclosure.routing.ts
> +      {
duplicate

2024-05-15 14:26 UTC, RehanY147 approved these changes
Please address the above suggestions. Otherwise looks good.

2024-05-15 14:50 UTC, undsoft commented
Doesn't seem like there is an easy solution to item highlighting in the menu.

2024-05-17 07:47 UTC, merged

2024-05-17 07:48 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.