NAS-128968 / 24.10 / TrueCloud Backup shows non-Storj credentials
truenas/webui pull request #10063
Opened 2024-05-14 14:11 UTC by AlexKarpov98

Testing: see ticket
<img width="488" alt="Screenshot 2024-05-14 at 16 49 08" src="https://github.com/truenas/webui/assets/22980553/cb08de0c-e40f-49eb-8b53-cc62ac16f9fa">

2024-05-14 14:12 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128968

2024-05-14 14:22 UTC, denysbutenko approved these changes
👍🏻

2024-05-15 08:44 UTC, undsoft requested changes
Test needs to be rewritten and I would also try to figure out why codecov views most of the component as not being covered.

2024-05-15 08:44 UTC, undsoft commented on src/app/modules/custom-selects/cloud-credentials-select/cloud-credentials-select.spec.ts
> +      schemas: [NO_ERRORS_SCHEMA],
No bueno.

2024-05-15 08:44 UTC, undsoft commented on src/app/modules/custom-selects/cloud-credentials-select/cloud-credentials-select.spec.ts
> +});
Was this test auto-generated? It needs to rewriten to match our code base by using spectator, removing unnecessary mocks and changing test to not use methods that should be protected like  `fetchOptions`.

You should create a test using `createHost` in spectator and test things that user/other components will interact with. This mostly means changing inputs and seeing that `ix-select` got populated with correct options.

2024-05-15 08:44 UTC, undsoft commented on src/app/modules/custom-selects/cloud-credentials-select/cloud-credentials-select.spec.ts
> +import { NO_ERRORS_SCHEMA } from '@angular/core';
Filename should be `cloud-credentials-select.component.spec.ts`

2024-05-17 07:22 UTC, undsoft approved these changes
Thanks.

2024-05-17 07:22 UTC, merged

2024-05-17 07:23 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.