NAS-128973: Used confirm-dialog for deleting with force flag
truenas/webui pull request #10075
Opened 2024-05-17 10:48 UTC by RehanY147

Add `force` flag to jbof delete requests

2024-05-17 10:48 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128973

2024-05-19 10:23 UTC, undsoft approved these changes
Tested jbof page with mocks. Confirmation dialog has force flag and sends correct requests.

2024-05-19 10:23 UTC, undsoft commented on src/app/pages/credentials/certificates-dash/certificate-list/certificate-list.component.ts
> +        (confirmation: boolean | { confirmed: boolean; secondaryCheckbox: boolean }) => {
Here, below and other files you shouldn't have to do this. `confirm` returns an object when used with `secondaryCheckbox: true`

2024-05-20 16:48 UTC, denysbutenko requested changes

2024-05-20 16:48 UTC, denysbutenko commented on src/app/pages/credentials/certificates-dash/certificate-list/certificate-list.component.ts
> +      switchMap((confirmation: boolean | { confirmed: boolean; secondaryCheckbox: boolean }) => {
Repetitive type comparison does not look good. Let's try to keep it clean. If this is going to be copy-pasted over and over, let's extract it into a helper operator.

2024-05-21 07:30 UTC, denysbutenko approved these changes

2024-05-21 08:40 UTC, merged

2024-05-21 08:41 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.