NAS-128542: Update certificate list when creating acme certificate
truenas/webui pull request #10146
Opened 2024-06-05 19:58 UTC by bvasilenko

**Testing**

For proper end-to-end testing you'll need to be the domain owner, and update it's DNS records.

Since the scope is limited to the frontend it will be easier for you to make a mock , i.e. temporarily add code that simulates the successful completion of a job that creates an ACME Certificate. Then, you need to test that the Certificates block receives fresh data from the server.

2024-06-05 19:59 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128542

2024-06-06 09:24 UTC, undsoft commented
24.04.0 was released more than a month ago.

2024-06-06 13:30 UTC, denysbutenko requested changes
The changes looking good but targeted wrong branch

2024-06-09 20:11 UTC, bvasilenko commented
replaced by https://github.com/truenas/webui/pull/10161

2024-06-09 20:11 UTC, closed without merging