NAS-129264: Add CPU Recent Usage widget
truenas/webui pull request #10140
Opened 2024-06-04 20:44 UTC by bvasilenko

**Summary**

FreeBSD does not have a single CPU usage chart. So we're going to display `System` and `User` CPU usage charts - these are the closest analogues of overall CPU usage

**Testing**

Please test the widget on the new dashboard

2024-06-04 20:45 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129264

2024-06-05 21:07 UTC, RehanY147 requested changes
CPU stats don't update once you navigate away and come back to the dashboard.

https://github.com/truenas/webui/assets/24204846/d58bf4d7-daa0-48a9-9fab-d1f84b6bf093

2024-06-11 20:56 UTC, bvasilenko commented
> CPU stats don't update once you navigate away and come back to the dashboard.

@RehanY147  Turned out that this is not caused by the WebUI, and root cause is middleware. I've moved your notice into a [separate issue](https://ixsystems.atlassian.net/browse/NAS-129552). 

So, I suggest to go ahead and merge this PR, if there's no other issues.

2024-06-12 12:22 UTC, RehanY147 approved these changes

2024-06-12 13:20 UTC, merged

2024-06-12 13:21 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.