Fixed warning text
truenas/webui pull request #10150
Opened 2024-06-06 00:55 UTC by RehanY147

2024-06-06 00:55 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129104

2024-06-06 13:26 UTC, denysbutenko requested changes

2024-06-06 13:26 UTC, denysbutenko commented on src/app/pages/apps/components/dockerhub-rate-limit-info-dialog/dockerhub-rate-limit-info-dialog.component.ts
>        this.helpText.dockerHubRateLimit.message,
now we can use this inside the template directly

2024-06-07 04:28 UTC, denysbutenko requested changes
ChartWizard needs to be updated since `MAT_DIALOG_DATA` was removed  
https://github.com/truenas/webui/blob/f3df7c398e53e8f35c88021bb65a14df9ec14ffa/src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts#L523-L532

2024-06-07 04:28 UTC, denysbutenko commented on src/app/pages/apps/components/dockerhub-rate-limit-info-dialog/dockerhub-rate-limit-info-dialog.component.ts
>    helpText = helptextApps;
unused

2024-06-07 05:07 UTC, denysbutenko approved these changes
Thanks, looks good

2024-06-10 22:32 UTC, merged

2024-06-10 22:32 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-129104 is targeted to the following versions which have not received their corresponding PRs: 24.04.2

2024-06-11 10:41 UTC, undsoft commented
backport