NAS-129425: Hide standby node info widget for a non-HA system
truenas/webui pull request #10173
Opened 2024-06-11 21:02 UTC by bvasilenko

**Summary**

In general, the **System Info** widget that needs to be hidden can be any size. And, if all the widgets are hidden inside a group of widgets (dark gray tile below),

<img width="652" alt="image" src="https://github.com/truenas/webui/assets/20611516/d0e773df-619d-437d-bd1d-9e4bd65edef8">

in this case one, then the group itself may not be closed.

I made this conclusion on the basis that now it is possible to add an empty group of widgets.

**Testing**

See ticket for replication steps

For Non-HA system use any CI instance. For HA system use 10.220.16.103

2024-06-11 21:02 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129425

2024-06-12 09:31 UTC, undsoft requested changes
1. WidgetResources is not an appropriate place for this logic.
2. Current approach means that there is going to be a service which is going to be smart. It's going to know conditions for hiding any widget that needs to be hidden. This violates O in SOLID. Is there a way to have this logic contained in widget/widget definition?

2024-06-12 13:36 UTC, RehanY147 reviewed
What Evgeny said

2024-06-17 09:51 UTC, undsoft requested changes
I was thinking more about moving this logic:
```
if (!isHaLicensed) {
  widgets.push(WidgetType.SystemInfoPassive);
}
```
here.
I know that it may be tricky, but I think there should be a way to do it.
For example, see if we can do injection like in Angular dependency containers:

```
visibility: {
  deps: [Store],
  isVisible$: (store: Store) => store.select(selectIsHaLicensed),
}

```

See if this helps https://angular.dev/guide/di/dependency-injection-context#run-within-an-injection-context

2024-06-19 08:58 UTC, undsoft requested changes
The code works, but let's add test cases for new behaviour.

2024-06-19 08:58 UTC, undsoft commented on src/app/pages/dashboard/types/widget-component.interface.ts
> +export type WidgetVisibilityProvider = Store;
Better to specify as generics or at least unknowns. Adding visibility condition to a widget definition should not necessitate adding types here.

2024-06-19 08:58 UTC, undsoft commented on src/app/pages/dashboard/components/widget-group-form/widget-group-slot-form/widget-group-slot-form.component.ts
> +    runInInjectionContext(this.environmentInjector, () => {
Large and complicated function needs to be split into methods/utility functions. Perhaps you can also figure out a way to extract similar code here and in `widget-group` into a shared function.

2024-06-25 09:01 UTC, undsoft approved these changes
Okay, it works correctly.

2024-06-25 20:59 UTC, merged

2024-06-25 20:59 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.