NAS-129625 / 24.10 / Dashboard - Editing - I can click and focus on widget buttons
truenas/webui pull request #10200
Opened 2024-06-17 10:02 UTC by AlexKarpov98

Testing: see ticket.

Current result:

https://github.com/truenas/webui/assets/22980553/a93fb440-7c53-4924-b672-bc31e89baf21

2024-06-17 10:02 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129625

2024-06-17 10:07 UTC, denysbutenko commented on src/app/pages/dashboard/components/dashboard/dashboard.component.ts
> +    const groupElements = this.document.querySelectorAll('.group *');
Unsure if modifying DOM here is a good approach.

2024-06-17 10:23 UTC, denysbutenko commented on src/app/pages/dashboard/components/dashboard/dashboard.component.ts
> +  private updateIsEditingState(value: boolean): void {
It may help avoid unnecessary wrapper functions https://angular.dev/guide/signals#effects

2024-06-18 07:04 UTC, undsoft requested changes
1. Let's try to stick to signal syntax.
2. We have the same problem with restricted roles where user can tab into a restricted button. It would be good to try to build a reusable solution (something like a directive) this time. Angular material has `cdkTrapFocus`, we need essentially the opposite of that. See if something already exists on npm or check source code for `cdkTrapFocus`, maybe it'll give you ideas.

2024-06-18 10:48 UTC, closed without merging