Share "enabled" checkbox on edit right panel not matched share page
truenas/webui pull request #10202
Opened 2024-06-17 20:34 UTC by bvasilenko

**Testing**

**Steps to Reproduce**

        
1. Navigate to Shares page

        
2. toggle share 'enabled' slider to 'disabled'

        
3. At this share click 'pencil' icon

**Expected Result**

right panel displays and 'enabled' checkbox is disabled

2024-06-17 20:35 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129198

2024-06-18 08:28 UTC, undsoft commented
Let's retarget this to just `master` and not have it in dragonfish.

2024-06-18 09:15 UTC, denysbutenko requested changes

2024-06-18 09:15 UTC, denysbutenko commented on src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
> +          disabled: (row) => this.changeEnabledIds$.pipe(map((ids) => ids.has(row.id))),
I think you misunderstood the issue. The author means `disabled=unchecked` and `enabled=checked`. The problem is that the state is `unsynced` for toggle&checkbox between card and form.

2024-06-19 19:10 UTC, bvasilenko commented
replaced by https://github.com/truenas/webui/pull/10218

2024-06-26 08:10 UTC, denysbutenko approved these changes
backported

2024-06-26 20:14 UTC, merged

2024-06-26 20:14 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-129198 is targeted to the following versions which have not received their corresponding PRs: 24.04.3

2024-06-26 20:14 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.