Update enabled field after change
truenas/webui pull request #10218
Opened 2024-06-19 19:10 UTC by bvasilenko

**Testing**

**Steps to Reproduce**

        
1. Navigate to Shares page

        
2. toggle share 'enabled' slider to 'disabled'

        
3. At this share click 'pencil' icon

**Expected Result**

right panel displays and 'enabled' checkbox is disabled

2024-06-20 05:43 UTC, denysbutenko requested changes

2024-06-20 05:43 UTC, denysbutenko commented on src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
> +  changedEnabled = new Map<number, boolean>([]);
Let's imagine fixing every other table with this approach.
TBH, it looks like a workaround. We have a mechanism called `getSmbShares` to get fresh results on each change. The question is, why does it not work as expected?

2024-06-25 09:16 UTC, denysbutenko approved these changes
![Kapture 2024-06-25 at 16 11 11](https://github.com/truenas/webui/assets/351613/0e256c59-abef-418a-a0d3-6505bfd10187)

It works well. However, I think `AppLoaderService.withLoader()` is doing its job.

2024-06-25 20:59 UTC, merged

2024-06-25 21:00 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-06-25 21:15 UTC, bvasilenko commented
backport