Fix issues in DisksOverviewComponent
truenas/webui pull request #10237
Opened 2024-06-24 19:28 UTC by bvasilenko

Code review should be enough

2024-06-24 19:29 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129646

2024-06-25 07:09 UTC, RehanY147 requested changes
I think we can make smaller components for better separation of concerns and code grouping here.

2024-06-27 09:32 UTC, undsoft approved these changes
Looks okay to me.

2024-06-30 11:35 UTC, merged

2024-06-30 11:35 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-129646 is targeted to the following versions which have not received their corresponding PRs: 24.04-BETA.1

2024-06-30 11:35 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.