NAS-129779: Expose Encryption in SMB service
truenas/webui pull request #10258
Opened 2024-06-28 11:45 UTC by undsoft

See ticket.

2024-06-28 11:45 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129779

2024-06-28 13:24 UTC, anodos325 commented on src/app/enums/smb-encryption.enum.ts
> +  [SmbEncryption.Default, T('Default – follow upstream / TruNAS default')],
Typo - s/TruNAS/TrueNAS

2024-07-01 14:09 UTC, RehanY147 requested changes
The options are cut off at the bottom
<img width="468" alt="image" src="https://github.com/truenas/webui/assets/24204846/c442da3f-dd58-4ae9-a407-d81e9a2bdbfa">

2024-07-02 09:29 UTC, RehanY147 approved these changes

2024-07-02 09:49 UTC, merged

2024-07-02 09:49 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.