NAS-129745: Markuplint: update packages and fix lint errors
truenas/webui pull request #10259
Opened 2024-06-28 15:05 UTC by denysbutenko

2024-06-28 15:06 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129745

2024-07-01 09:33 UTC, undsoft requested changes
I get the same error locally as in CI.

2024-07-01 09:33 UTC, undsoft commented on src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts
> +      if (!systemInfo.license?.features.includes(LicenseFeature.Dedup)) {
If license is empty like original condition suggests it can be you'll have:
`undefined.includes(LicenseFeature.Dedup)`

2024-07-01 12:57 UTC, AlexKarpov98 reviewed
Confirm, Evgeny's message.

2024-07-15 06:36 UTC, closed without merging