NAS-129686: Fix SMB ACL form
truenas/webui pull request #10271
Opened 2024-07-02 21:53 UTC by bvasilenko

**Summary**

For the special case, where **Group** combobox does not contain any suitable values to choose from,
I've changed to code to add the ability to type in a custom value from keyboard . This value is validated for being a valid existing entry in the Active Directory by the method `userService.smbUserQueryDsCache()`

**Testing**

1. Log into WebUI
2. Setup the Active directory
3. Disable AD User / Group Cache and rebuild cache
4. Save the configuration
5. Create an SMB share
6. Edit the SMB ACL
7. Add a known to exist AD Group using keyboard entry, not picking any of options of the dropdown menu (for example `AD02\domain users`)
  and/or add a User entry (for example type in `AD02\administrator`)
9. Save the ACL
10. Edit the SMB ACL
11. Observe the AD Group and/or User entry

2024-07-02 21:53 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129686

2024-07-03 07:14 UTC, denysbutenko requested changes
There were no errors when I typed unexisted user and clicked on Save. The loading state is never-ending. Let's improve error handling so users know about it.

![image](https://github.com/truenas/webui/assets/351613/cd169b48-9b8b-4519-a6f3-912815f87d91)

Also, when I choose `Who: User` and type `AD02\administrator` when I edit share again, it becomes `Who: Group`. Is it expected?

![image](https://github.com/truenas/webui/assets/351613/03cbbd36-8a34-44d2-8178-652baad4de5d)

2024-07-03 09:29 UTC, undsoft reviewed
It's kinda weird that my user entry silently becomes a group entry. I understand that we don't have time to make middleware changes, but can't we keep showing/sending BOTH as a value?

2024-07-04 11:50 UTC, undsoft reviewed
It works, but I have the following questions:
1. What does it mean to create a record with BOTH type? Can we only show this option on edit?
2. Can we call it "User or Group" or "Unknown"?

2024-07-04 20:05 UTC, bvasilenko commented
@undsoft 

> 1. What does it mean to create a record with BOTH type? Can we only show this option on edit?

We can't show this option on edit. `BOTH` type means middleware is not providing enough information for determining whether this a user or a group. As discussed with @anodos325 , middleware will introduce this capability in the upcoming releases.

> 2. Can we call it "User or Group" or "Unknown"?

Sure, I've updated the PR

2024-07-05 06:25 UTC, denysbutenko approved these changes
![image](https://github.com/truenas/webui/assets/351613/cf20cda1-eb17-4af2-aa6f-cd22d4ff324a)

![image](https://github.com/truenas/webui/assets/351613/cba6f464-359f-4c75-9db8-0534f1efa38a)
Steps:
1. Choose `AD02\administrator`
2. Replace slash with `/`
3. Click save
4. Replace slash back to `\`


![image](https://github.com/truenas/webui/assets/351613/4faf0bfd-ca2e-4bc4-8a6d-10543f22e525)

Looks good

2024-07-05 06:25 UTC, denysbutenko commented on src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
> +              <!-- TODO: Delete after the backend has support for distinguishing user from group -->
Is there a ticket number available?

2024-07-05 09:38 UTC, undsoft commented
Okay, there are more problems with how this form works, but it works to a certain extent which is better than not working completely. I'm going to merge this PR and we can improve on it later.

2024-07-05 09:38 UTC, merged

2024-07-05 09:38 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.