NAS-129944: Add new badge indicators
truenas/webui pull request #10307
Opened 2024-07-10 08:47 UTC by denysbutenko

- Added new page indicators for Dashboard and Enclosure pages.
- Added new feature indicator to Configure button on dashboard.
- Also, removed `FlexModule` dependency from `PageHeaderModule`

2024-07-10 08:47 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129944

2024-07-10 12:47 UTC, undsoft approved these changes
Okay, I think new circle can be improved, but I'll create a separate ticket for it.
This one looks good.

2024-07-10 12:47 UTC, undsoft commented on src/app/pages/dashboard/components/dashboard/dashboard.component.ts
> +    message: this.translate.instant('Try out the new dashboard configuration feature!'),
Let's remove the exclamation mark.

2024-07-10 13:18 UTC, RehanY147 requested changes
Should we rename the `"New Enclosure"` to just `"Enclosure"` and `"Enclosure"` to `"Enclosure (old)"`.

2024-07-10 13:48 UTC, denysbutenko commented
> Should we rename the `"New Enclosure"` to just `"Enclosure"` and `"Enclosure"` to `"Enclosure (old)"`.

This wasn't mentioned yet but I'm okay to do if necessary.

2024-07-11 23:12 UTC, RehanY147 approved these changes

2024-07-12 10:23 UTC, merged

2024-07-12 10:23 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.