Nas 130050
truenas/webui pull request #10325
Opened 2024-07-18 02:26 UTC by RehanY147

**Changes:**

Added a new class to the `overlay-rect` that adds the same highlight styles as the selected slot but with a white border color to all other disks in the same vdev as the currently selected slot.

**Testing:**

Mock some enclosures and test by selecting different slots. Other slots that are also part of the same vdev should also get the highlight styles but with a white border.

2024-07-18 02:27 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130050

2024-07-18 10:54 UTC, AlexKarpov98 reviewed
It works, but visually it's hard to understand what is highlighted as well.
White border is not really visible.

maybe we can use `var(--red)` or `var(--green)`?

2024-07-24 14:41 UTC, undsoft requested changes
Overall approach was approved.
1. When in vdev mode, I would keep showing a bit more color. 
2. I think we should also consider letting user switch to another vdev directly by clicking on another slot, without user having to click twice.
3. Clicking on the same slot twice should exit vdev mode.
4. Behaviour needs to be consistent whether I'm using mouse or keyboard.

2024-07-24 14:41 UTC, undsoft commented on src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.ts
> +    this.clickListener = this.renderer.listen(overlay, 'click', () => {
Time to move to a separate arrow method.

2024-07-24 14:41 UTC, undsoft commented on src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.ts
> +      this.renderer.addClass(vdevDiskSlotOverlay, 'not-selected-vdev-disk');
Feels like you can simplify this for example by not just updating overlay classes in the first for loop, or by iterating over `overlayRects`.

2024-07-28 08:04 UTC, undsoft approved these changes
Looks good. Let's add some tests.

2024-07-29 12:04 UTC, merged

2024-07-29 12:04 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.