NAS-130027: Update styles for mobile layout
truenas/webui pull request #10326
Opened 2024-07-18 05:56 UTC by denysbutenko

**Changes:**

- Add padding to the layout container. 
- Rename `spltiview.scss` into `variables.scss`. 
- Update styles to use variables.

**Testing:**

Test the UI on mobile and tablets when `Show Console Messages` is on and off. See the ticket for an issue demo.

2024-07-18 05:56 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130027

2024-07-19 02:00 UTC, RehanY147 requested changes
This branch is up to date with master and we have already solved the issue with the Help widget on master. So, I don't know why but the wrong scroll styles on smaller screens for help widget is still an issue. See video.

https://github.com/user-attachments/assets/b3ce5c72-1dfa-4178-8e29-4968deb4522e

2024-07-19 02:19 UTC, denysbutenko commented
> This branch is up to date with master and we have already solved the issue with the Help widget on master. So, I don't know why but the wrong scroll styles on smaller screens for help widget is still an issue. See video.
> 
>  Screen.Recording.2024-07-19.at.6.58.06.AM.mov

Good catch. Adjusted styles on non-enterprise systems.

2024-07-19 02:35 UTC, RehanY147 approved these changes
Looks good

2024-07-19 02:54 UTC, merged

2024-07-19 02:54 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.