NAS-130129: Update datapoint widget and arbitary settings
truenas/webui pull request #10349
Opened 2024-07-24 05:01 UTC by denysbutenko

**Changes:**

- Updated widget with custom text. 
- Subtext is placed on a new line. 
- The length of the subtext increased to 64 chars.

**Testing:**

Test Arbitary Widget with different slot sizes and short/long text.

2024-07-24 05:01 UTC, denysbutenko commented
Preview
![image](https://github.com/user-attachments/assets/44745e04-4b52-4e0a-89fb-d7bd13f9d3cc)

2024-07-24 05:01 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130129

2024-07-24 09:30 UTC, RehanY147 requested changes
<img width="561" alt="Screenshot 2024-07-24 at 2 28 52 PM" src="https://github.com/user-attachments/assets/da4aeb93-70d4-47e8-b911-ec408f1d38bf">
Really long text and shorter sub text makes for a weird UI experience. I think the max font size for the subtext should be bound to the font size of the text. Otherwise, it looks weird.

2024-07-25 08:54 UTC, denysbutenko commented
> <img alt="Screenshot 2024-07-24 at 2 28 52 PM" width="561" src="https://private-user-images.githubusercontent.com/24204846/351659212-da4aeb93-70d4-47e8-b911-ec408f1d38bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTU3OTcsIm5iZiI6MTcyMTg5NTQ5NywicGF0aCI6Ii8yNDIwNDg0Ni8zNTE2NTkyMTItZGE0YWViOTMtNzBkNC00N2U4LWI5MTEtZWM0MDhmMWQzOGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4MTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNDNlZTAzMDEwYTk2OGUzMjYxZTE2ODk2NDU2ZDYwN2QxZjc2MTdhZTk5YjE4NTAyZDRhMDk4OGE4NTY5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k3bSquJKsBSgTzdts5g1xVyVqluswePVC1Hv9JaHBE0"> Really long text and shorter sub text makes for a weird UI experience. I think the max font size for the subtext should be bound to the font size of the text. Otherwise, it looks weird.

Agreed

2024-07-27 00:07 UTC, RehanY147 approved these changes

2024-07-27 04:11 UTC, merged

2024-07-27 04:11 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.