Nas 130063
truenas/webui pull request #10362
Opened 2024-07-26 08:58 UTC by denysbutenko

**Changes:**

- Refactor DiskTemperature service.
- More usage of TemperatureUnit enum

**Testing:**

Use a system on MINI model.

2024-07-26 08:58 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130063

2024-07-27 01:30 UTC, RehanY147 requested changes
Lots of code is commented out. Is it ready for review?

2024-07-27 05:28 UTC, denysbutenko commented
> Lots of code is commented out. Is it ready for review?

Yeah it's ready. Just updated old enclosure pages as well.

2024-07-30 06:29 UTC, RehanY147 requested changes
It looks good for the most part.

2024-07-30 08:28 UTC, RehanY147 approved these changes

2024-07-30 10:36 UTC, merged

2024-07-30 10:36 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.