NAS-130284: A11y improvements
truenas/webui pull request #10369
Opened 2024-07-28 12:41 UTC by undsoft

**Changes:**

Fixes some of screen reader issues:
- Adds landmarks.
- Prevents show/hide password button from submitting the form when it is pressed via keyboard.
- Will read aloud snackbar and alert messages.

**Testing:**

Instructions on how to use voiceover on mac https://www.unimelb.edu.au/accessibility/tools/testing-web-pages-with-voiceover
Test some of the affected places.
There are a number of other issues that this PR does not address.

2024-07-28 12:41 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130284

2024-07-30 06:45 UTC, RehanY147 requested changes
Can't navigate onto the sub-menu items

2024-07-30 08:17 UTC, undsoft commented
This is known and not part of this PR.

2024-07-31 09:12 UTC, RehanY147 approved these changes

2024-07-31 09:13 UTC, merged

2024-07-31 09:14 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.