NAS-129910: Enclosure various improvements
truenas/webui pull request #10383
Opened 2024-07-31 18:19 UTC by bvasilenko

**Testing:**

Navigate to **Enclosure** page. And please see ticket for the list of expected fixes

2024-07-31 18:19 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129910

2024-08-01 07:08 UTC, undsoft requested changes
I would suggest adding 

```
expansionModels: Object.values(EnclosureModel),
```

to environment ts and checking other models.

I've noticed at least the following issues:
1. ES60 doesn't fit the screen both in main view and on enclosure switcher.
2. Enclosure selector doesn't fit the screen.
3. Tablet view doesn't look too good with selector being too tall, legends not being visible. 
<img width="1156" alt="Снимок экрана 2024-08-01 в 09 06 11" src="https://github.com/user-attachments/assets/923990f7-4fa2-450c-bcc0-1e285ae13326">

4. On some resolutions there are no margins between enclosure image and enclosing box. 
<img width="942" alt="Снимок экрана 2024-08-01 в 09 08 01" src="https://github.com/user-attachments/assets/cfaa0579-2b3d-4b43-974a-19fb9e562353">

2024-08-01 07:11 UTC, AlexKarpov98 reviewed
Agree with Evgeny.

2024-08-06 13:26 UTC, AlexKarpov98 approved these changes

2024-08-07 04:29 UTC, merged

2024-08-07 04:29 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.