Check smart supports before showing Run Manual Test button
truenas/webui pull request #10397
Opened 2024-08-05 09:50 UTC by denysbutenko

**Changes:**

Fix TODO. Add check if disk supports smart. Update tests.

**Testing:**

Open Devices page and check if `Run Manual Test` button appears correctly.

2024-08-05 09:51 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130412

2024-08-05 09:51 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130412

2024-08-06 04:37 UTC, denysbutenko commented
> Can we update `loadNodes` in `DevicesStore` instead to load extra field?

Getting an error from `disk.query`:

```[EFAULT] `supports_smart` cannot be queried if disk count is greater than 1```

Or did you mean to move getting data from card component into store?

2024-08-06 07:49 UTC, undsoft reviewed
No, that's what I meant. Just thought we could avoid making another call.
We seem to be using different method to determine whether Manual test button is available on Devices page and on Disks page.
I've asked Vladimir about it here: https://ixsystems.atlassian.net/browse/NAS-116969

2024-08-07 07:15 UTC, undsoft requested changes
After checking with Vladimir, it seems that `supports_smart` in `disk.get_instance` means that disk supports SMART monitoring in general and `smart.test.disk_choices` means that disk may support SMART tests. 

Therefore using `supports_smart` in here to show/hide test button is not correct.

2024-08-08 09:53 UTC, undsoft approved these changes
Looks good.

2024-08-08 09:53 UTC, undsoft commented on src/app/pages/storage/modules/devices/stores/devices-store.service.ts
> +            this.patchState({ disksWithSmartSupport: Object.values(disksWithSmartSupport) });
Would be good to keep naming more specific. Here for example, it's not just disks with smart support, it's disks that support running a smart test.

2024-08-08 09:53 UTC, undsoft commented on src/app/pages/storage/modules/devices/stores/devices-store.service.ts
> +  readonly diskWithSmartSupport$ = this.select((state) => state.disksWithSmartSupport);
disk => disks

2024-08-08 09:53 UTC, undsoft commented on src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.spec.ts
> +  it('checks if disk do not supports SMART', () => {
"does not show Run Manual Test when disks does not support smart tests"

2024-08-08 12:14 UTC, merged

2024-08-08 12:14 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.