NAS-129364: "There are unapplied network interface changes" window is displayed incorrectly
truenas/webui pull request #10396
Opened 2024-08-05 09:14 UTC by AlexKarpov98

**Changes:**

New warning dialog is added to inform user that we have restored the previous network configuration to ensure continued connectivity.

**Testing:**
See ticket.
Try updating network interface Aliases with `9.9.9.9` for example.
You can set 10 seconds to wait less time.

Result:
<img width="1728" alt="Screenshot 2024-08-05 at 12 05 09" src="https://github.com/user-attachments/assets/effbca99-41d0-44c1-9672-278ded50ca5b">

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | New dialog is added in case of `Network Reconnection Issue`

2024-08-05 09:15 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129364

2024-08-06 06:07 UTC, denysbutenko requested changes
On nightly HA VM (Failover Disabled). 

When I change the address in `IP Address (This Controller)*,` the `Test Changes` button appears, and I press it. A few moments later, I saw the sign-in page and log in as usual. There were no popups or `test changes` section present.

When I change two fields `IP Address (This Controller)*` and `IP Address (TrueNAS Controller 2)*` it applies without testing changes and connectivity with a system is lost.

2024-08-06 11:24 UTC, AlexKarpov98 commented
@denysbutenko - for me it seems like a middleware issue. (only for HA system, Vladimir Vinogradenko approved)

Since after test changes we are just locked and no way back.
It only worked fine when i updated all the IP fields to be 1.1.1.1
And then I’ve seen TEST CHANGES as well and IP’s were rolled back and I showed up a message (Network Reconnection Issue)

Vladimir Vinogradenko 👇  confirmed it as well (but it's only an issue for HA system and specific cases @denysbutenko described)
`Hi, thank you for this information, we’ll fix it`
`Looks like a middleware issue, yes`

I tested with `non HA` system - and it works fine there. There we can only set one `IP Address`
See `non HA` system in action ⬇️ 

https://github.com/user-attachments/assets/95e206e9-cbf2-4665-8582-ab4ae6ac6e23

2024-08-06 15:14 UTC, denysbutenko approved these changes
Looks good

2024-08-06 15:18 UTC, merged

2024-08-06 15:19 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.