NAS-130259: Ensure alphabetical order of shares on Shares dashboard
truenas/webui pull request #10395
Opened 2024-08-05 07:46 UTC by denysbutenko

**Changes:**

1. Fix sort on `SMB`, `NFS` and `iSCSI` cards
2. Sync behavior between mentioned cards
3. Use `ix-table-pager-show-more` component for `View All` button
4. Update `ix-table-pager-show-more` to use signals
5. Add router support in `ix-table-pager-show-more`
6. Minor cleanup

**Testing:**

Go to the Sharing dashboard. Create 5 or more shares for each card.

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | Minor UI changes for `View All` button

2024-08-05 07:46 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130259

2024-08-07 12:57 UTC, RehanY147 requested changes
The sorting isn't applied by default in the smb card. `pool` comes before `ds` it doesn't change if I change sorting from Asc to Desc in the code.

2024-08-07 12:57 UTC, RehanY147 commented on src/app/pages/sharing/components/shares-dashboard/iscsi-card/iscsi-card.component.ts
> +      active: 0, // index column
Instead of a comment, it would be better to create a variable and use that instead of just `0`. Like `let activeColumnIndex = 0`

2024-08-09 06:33 UTC, AlexKarpov98 approved these changes
Works good 👍 

Please fix SBM list default sorting as well.
See:

https://github.com/user-attachments/assets/421673c2-7d90-4403-908b-3875b4b44d6e

2024-08-09 11:47 UTC, denysbutenko commented
Thanks for review, @AlexKarpov98. I have fixed default sorting on list pages for SMB, NFS and iSCSI

2024-08-10 00:35 UTC, RehanY147 approved these changes

2024-08-10 00:35 UTC, merged

2024-08-10 00:35 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.