Update data-test tag for show-more button
truenas/webui pull request #10437
Opened 2024-08-12 17:16 UTC by denysbutenko

**Changes:**

Update data-test tag for table pager show more component

**Testing:**

Create at least 5 shares to see `View All` button for SMB, NFS, iSCSI
Check data-test tag.

2024-08-12 17:16 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130566

2024-08-13 11:52 UTC, RehanY147 requested changes

2024-08-13 11:52 UTC, RehanY147 commented on src/app/modules/ix-table/components/ix-table-pager-show-more/ix-table-pager-show-more.component.ts
> +  ixTestOverride = input<string[]>([]);
This should be `input.required`

2024-08-14 15:35 UTC, RehanY147 approved these changes
Looks good

2024-08-14 15:37 UTC, merged

2024-08-14 15:37 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-130566 is targeted to the following versions which have not received their corresponding PRs: 24.10-RC.1

2024-08-14 15:37 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-08-15 07:15 UTC, denysbutenko commented
backport