NAS-130254 / 25.04 / Setting UK/GB date results in error in Reporting graphs
truenas/webui pull request #10465
Opened 2024-08-14 12:46 UTC by AlexKarpov98

**Changes:**
Added locale service tests & added new method to correctly convert string date to Date() object.

**Testing:**
See ticket.
Try affected files. (As well fixed dashboard widgets)

**new Date() Bug logic:**
It's because the Date constructor in JavaScript expects the date string to be in a format that it can parse correctly. The format DD/MM/YYYY HH:MM:SS is not natively supported by the Date constructor, leading to an “Invalid Date” error.

2024-08-14 12:47 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130254

2024-08-15 14:15 UTC, undsoft requested changes
So I'm confused about the code that we use in uptime calculations.
Currently we take a date, the format it, then parse it back and then add seconds to it.
Why not take a date, add seconds and then format it?

2024-08-15 14:21 UTC, AlexKarpov98 commented
> So I'm confused about the code that we use in uptime calculations. Currently we take a date, the format it, then parse it back and then add seconds to it. Why not take a date, add seconds and then format it?

@undsoft  - currently - we have a string date, convert it to real date and adding seconds then.
We don't have a Date() initially, but `string date`

2024-08-19 09:58 UTC, undsoft approved these changes
I still think there is something fishy going on with uptime, but we can look into it later.
Using different date formats no longer breaks pages.

2024-08-19 12:27 UTC, merged

2024-08-19 12:27 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.