Update cs.json
truenas/webui pull request #10478
Opened 2024-08-15 23:00 UTC by markrieder

**Changes:**

**Testing:**

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   |

2024-08-16 07:36 UTC, undsoft requested changes
Thank you for your contribution. There are a couple of syntax mistakes in your json file.

2024-08-16 07:36 UTC, undsoft commented on src/assets/i18n/cs.json
> +  "Allow non-unique serialed disks (not recommended)": "  "Admin Password": "Heslo administrátora",
Syntax error here.

2024-08-16 07:36 UTC, undsoft commented on src/assets/i18n/cs.json
> +  "Allow all sudo commands with no password": "Povolit všechny sudo příkazy bez hesla  "Admin Password": "Heslo administrátora",
Syntax error.

2024-08-16 13:56 UTC, AlexKarpov98 reviewed
Agree with Evgeny.

2024-09-13 09:19 UTC, AlexKarpov98 commented
@undsoft  @markrieder - that's the maximum I was able to fix.

This PR https://github.com/truenas/webui/pull/10316/files has more translations, but they all are incorrectly formatted, and I don't know how to inject them properly, and seems it'll be easier to add them again, instead of trying to understand where to inject which phrase.

<img width="259" alt="Screenshot 2024-09-13 at 12 16 38" src="https://github.com/user-attachments/assets/517e7bbe-fe53-4e5e-95a9-b9f1827f2790">

It's better to create a new PR, for the missing translations, please. 

@markrieder - thank you for your contribution. 
Please go ahead and add more translations, now you have a correct understanding how it works ✊

2024-09-16 08:40 UTC, undsoft approved these changes

2024-09-16 08:40 UTC, merged