NAS-130607: Mobile adjustments for dashboard widgets
truenas/webui pull request #10507
Opened 2024-08-20 13:48 UTC by AlexKarpov98

**Changes:**

Adjustments for widgets (mobile view)

**Testing:**

See ticket, check all of the widget with all sizes. 
Try to find any regression.

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | Adjustments for widgets (mobile view), maybe there are some screenshots

2024-08-20 13:48 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130607

2024-08-21 10:36 UTC, RehanY147 requested changes
Looks good for the most part. Two complaints.
1. These labels like "Disks ..." which are unreadable. We should make them readable or remove them. Maybe just show a tooltip or something? But as is, they are not readable in this short form.
<img width="385" alt="Screenshot 2024-08-21 at 3 34 49 PM" src="https://github.com/user-attachments/assets/fa36bc1a-cd89-48d0-8dda-7af63cae745c">

2. The CPU usage for quarter size has no title. No way to tell what is being shown. 
<img width="295" alt="Screenshot 2024-08-21 at 3 35 19 PM" src="https://github.com/user-attachments/assets/e4df19fc-1beb-46d9-8ea9-d5167fa259a2">

2024-08-22 08:54 UTC, AlexKarpov98 commented
@RehanY147 
Updates are there
<img width="193" alt="Screenshot 2024-08-22 at 11 40 32" src="https://github.com/user-attachments/assets/089a2fdf-2615-43df-bab0-f8a94866377c">
<img width="381" alt="Screenshot 2024-08-22 at 11 49 26" src="https://github.com/user-attachments/assets/67b9c995-2c15-4596-a1ea-412c2ea5c559">
<img width="390" alt="Screenshot 2024-08-22 at 11 49 58" src="https://github.com/user-attachments/assets/f677d5fa-48d3-4720-9d3d-a4f7f3bf42ff">

2024-08-22 21:53 UTC, RehanY147 approved these changes

2024-08-22 22:22 UTC, merged

2024-08-22 22:22 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.