Optimize app.query calls
truenas/webui pull request #10569
Opened 2024-08-28 08:13 UTC by denysbutenko

**Changes:**

Optimize app.query calls

**Testing:**

See ticket for details

2024-08-28 08:13 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130767

2024-08-29 06:46 UTC, RehanY147 requested changes
When I install a new app, for the first time, the installed-apps page doesn't update. It continues to show me empty message.

2024-08-29 06:56 UTC, denysbutenko commented on src/app/pages/apps/store/installed-apps-store.service.ts
> +      debounceTime(300),
Coz observable emits two values in a short period that causes two websocket calls.

2024-09-04 08:36 UTC, RehanY147 requested changes
I don't think the debounceTime operator is the correct solution here. That just puts a patch on the problem. When using UI with a remote and slow server, the 300 millisecond could be avoided. We should instead aim to fix the condition which preceeds the `app.query` call twice.

2024-09-09 07:55 UTC, denysbutenko commented
> I don't think the debounceTime operator is the correct solution here. That just puts a patch on the problem. When using UI with a remote and slow server, the 300 millisecond could be avoided. We should instead aim to fix the condition which preceeds the `app.query` call twice.

Well, I think it is related to this:

```
readonly isDockerStarted$ = this.select((state) => {
    return [
      DockerStatus.Initializing,
      DockerStatus.Pending,
      DockerStatus.Running,
    ].includes(state.statusData.status as DockerStatus);
  });
```

The `isDockerStarted` checks for non-started statuses and emits intermediate values.
Let's scope `isDockerStarted` to `DockerStatus.Running` only and remove `debounceTime` operator.

2024-09-09 09:11 UTC, denysbutenko commented
Okay, I found the root cause. There was a check for a boolean when the response was an array of booleans. That was fixed.

2024-09-09 12:01 UTC, RehanY147 approved these changes

2024-09-09 13:37 UTC, AlexKarpov98 approved these changes

2024-09-10 08:45 UTC, merged

2024-09-10 08:46 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.