Add custom app form
truenas/webui pull request #10586
Opened 2024-08-30 09:07 UTC by RehanY147

**Changes:**

Adds a form to install apps using custom YML config

**Testing:**

Go to the apps discover page, and click on the `'Custom App'` button. Enter a unique app name and enter this config in the `"Custom Config"` input.
```
services:
  nginx:
    image: nginx:latest
    ports:
      - "8580:80"
    restart: unless-stopped
```

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | Adds a form to install custom app with YAML config

2024-08-30 09:08 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129579

2024-09-02 07:31 UTC, bvasilenko requested changes

2024-09-02 07:31 UTC, bvasilenko commented on src/app/pages/apps/components/custom-app-form/custom-app-form.component.ts
> +    this.addForbiddenAppNamesValidator();
I've noticed that the form could not pass validation when there's no installed apps. I'd double check the validation logic.

2024-09-03 08:11 UTC, undsoft reviewed
Looks good in general. Can we have code-editor have at least 3 lines by default?

2024-09-03 08:11 UTC, undsoft commented on src/app/pages/apps/components/custom-app-form/custom-app-form.component.scss
Empty file can removed.

2024-09-03 08:11 UTC, undsoft commented on src/app/pages/apps/components/available-apps/custom-app-button/custom-app-button.component.html
> +<!-- @if (false) { -->
You can just remove this.

2024-09-03 08:11 UTC, undsoft commented on src/app/pages/apps/components/custom-app-form/custom-app-form.component.spec.ts
> +    spectator.component.form.patchValue({
When writing tests it's best to cover public interfaces of whatever you are testing. In this case `form` is an implementation detail of the component. It's not mean to be interacted with directly. It should be `protected` really. You should test form by interacting with controls.

2024-09-03 08:21 UTC, RehanY147 commented
@bvasilenko Can you provide steps to reproduce the validation issue? It's working for me.

2024-09-04 13:22 UTC, undsoft approved these changes
Looks good.

2024-09-04 19:01 UTC, bvasilenko commented
@RehanY147 curerntly I cannot reproduce the issue any more

2024-09-04 19:01 UTC, bvasilenko approved these changes
Works good!

2024-09-05 06:50 UTC, merged

2024-09-05 06:50 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-129579 is targeted to the following versions which have not received their corresponding PRs: 24.10-RC.1

2024-09-05 06:50 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-09-06 14:33 UTC, undsoft commented
backport