NAS-130956: Reduce numbers of layout shifts on login page
truenas/webui pull request #10612
Opened 2024-09-03 10:56 UTC by AlexKarpov98

**Changes:**
Reduced numbers of layout shifts on login page

**Testing:**
See ticket and try it in action.

See how it works if I log in for the first time, see layout shifts fixes.
As well once I was logged in, I reloaded the page. (see)👇 

**BEFORE:**

https://github.com/user-attachments/assets/f2510e9c-20a3-4c40-ab15-4cae81251990

**AFTER:**

https://github.com/user-attachments/assets/25052085-b0ca-4121-a18a-fc121fd16fa1

_Note: No tests added before the final approve._

2024-09-03 10:56 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130956

2024-09-04 19:00 UTC, bvasilenko approved these changes
Loading of the login page looks good!

2024-09-05 16:07 UTC, undsoft requested changes
1. If you restart middleware with `service middlewared restart` you'll still get `Please wait` with the message, even though you are not being logged in and waiting may not help if there is no connectivity. We should only show that message when we are actively logging user in.
2. We should change `Please wait` to `Logging in...`
3. There is a lot of empty space on main login form now, I think we should do something about it.
4. If the system is managed by truecommand and has HA, there is a scrollbar.
5. I'm fine with changing how `FailoverStatusComponent` works. For example, we could show `HA is enabled (?)` with a tooltip for active IP addresses. We could show `HA is disabled: reason` when there is one reason and `HA is disabled (?)` when there are many.
6. We could also avoid showing validation errors in the form, but we need to make snackbar more prominent then.
7. Page doesn't look correct when you connect to a standby controller. This is how used to look. You can test it by connecting by adding `a` or `b` to hostname of our m40.
<img width="534" alt="Снимок экрана 2024-09-05 в 18 06 12" src="https://github.com/user-attachments/assets/959c9e3e-5773-4b1f-bf5e-7b8bb458854f">

8. If set password form has scrollbar, we need to make to make adjustments to it as well. I'm fine with it having a different height there.

2024-09-09 10:56 UTC, AlexKarpov98 commented
@undsoft please give it a try now. It's a bit tricky with that `Logging in` show up.

I think we can remove it, if it created more problems than benefits?

2024-09-10 09:17 UTC, undsoft requested changes
Initial login flow looks fine, however I could live without Logging you in after submitting the form.
When reloading the page, I could live without "Connecting to TrueNAS" message at least for some time. I think there should be some period where we expect connection to happen and we don't show this dialog.
Also "Connecting to TrueNAS" is too wide now for some reason.

2024-09-10 09:17 UTC, undsoft commented on src/app/services/auth/auth.service.ts
> +  instantAuthTokenValue$ = new BehaviorSubject<string>(this.window.localStorage.getItem('ngx-webstorage|token'));
This relies on internal implementation of a 3rd party. Is there a way to just read value from `token`?

2024-09-10 12:29 UTC, AlexKarpov98 commented
@undsoft  - updatred:

https://github.com/user-attachments/assets/fcf25d49-4c04-4aeb-8346-1dcfd6830060

2024-09-12 09:04 UTC, undsoft requested changes
Better, but still some things to fix:
1. When connecting to a standby controller, I think it would be helpful to disable inputs as well, otherwise it's not immediately obvious why I cannot click Login.
2. I've used Reset Configuration option in General Settings and it kept saying Logging in.
3. If you use non-existent url for webui, it will still present a login form for a second before switching to "Connecting to TrueNAS" message. I think we should keep longer in previous loading state before showing login form as we attempt to establish a WS connection.

2024-09-12 09:07 UTC, AlexKarpov98 commented
> Better, but still some things to fix:
> 
> 1. When connecting to a standby controller, I think it would be helpful to disable inputs as well, otherwise it's not immediately obvious why I cannot click Login.
> 2. I've used Reset Configuration option in General Settings and it kept saying Logging in.
> 3. If you use non-existent url for webui, it will still present a login form for a second before switching to "Connecting to TrueNAS" message. I think we should keep longer in previous loading state before showing login form as we attempt to establish a WS connection.

@undsoft  we shod `LOGGING IN` only if user has token and if token `isTokenWithinTimeline` 
probably there may be cases when token is not cleared up?
for this one: `I've used Reset Configuration option in General Settings and it kept saying Logging in.`

2024-09-13 08:01 UTC, AlexKarpov98 commented
@undsoft 

```
3. If you use non-existent url for webui, it will still present a login form for a second before switching to "Connecting to TrueNAS" message. I think we should keep longer in previous loading state before showing login form as we attempt to establish a WS connection.
```

Problem is that if we'll show loading screen on invalid url, it as well will be shown before valid TRUE NAS url for web ui. And we'll loose that immediate sign in form rendering.

We show LOGGING IN message only if user has `token` and `isTokenWithinTimeline`

As discussed - `<ix-disconnected-message />` is showed with delay,  currently it's `2 sec`.
SO we only show it if we are not connected yet after 2 seconds.

2024-09-13 08:08 UTC, AlexKarpov98 commented
```I've used Reset Configuration option in General Settings and it kept saying Logging in.```

I see: 
```Connecting to TrueNAS ... Make sure the TrueNAS system is powered on and connected to the network.```

And if I reload the page I see `Logging in...` - but it's shown because we have `token` and it's `isTokenWithinTimeline`

2024-09-16 08:47 UTC, undsoft commented
I understand how it currently works, but I am saying that maybe we could keep showing flashing TrueNAS login animation until websocket connection is established. This way we won't have situations where it says "logging in" for an offline system.

2024-09-16 09:57 UTC, AlexKarpov98 commented
> I understand how it currently works, but I am saying that maybe we could keep showing flashing TrueNAS login animation until websocket connection is established. This way we won't have situations where it says "logging in" for an offline system.

Yeah, I got it, I think that's the only way.

2024-09-16 12:08 UTC, undsoft requested changes
It's a bit worse now. My WS connection took 500ms to establish, yet I still saw establishing connection on initial page load.

https://github.com/user-attachments/assets/7ec6f3a7-08d9-4fe4-a794-b38814b556fa

2024-09-16 12:49 UTC, AlexKarpov98 commented
@undsoft now it's updated to show True NAS logo as a fallback if we are not logged in or not connected to the WS (for 1 second)

User Logged In

https://github.com/user-attachments/assets/82d653cd-33e4-49cc-b1fb-f04e10af9ecc

And screen like that if we are not connected and more than 1 sec waiting

https://github.com/user-attachments/assets/746679f1-4753-464a-b90e-f0e9d43c0008

2024-09-16 13:28 UTC, undsoft approved these changes
Thanks. Nice work 👍🏼

2024-09-16 21:03 UTC, merged

2024-09-16 21:03 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.