NAS-130848: Add apps stats
truenas/webui pull request #10620
Opened 2024-09-04 14:57 UTC by denysbutenko

**Changes:**

Add apps stats on installed apps 

**Testing:**

Check installed apps page

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | UI changes

2024-09-04 14:57 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130848

2024-09-05 15:22 UTC, undsoft approved these changes
Looks good overall.

2024-09-05 15:26 UTC, AlexKarpov98 approved these changes

2024-09-09 12:00 UTC, denysbutenko commented on src/app/pages/dashboard/widgets/apps/common/app-network-info/app-network-info.component.html
> +        {{ stats.networks[0].rx_bytes | ixNetworkSpeed }}
I noted this in the [ticket](https://ixsystems.atlassian.net/browse/NAS-131073)

2024-09-09 12:08 UTC, undsoft requested changes

2024-09-09 12:08 UTC, undsoft commented on src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
> +      {{ stats().networks[0].rx_bytes | ixNetworkSpeed }}
Commented in incorrect place. App widgets can be fixed later, but network stats need to be fixed here now.

2024-09-09 13:19 UTC, undsoft approved these changes
Looks good, thanks.

2024-09-09 13:41 UTC, merged

2024-09-09 13:41 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.