NAS-130955: Implement `IxResourcesService`
truenas/webui pull request #10623
Opened 2024-09-05 21:34 UTC by bvasilenko

**Changes:**

An attempt to establish a new kind of service, which will resolve the problem described in the ticket.

**Testing:**

1. Double check that the ticket's requirements are met
2. Code review

2024-09-05 21:35 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130955

2024-09-12 08:20 UTC, undsoft requested changes
Am I missing something? How is this different from what I've reviewed previously?

2024-09-12 09:46 UTC, bvasilenko commented
>  Am I missing something? How is this different from what I've reviewed previously?

@undsoft  Sorry, I've pushed same version again. Now this PR contains an updated version.

2024-09-16 08:53 UTC, undsoft requested changes
These requirements should be handled by the new store and not left for developers to implement:
> 1. Data is loaded lazily, when it is needed.
> 3. It should be possible to invalidate data.

It would also be good to see examples of these and other requirements, like "mockable and testable".

The output of this ticket is a clear way for developers to use this global data.

2024-09-19 10:55 UTC, undsoft approved these changes
Overall looks good, let's see how it behaves in action.

2024-09-19 10:55 UTC, undsoft commented on src/app/pages/dashboard/services/widget-resources.service.ts
> +  appStore = globalStore('app.query');
Let's move these to constants somewhere so that new injectors are not created every time.

2024-09-19 10:55 UTC, undsoft commented on src/app/pages/dashboard/services/widget-resources.service.spec.ts
> +    mockGlobalStore({
It would be good to refactor `mockGlobalStore`, so that it's mock like other provider mocks and not a separate global function.

2024-09-23 13:10 UTC, merged

2024-09-23 13:11 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.