NAS-131130: Refactor `subscribeToInstalledAppsUpdates` in `installed-apps-store.service`
truenas/webui pull request #10741
Opened 2024-09-24 08:31 UTC by AlexKarpov98

Refactoring.

2024-09-24 08:32 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131130

2024-09-25 08:09 UTC, denysbutenko commented
I have been looking into this code for the last few days. Some points that I highlighted:

- We may need to split the logic for installed apps and available apps into corresponding files.
- `app.query` have support `callAndSubscribe` to handle collection changes
- `recommendedApps` is a subset of `availableApps` like computed property.

Just shared thoughts, this is not a call to action

2024-09-25 08:12 UTC, AlexKarpov98 commented
@denysbutenko - thanks.
My original thoughts regarding this PR - is just refactoring, to make it much easier to read and understand the code.

2024-09-25 22:09 UTC, RehanY147 requested changes

2024-09-25 22:09 UTC, RehanY147 commented on src/app/pages/apps/store/installed-apps-store.service.ts
> +        console.error('Unknown API event type (installed-apps-store.service):', apiEvent.msg);
We shouldn't expose code details in console logs. Also, this has a potential to expose sensitive info from the api event to the console. We shouldn't be logging the message itself.

2024-09-27 11:20 UTC, RehanY147 approved these changes

2024-09-27 11:28 UTC, merged

2024-09-27 11:29 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.