NAS-131191: Fix title on Apps Volumn Mounts dialog
truenas/webui pull request #10777
Opened 2024-10-01 11:49 UTC by denysbutenko

**Changes:**

Added humanReadableKey pipe to make service name looks better

**Testing:**

Check title on Volumn Mount dialog

2024-10-01 11:49 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131191

2024-10-01 11:52 UTC, stavros-k commented
The title in human readable form is already defined in apps side. We shouldn't need to do this here.

I've referenced a ticket in the original one, that might actually cause the issue on the UI

2024-10-01 21:52 UTC, RehanY147 requested changes
Please address review by Stevros.

2024-10-02 10:11 UTC, denysbutenko commented
> The title in human readable form is already defined in apps side. We shouldn't need to do this here.
> 
> I've referenced a ticket in the original one, that might actually cause the issue on the UI

Okay let's close this then

2024-10-02 10:11 UTC, closed without merging