NAS-131641: Directory Services Cards -> Different card for Kerberos Settings
truenas/webui pull request #10823
Opened 2024-10-08 10:35 UTC by AlexKarpov98

Code review is enough.

2024-10-08 10:36 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131641

2024-10-08 10:44 UTC, denysbutenko requested changes
I thought we decided to not round mat-cards like on main dashboard. Is it was changed?

2024-10-08 10:46 UTC, AlexKarpov98 commented
> I thought we decided to not round mat-cards like on main dashboard. Is it was changed?

I don't know, but have a look at `Advanced settings`

![image](https://github.com/user-attachments/assets/907f6003-3587-4732-a247-eecd0e9fb3b7)

It's kind of weird when 3 cards have rounded corners and 1 card does not have it.

2024-10-08 15:05 UTC, denysbutenko approved these changes
Okay lets revisit it later

2024-10-09 10:33 UTC, merged

2024-10-09 10:33 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.