NAS-131656: Better handling for invalid cron schedules
truenas/webui pull request #10824
Opened 2024-10-08 14:52 UTC by AlexKarpov98

Testing: see ticket.

Try setting up with invalid cron configuration.

Result:
<img width="732" alt="Screenshot 2024-10-08 at 16 09 48" src="https://github.com/user-attachments/assets/418e883e-1bab-4e43-a832-326cd40ee20e">

2024-10-08 14:53 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131656

2024-10-08 23:58 UTC, RehanY147 requested changes
Looks good. The table doesn't error out now and you see an error message. Although, since this is an error, we need to make it more apparent with a red color or an error icon next to it in red so it jumps out to the user that there is a problem.

2024-10-09 13:24 UTC, AlexKarpov98 commented
@RehanY147 
<img width="898" alt="Screenshot 2024-10-09 at 15 49 28" src="https://github.com/user-attachments/assets/957024b4-f136-454a-80a5-6f8a400fef45">

2024-10-11 12:44 UTC, RehanY147 approved these changes

2024-10-11 13:50 UTC, merged

2024-10-11 13:50 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-10-13 21:09 UTC, AlexKarpov98 commented
backport