NAS-125917: Ask user when they try to close the form after making edits
truenas/webui pull request #10844
Opened 2024-10-10 15:54 UTC by AlexKarpov98

**Changes:**
We are using 2 different slideIns. 

First one - regular SlideIn (more used) second one - ChainedSlideIn.
- For wizard we don’t always have formGroup available on the top component level and the logic is tricky where we can swap component to Advanced Form. 

I’ve implemented form-change-guard-for-slide-in.directive directive, and it will only work for SlideIn.
For ChainedSlideIn we gonna need similar solution and I think it worth of a separate ticket.

**Testing:**
See result:

https://github.com/user-attachments/assets/7693faca-a26b-4e45-976b-64bf6ac83d34

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | New functionality for the user

2024-10-10 15:54 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125917

2024-10-12 11:44 UTC, RehanY147 requested changes
The Yes button shouldn't be primary color. It portrays a positive indication. Meaning clicking Yes is the safe and recommended option. Whereas, No button is the safe bet. Yes should be Red maybe. Or make No primary color and Yes to be default.

2024-10-12 14:32 UTC, AlexKarpov98 commented
@RehanY147 - that's what's possible:
<img width="419" alt="Screenshot 2024-10-12 at 16 52 50" src="https://github.com/user-attachments/assets/6aa2375b-eef7-42f7-b617-fa14ae64ca23">

2024-10-14 12:44 UTC, undsoft approved these changes
It works. We still need a version for SlideIn2. Overriding `close` method in slide in ref is creative solution and probably not very kosher, but I can live with it for now.

2024-10-14 12:44 UTC, undsoft commented on src/app/pages/network/components/static-route-form/static-route-form.component.html
> +    <form class="ix-form-container" formChangeGuardForSlideIn [formGroup]="form" (submit)="onSubmit()">
How about just calling it `warnAboutChanges` or `warnAboutUnsavedChanges`.

2024-10-14 21:59 UTC, AlexKarpov98 commented
For Chained Slide In I've created a separate ticket to implement it:
https://ixsystems.atlassian.net/browse/NAS-131790

2024-10-15 02:56 UTC, RehanY147 requested changes
Since we only ever use slide-ins for forms, we should be able to make some assumptions like assume that slide-ins are always forms. And alter the slide-in itself. Instead of creating a new directive that could just be part of the slide-in component itself.

2024-10-15 08:28 UTC, undsoft commented
> Since we only ever use slide-ins for forms, we should be able to make some assumptions like assume that slide-ins are always forms.

I disagree. There are slide-ins in certificates that are 90% text, plus I don't really want to end up with a slide-in component that has too many responsibilities.

2024-10-15 10:25 UTC, merged

2024-10-15 10:25 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.