NAS-131317: Replaced Lifetime with Power On Hours
truenas/webui pull request #10845
Opened 2024-10-10 16:04 UTC by aiden3c

I replaced the "Lifetime" value in our smart test results with "Power On Hours Ago". This reports how many "power on hours" ago a test happened.
Power on hours are how many hours a disk has been on, the "hours ago" is the disks' total POH - the disks' POH when the test was initiated.

It would be really nice if we could track the actual timestamp of test starts, but smartctl doesn't supply that information. We could track it ourselves, but that becomes very complicated after tests overwrite their own history (scsi only reports the most recent 20 for example). I've thought of some ways to maybe track the actual "hours ago" a test was performed, but it always balloons out. After discussion with Caleb we decided that POH would be the best bet.
Regardless, it's more useful and readable than the raw disk lifetime value.

This has to be paired with this middleware PR, otherwise the key won't exist when getting the results.

2024-10-10 16:04 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131317

2024-10-10 16:07 UTC, aiden3c commented
Oh another thing I added was a "toolTip" property to our ColumnComponent, and the ix table header will use that in place of the default tooltip (just reiterating the title) if it exists

2024-10-11 08:45 UTC, undsoft requested changes
So, I don't think it's going to be obvious to the user that there is a tooltip available over table header. I'd rather we make `headerTooltip` an optional property and when supplied  show tooltip circle (`ix-tooltip`) in the header.

2024-10-11 08:45 UTC, undsoft commented on src/app/modules/ix-table/interfaces/column-component.class.ts
> +  toolTip?: string;
Better call it `headerTooltip`.

2024-10-11 08:45 UTC, undsoft commented on src/app/pages/storage/modules/disks/components/smart-test-result-list/smart-test-result-list.component.spec.ts
> +      poh_ago: 0,
Maybe add at least one value, so that it appears in the table below.

2024-10-11 08:45 UTC, undsoft commented on src/app/pages/storage/modules/disks/components/smart-test-result-list/smart-test-result-list.component.ts
> +      toolTip: '"Power On Hours" are how many hours have passed while the disk has been powered on. "Power On Hours Ago" is how many power on hours have passed since each test.',
Please wrap string with `this.translate.instant` so that it gets extracted into translation messages.

2024-10-11 08:45 UTC, undsoft commented on src/app/interfaces/smart-test.interface.ts
> +  poh_ago: number;
`poh_ago`, such a descriptive name 😅

2024-10-13 09:35 UTC, undsoft approved these changes
Looks good, tested via mocks. As long as middleware has `power_on_hours_ago` in the response, it'll be shown correctly.

Let's make the following adjustments:
1. Add `(click)="$event.stopPropagation()"` to `ix-tooltip` in `ix-table-head`, so that it doesn't trigger column sorting when tooltip is opened.
2. Align it vertically to be inline with the text.
3. Test fails in part because code picks up test in the tooltip. You can replace `Power On Hours Ago` in expect block with `expect.stringContaining('Power On Hours Ago')` for now.

2024-10-14 15:35 UTC, undsoft approved these changes
Looks good, tests need fixing.

2024-10-14 18:50 UTC, merged

2024-10-14 18:50 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.