NAS-131843: Incorrect behavior on alert actions with readonly admin
truenas/webui pull request #10905
Opened 2024-10-21 11:22 UTC by AlexKarpov98

Testing: see ticket, 

<img width="346" alt="Screenshot 2024-10-21 at 14 21 18" src="https://github.com/user-attachments/assets/6b17c80f-993a-4709-bfee-4132cac2fcf0">

Error handling added as well.
<img width="343" alt="Screenshot 2024-10-21 at 14 21 59" src="https://github.com/user-attachments/assets/468df579-5111-46dc-9e0d-e4b59507d103">

2024-10-21 11:23 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131843

2024-10-21 12:14 UTC, undsoft requested changes
<img width="399" alt="Снимок экрана 2024-10-21 в 14 09 44" src="https://github.com/user-attachments/assets/4b42587a-f71c-4d6c-ad12-47448342feb5">


1. Lock icons are far too on the right.
2. Dismiss all alerts button doesn't look disabled.
3. If I remove role checks and click Dismiss / Reopen, because of optimistic updates it stays in new incorrect state. We need to dispatch and action to revert the update on error.
4. Error appears to only be handled once, if I "dismiss" multiple alerts, I will only get an error for the new one.

There also appears to be a middleware issue for `datetime_`: https://ixsystems.atlassian.net/browse/NAS-131910?atlOrigin=eyJpIjoiNzI4ZTAwMDFkNTVjNDY0ZDgzNzg2OGI0MDE2ZDI1NjciLCJwIjoiamlyYS1zbGFjay1pbnQifQ

2024-10-22 14:31 UTC, undsoft approved these changes
Looks good, but can we align the lock icon for Dismiss All button as well?

2024-10-22 14:32 UTC, AlexKarpov98 commented
> Looks good, but can we align the lock icon for Dismiss All button as well?

for `Dismiss all` we can't do it since it's supposed to be a full width button, we can't guess absolute position for the lock icon here.

2024-10-23 11:43 UTC, merged

2024-10-23 11:43 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.