NAS-131839: Fix cpu core bar
truenas/webui pull request #10927
Opened 2024-10-25 04:31 UTC by bvasilenko

**Changes:**

Prefer number of physical cores over number of cores, which is incorrect for most CPUs.

**Testing:**

Ensure that number of cores is correct At the **Dashboard** page, at the **CPU Widget**

2024-10-25 04:32 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131839

2024-10-25 07:24 UTC, undsoft requested changes
I removed all widgets from dashboard and add a CPU overview widget.
It fails with:
> Cannot read properties of null (reading '0')
>    at _WidgetCpuComponent.parseCpuData (widget-cpu.component.ts:120:47)
>    at _WidgetCpuComponent.getCpuParams (widget-cpu.component.ts:127:23)

This was seen on a CI machine.

2024-10-28 09:26 UTC, undsoft approved these changes
Changes look good, thanks.

2024-10-29 06:55 UTC, merged

2024-10-29 06:55 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-131839 is targeted to the following versions which have not received their corresponding PRs: 24.10.1

2024-10-29 06:55 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-10-29 06:56 UTC, bvasilenko commented
backport