NAS-131862 / 25.04 / Fix reboot call
truenas/webui pull request #10933
Opened 2024-10-25 19:43 UTC by RehanY147

**Changes:**

Fixes the way UI calls the reboot command

**Testing:**

Test reboot from the top bar

2024-10-25 19:44 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131862

2024-10-26 08:52 UTC, undsoft requested changes
The same issue exists with shutdown and probably with config.reset.

2024-10-28 09:34 UTC, RehanY147 commented
@undsoft The `config.reset` call is correct. It fails though from middleware but doesn't throw a validation error so I guess it's not UI's fault.

2024-10-28 11:42 UTC, undsoft approved these changes
Looks good.

2024-10-28 12:49 UTC, merged

2024-10-28 12:50 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.