NAS-132298 / 25.04 / Add Delete and Edit actions for virtualization instances
truenas/webui pull request #10996
Opened 2024-11-07 10:38 UTC by AlexKarpov98

Testing: 

See ticket.
I fixed initial list instances loading as well, it didn't work correctly.

Known issue: Auto-start is always TRUE (unchangeable) -> William is notified about it

Result:

https://github.com/user-attachments/assets/7a97378b-d6af-4750-8019-c900c0deee23

2024-11-07 10:39 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132298

2024-11-07 14:29 UTC, undsoft requested changes
There is no need to extend instance-wizard for edit scenario. Creating and editing actions are sufficiently different for a new edit component to show in slide in.

2024-11-07 21:04 UTC, AlexKarpov98 commented
Edit form now shows up in Slide In.

<img width="1728" alt="Screenshot 2024-11-07 at 22 58 35" src="https://github.com/user-attachments/assets/1ca91989-d754-4917-93f7-23bbb0e71875">

2024-11-08 12:20 UTC, undsoft approved these changes
Save Instance button is slightly misaligned with the rest of the form, otherwise looks goo d – I was able to edit and delete a container.

2024-11-08 12:20 UTC, undsoft commented on src/app/pages/virtualization/components/all-instances/instance-list/instance-list.component.ts
> +    effect(() => {
Let's move it into its own class field.

2024-11-08 12:20 UTC, undsoft commented on src/app/pages/virtualization/components/instance-wizard/select-image-dialog/select-image-dialog.component.ts
> +    private dialogRef: MatDialogRef<InstanceWizardComponent>,
Actually incorrect reference here. DialogRef refers to the component that was open, so SelectImageDialog in this case.

2024-11-08 12:20 UTC, undsoft commented on src/app/interfaces/api/api-call-directory.interface.ts
> +  'virt.instance.get_instance': { params: [instanceId: string]; response: VirtualizationInstance };
Not used, can be removed.

2024-11-08 12:20 UTC, undsoft commented on src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.ts
> +          this.router.navigate(['/virtualization/view', result?.id]);
Hah, interesting bug.

2024-11-09 22:34 UTC, merged

2024-11-09 22:34 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.