NAS-132334: Add environment variables to containers
truenas/webui pull request #11015
Opened 2024-11-12 12:42 UTC by AlexKarpov98

**Testing:**

See ticket, result:

https://github.com/user-attachments/assets/34ed18f0-a77c-4ce4-aaf8-d4b5851719ed

2024-11-12 12:43 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132334

2024-11-12 13:45 UTC, denysbutenko commented on src/app/pages/virtualization/components/all-instances/instance-details/instance-general-info/instance-general-info.component.html
> +      @if (instance.environment && objectKeys(instance.environment).length) {
hey Alex I just found that `keyvalue` pipe could be used natively

https://github.com/truenas/webui/blob/21722ce6654cb70801715c47f98d67cc81cd9bd9/src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html#L88

2024-11-13 10:22 UTC, RehanY147 requested changes
Should be added to the edit form as well

2024-11-13 10:22 UTC, AlexKarpov98 commented
> Should be added to the edit form as well

In ticket it only says about Creation Form, maybe for edit form there will be separate ticket.

2024-11-14 06:19 UTC, denysbutenko approved these changes
Otherwise looks good for me.

2024-11-14 06:19 UTC, denysbutenko commented on src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.html
> +            [label]="'Environment Variable ' + (i + 1)"
This label needs `translate` pipe (and one below)

2024-11-14 22:24 UTC, RehanY147 approved these changes

2024-11-15 11:22 UTC, merged

2024-11-15 11:22 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.