NAS-131796: Fix styles for `ix-code-editor`
truenas/webui pull request #11105
Opened 2024-11-27 23:50 UTC by RehanY147

**Changes:**

Changes theme. But doesn't change much visually.

**Testing:**

Test the custom app yaml form. You should see some code editor styles. Line numbers and changed background color.

2024-11-27 23:50 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131796

2024-11-28 06:55 UTC, AlexKarpov98 requested changes
Hey, I tested it out and found problems, see the video:

https://github.com/user-attachments/assets/6951493f-bd14-4380-9d03-43b78d558336

2024-11-28 22:41 UTC, RehanY147 commented
@AlexKarpov98 This is just means to provide very basic help as a code editor. This editor is for yml language. There's no syntax highlighting available for yml config. I've added support for enter and undo commands

2024-12-01 11:52 UTC, AlexKarpov98 approved these changes
Works smoothly now.

I'd like to see some syntax highlighting though, like in VS code for example, 
<img width="396" alt="Screenshot 2024-12-01 at 13 52 03" src="https://github.com/user-attachments/assets/ab68e0b0-47e0-49a1-bb3e-b0095785d673">

2024-12-04 00:34 UTC, merged

2024-12-04 00:34 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.