NAS-132607: Adapting to new API
truenas/webui pull request #11143
Opened 2024-12-04 15:50 UTC by undsoft

**Changes:**

Adapts to new API. Major changes in error handling, subscriptions and events.

**Testing**
Regression testing of everything websocket related.

2024-12-04 15:51 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132607

2024-12-05 00:14 UTC, RehanY147 requested changes
ErrorHandlerService seems to have some issue that's not present in master.


https://github.com/user-attachments/assets/60b84bc9-2383-4902-b66f-79db10d0bf15

2024-12-05 12:57 UTC, undsoft commented
@RehanY147 Shape of middleware endpoint has been changed. I will create a separate ticket for it after this PR is merged. 
But I have fixed the error reporting.

2024-12-06 11:13 UTC, RehanY147 approved these changes
The scope of the ticket is large. But after testing for a while, things seem to be working Ok.

2024-12-06 11:18 UTC, merged

2024-12-06 11:18 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.