Update audit page to master-detail view
truenas/webui pull request #11205
Opened 2024-12-18 16:10 UTC by denysbutenko

**Changes:**

- Update audit page to master-detail view
- Split audit component into list and search components.

**Testing:**

Check audit page for regressions.

2024-12-18 16:10 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133031

2024-12-23 23:46 UTC, RehanY147 requested changes
Seeing these errors when I try to interact with the Advanced Search or click on an item in the middle of searching
<img width="901" alt="image" src="https://github.com/user-attachments/assets/b7f8b5cc-1282-4188-b5ee-f136a19ce073" />

2024-12-24 12:07 UTC, denysbutenko commented
> Seeing these errors when I try to interact with the Advanced Search or click on an item in the middle of searching <img alt="image" width="901" src="https://private-user-images.githubusercontent.com/24204846/398275894-b7f8b5cc-1282-4188-b5ee-f136a19ce073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzgzOTMsIm5iZiI6MTczNTAzODA5MywicGF0aCI6Ii8yNDIwNDg0Ni8zOTgyNzU4OTQtYjdmOGI1Y2MtMTI4Mi00MTg4LWI1ZWUtZjEzNmExOWNlMDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDExMDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYWY3YTkyYWUwNDAyYjc1ZGEwYWUyNjgyZjNlYjQyNmFiMjc5MmJhMGYyOTNkZTQ0YjllNjMwMWZjZGRkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rbqAooZe3nsyX7N9OaVtEENMmnnu7EJ6HgHPLU0eJGk">

The first one was fixed. The second is reproducible in main branch, ticket [NAS-133252](https://ixsystems.atlassian.net/browse/NAS-133252).

2024-12-24 23:05 UTC, RehanY147 requested changes
I can still see this error

<img width="784" alt="image" src="https://github.com/user-attachments/assets/adcae808-3766-4bba-bdb1-6fcb91144523" />

2024-12-26 06:48 UTC, denysbutenko commented
> I can still see this error
> 
> <img alt="image" width="784" src="https://private-user-images.githubusercontent.com/24204846/398488022-adcae808-3766-4bba-bdb1-6fcb91144523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTU3NDQsIm5iZiI6MTczNTE5NTQ0NCwicGF0aCI6Ii8yNDIwNDg0Ni8zOTg0ODgwMjItYWRjYWU4MDgtMzc2Ni00YmJhLWJkYjEtNmZjYjkxMTQ0NTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA2NDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NGM4ZmViNzYzMjBmMGU2ODgwZjk5MTI1ZGZiMDQyNDhkMjkxOWU3N2UwNDI2MzY2OTU1ZjA0ODkyMGFiZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P3uAO8SK_IS0uQUkzLEO1aowOZkKkqRwG1hIpfOwLMI">

@RehanY147 there is no `window.getElementsByClassName()` usage in `audit.component.ts`. Did you pull the latest changes? What steps to get this?

2024-12-28 23:06 UTC, RehanY147 approved these changes
I can't reproduce the bug. Although, it did appear after some clicking around the first time too. So, maybe it's an obscure bug. If it pops up again, we can fix it in a separate ticket.

2025-01-02 00:28 UTC, merged

2025-01-02 00:28 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.