Update ko.json
truenas/webui pull request #11220
Opened 2024-12-23 12:43 UTC by jbsamcho

한국어 수정

**Changes:**
korean patched

**Testing:**

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   |

2024-12-23 12:52 UTC, undsoft approved these changes
👍🏼

2024-12-23 12:52 UTC, undsoft commented on src/assets/i18n/ko.json
> +  "CC": "CC": "CC (참조)",
Syntax error on this line.

2024-12-23 14:02 UTC, denysbutenko requested changes
Please resolve merge conflict to proceed. https://github.com/truenas/webui/pull/11214 was merged recently.

2024-12-23 23:52 UTC, RehanY147 commented
Removed the syntax error and resolved conflicts. Will merge. Thanks!

2024-12-24 05:01 UTC, denysbutenko approved these changes

2024-12-24 11:24 UTC, merged