NAS-133155: Non-default account alert does not truncate
truenas/webui pull request #11236
Opened 2024-12-25 09:39 UTC by AlexKarpov98

**Testing:**
See ticket.

Result:

https://github.com/user-attachments/assets/123f4233-67cc-46a3-ac42-5880215e8e5f

### Downstream

|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | Added Expand/Collapse logic to the alert

2024-12-25 09:39 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133155

2024-12-25 14:11 UTC, undsoft requested changes
Looks good, but the button looks a bit intrusive. Let's try to do something about it to either make it less noticeable or try using a link.

2024-12-26 11:24 UTC, AlexKarpov98 commented
@undsoft I like how it looks now, what do you think?
<img width="411" alt="Screenshot 2024-12-26 at 13 23 09" src="https://github.com/user-attachments/assets/c0a6b9c2-aae3-45ef-8bdd-d22b7b7d593f" />

2024-12-26 13:57 UTC, undsoft approved these changes
Let's try with `background: var(--alt-bg1);`.

2024-12-27 13:31 UTC, merged

2024-12-27 13:31 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.