Update src/assets/i18n/es-ar.json
truenas/webui pull request #11255
Opened 2024-12-29 20:18 UTC by castillofrancodamian

2024-12-30 13:26 UTC, undsoft requested changes

2024-12-30 13:26 UTC, undsoft commented on src/assets/i18n/es-ar.json
> +  "{n, plural, one {Failed Disk} other {Failed Disks} }": "{n, plural, one {Failed Disk} other {Failed Disks} }",
So those strings specify how to translate plural words based on your language.
Here `Failed Disk` and `Failed Disks` are translatable.
`{n, plural, one {Failed Disk} other {Failed Disks} }` may become something like `{n, plural, one {Disco averiado} other {Discos averiados} }`

See [TRANSLATING.md](https://github.com/truenas/webui/blob/master/TRANSLATING.md) and [online editor](http://format-message.github.io/icu-message-format-for-translators/editor.html) for help.

2024-12-30 16:33 UTC, AlexKarpov98 reviewed
Follow Evgeny's comments. 👌

2024-12-31 15:13 UTC, undsoft approved these changes
Thanks!

2024-12-31 15:13 UTC, merged