Showing updates to apps
truenas/webui pull request #5180
Opened 2021-02-26 19:10 UTC by AlexKarpov98

2021-02-26 20:52 UTC, sonicaj requested changes
I have following concerns:

1) Not aligned buttons and a scrollbar showing
<img width="1538" alt="Screenshot 2021-02-27 at 1 49 35 AM" src="https://user-images.githubusercontent.com/17968138/109353505-4acc4900-789e-11eb-86cb-60039d09cdfc.png">

2) We should try to have some kind of distinction between text `Update Available` and the newer version ( or if you think perhaps showing version with different font/color/size would be nice, that would be good as well - this does not seem very clear to me especially with multiple apps )
<img width="342" alt="Screenshot 2021-02-27 at 1 50 29 AM" src="https://user-images.githubusercontent.com/17968138/109353588-65062700-789e-11eb-97bb-03cfad2186bf.png">

2021-03-01 17:45 UTC, AlexKarpov98 commented
Updated

2021-03-01 18:02 UTC, sonicaj requested changes
We are now not using `human_version` key to show the human catalog item version. Let's please use that.

2021-03-01 18:46 UTC, kmoore134 commented
Just tested this out, showed upgrades properly, and upgrade worked. Only issue was that the 'upgrade' option was still visible from three-dot menu after the upgrade was done. 

![image](https://user-images.githubusercontent.com/1933088/109543648-8f213a00-7a94-11eb-8d09-db926cf143b6.png)

2021-03-01 20:04 UTC, AlexKarpov98 commented
Updated

2021-03-01 20:37 UTC, sonicaj reviewed
We have rollback button grayed out even if a chart release has history versions which it can rollback to.

<img width="326" alt="Screenshot 2021-03-02 at 1 34 13 AM" src="https://user-images.githubusercontent.com/17968138/109555486-6c743d00-7af7-11eb-98c3-1d8a970c79d7.png">

2021-03-01 20:37 UTC, sonicaj commented
We can check history via
```
midclt call chart.release.query '[["id", "=", "ipfs-test"]]' '{"extra": {"history": true}}'
```

2021-03-02 15:06 UTC, AlexKarpov98 commented
It should solved as middleware is updated accordingly.

2021-03-02 15:26 UTC, sonicaj approved these changes

2021-03-02 16:32 UTC, dszidi commented
Code looks good. Just one small thing. Please add types to the "poolList" and "selectedPool" properties of the CatalogComponent.

2021-03-02 16:59 UTC, AlexKarpov98 commented
Updated

2021-03-02 17:39 UTC, dszidi commented on src/app/pages/applications/chart-releases/chart-releases.component.html
>                ix-auto ix-auto-type="option" ix-auto-identifier="rollback">
ix-auto-identifier should probably equal "update"

2021-03-02 18:12 UTC, dszidi approved these changes
LGTM

2021-03-02 18:14 UTC, merged