Fixed display device issues for VMs
truenas/webui pull request #5347
Opened 2021-04-16 20:33 UTC by ryousaf

NAS-109996

2021-04-16 20:33 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-109996

2021-04-19 09:24 UTC, denysbutenko commented on src/app/pages/vm/vm-list/vm-list.component.ts
> +    extractHostname(url: string) {
what type returns this method?

2021-04-19 09:25 UTC, denysbutenko commented on src/app/pages/vm/vm-list/vm-list.component.ts
> +                            saveButtonText: "Open",
please wrap into `T()` to make it translatable

2021-04-19 09:28 UTC, denysbutenko commented on src/app/pages/vm/devices/device-edit/device-edit.component.ts
> +        {label: 'VNC', value: "VNC"},
labels also should be translatable

2021-04-26 08:48 UTC, denysbutenko commented
There are conflicting files

2021-04-26 08:51 UTC, denysbutenko approved these changes

2021-04-27 23:46 UTC, sonicaj requested changes
Can we please fix NAS-110377 in the same PR perhaps as middleware has updated it's response which means that using the same UI diff will not work now in latest nightlies ?

2021-04-30 10:13 UTC, closed without merging