upon clicking an attribute's tool tip, instead of rendering next to the attribute in question, it renders further down the page
truenas/webui pull request #5455
Opened 2021-05-14 20:19 UTC by AlexKarpov98

2021-05-14 20:19 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110594

2021-05-17 09:35 UTC, RehanY147 requested changes
Weird overlap when switching wizard steps in comparison to `master`. See files for example
![110594](https://user-images.githubusercontent.com/24204846/118467326-8d8d0880-b6b8-11eb-87e6-31389c90238a.gif)
![master](https://user-images.githubusercontent.com/24204846/118467346-9087f900-b6b8-11eb-89c1-e6d517349d3e.gif)

2021-05-17 16:26 UTC, AlexKarpov98 commented
@RehanY147 Fixed.

2021-05-21 20:52 UTC, RehanY147 approved these changes
LGTM. The overlap issue has been resolved

2021-05-24 17:41 UTC, merged