Fixed ACL Manager for NFSv4 type, Added 'acltype' to dataset advanced form options
truenas/webui pull request #5552
Opened 2021-06-08 21:50 UTC by RehanY147

NAS-110951

2021-06-08 21:50 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110951

2021-06-09 08:14 UTC, undsoft requested changes
Doing `zfs set acltype=nfsv4 tank/share` and then opening ACL Manager appears to be working, but I've found additional issues:
- Previously it was possible to create a dataset without explicitly setting up ACL Type. Now user gets a validation error and has to go to Advanced settings.
- Failed to create dataset: 'acltype' must be one of 'off | nfsv4 | posix' when selecting NFS4ACL. Expected?

2021-06-09 09:09 UTC, RehanY147 commented
> 
> 
> Doing `zfs set acltype=nfsv4 tank/share` and then opening ACL Manager appears to be working, but I've found additional issues:
> 
>     * Previously it was possible to create a dataset without explicitly setting up ACL Type. Now user gets a validation error and has to go to Advanced settings.
> 
>     * Failed to create dataset: 'acltype' must be one of 'off | nfsv4 | posix' when selecting NFS4ACL. Expected?

Not sure about the second part. I picked these values from the `pool.dataset.create` api call's docs. They should be working.

2021-06-09 10:34 UTC, anodos325 commented on src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
> +            { label: 'POSIXACL', value: 'POSIXACL' },
NFS4ACL and POSIXACL are old names. They were renamed at some point after initial versions of SCALE and we allowed through for backwards compatibility. Obviously if you're getting errors then that needs to be fixed, but users shouldn't be presented with the options in the GUI.

Requiring explicit acltype seems like a behavior change or regression. Probably related to work on inheritable properties.

2021-06-09 10:35 UTC, undsoft commented on src/app/enums/dataset-acl-type.enum.ts
> +  POSIXAcl = 'POSIXACL',
Previous code style was correct.

2021-06-09 10:35 UTC, undsoft commented on src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
>              { label: 'POSIX', value: 'POSIX' },
{ label: 'POSIX', value: DatasetAclType.Posix }

2021-06-11 09:40 UTC, denysbutenko commented on src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
> +          value: 'INHERIT',
It could be `DatasetAclType.Inherit`

2021-06-11 11:19 UTC, anodos325 commented
Okay, loaded in testing environment. `Dataset Path` in permissions editor is blank. 

Looks like the ACL editor freezes if user selects one of the POSIX ACL templates on the NFSv4 ACL editor. We should probably remove those from the list for now (POSIX_OPEN, POSIX_RESTRICTED) until I alter  `filesystem.default_acl_choices` to optionally take a path (dataset mountpoint in this case) as an argument.

2021-06-11 13:17 UTC, anodos325 commented
Looks like in my tests when filesystem.getacl returns the following, the corresponding named entry (for gid 545) is not populated in the webui:
```
{"acl": [{"tag": "owner@", "id": -1, "perms": {"BASIC": "FULL_CONTROL"}, "flags": {"BASIC": "INHERIT"}, "type": "ALLOW"}, {"tag": "group@", "id": -1, "perms": {"BASIC": "FULL_CONTROL"}, "flags": {"BASIC": "INHERIT"}, "type": "ALLOW"}, {"tag": "everyone@", "id": -1, "perms": {"BASIC": "MODIFY"}, "flags": {"BASIC": "INHERIT"}, "type": "ALLOW"}, {"tag": "GROUP", "id": 545, "perms": {"BASIC": "MODIFY"}, "flags": {"BASIC": "INHERIT"}, "type": "ALLOW"}], "trivial": false, "uid": 666, "gid": 666, "path": "/mnt/dozer/NFS4", "nfs41_flags": {"protected": false, "autoinherit": false}, "acltype": "NFS4"}
```

2021-06-14 11:45 UTC, undsoft commented
Retested again: Path fields are populated, Posix presets are hidden, was able to edit both posix and nfs permissions.
Additional fixes for some inputs in aces going blank is coming in this PR: https://github.com/truenas/webui/pull/5566
Merging this one.

2021-06-14 11:45 UTC, merged