Added 'name_regex' to ReplicationWizard and ReplicationForm
truenas/webui pull request #5587
Opened 2021-06-17 11:58 UTC by RehanY147

NAS-110543

2021-06-17 11:58 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110543

2021-06-18 08:05 UTC, undsoft requested changes
Issues found during testing:
- When I open the form `Naming Schema` input is not visible. I have to toggle radiobuttons back and forth for it to appear.
- If I use Regular Expression, Radio button is not set when I edit replication task.
- Would it be possible to talk to Vladimir and come up with better name for `Naming Schema or Snapshot Name Regular Expression` label. Something like `Filter snapshots`?

2021-06-19 11:09 UTC, AlexKarpov98 requested changes
I see 2 issues when I try to edit existing one.
1) When I open edit form, it only shows one item (`Also Include Naming Schema `).
But once I clicked `Snapshot Name Regular Expression` and back to `Naming Schema`, then `Naming Schema ` appears. (First gif)
2) The radio button is not auto selected correctly for those `Snapshot Name Regular Expression` is set. (Second gif)
![CPT2106191358-1680x853](https://user-images.githubusercontent.com/22980553/122640320-a6e60200-d107-11eb-8dfa-1918fa1d75f7.gif)
![CPT2106191408-1680x792](https://user-images.githubusercontent.com/22980553/122640391-ee6c8e00-d107-11eb-8273-1accb78ca618.gif)

2021-06-20 22:27 UTC, RehanY147 commented
Waiting on feedback from @themylogin. Will likely be able to update on Monday.

2021-07-16 12:51 UTC, closed without merging