No UI option to change the readonly state of a ZVOL
truenas/webui pull request #5593
Opened 2021-06-18 08:56 UTC by AlexKarpov98

2021-06-18 08:56 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110927

2021-06-18 09:37 UTC, denysbutenko commented on src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
> +          { label: 'On', value: 'ON' },
non-translatable labels

2021-06-21 07:21 UTC, undsoft requested changes
The dropdown works correctly, however this PR seems to make another existing issue worse.
When user presses "Edit Zvol", the form is not populated with current values. This also happens on master, but at least on master it works on second attempt for some reason.
Please take a look at this as well.

2021-06-21 20:38 UTC, AlexKarpov98 commented on src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
> +          { label: 'On', value: 'ON' },
Fixed

2021-06-21 20:39 UTC, AlexKarpov98 commented
@undsoft Fixed

2021-06-22 07:12 UTC, undsoft approved these changes
Looks good, thanks!

2021-06-22 16:17 UTC, merged