NAS-111036 / 21.06-BETA.1 / Added defaults for 'aclmode' based on 'acltype' & warning shown
truenas/webui pull request #5594
Opened 2021-06-18 11:25 UTC by RehanY147

NAS-111036

2021-06-18 11:25 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111036

2021-06-21 07:35 UTC, undsoft requested changes

2021-06-21 07:35 UTC, undsoft commented on src/assets/i18n/af.json
> +  "Changes to ACL type affect how on-disk ZFS ACL is  written and read. When the ACL type is changed from POSIX to NFSv4,  no migration is performed for default and access ACLs encoded in the  posix1
Can we add new lines somewhere? It's hard to read one large block of text.

2021-06-21 07:35 UTC, undsoft commented on src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
> +              this.entityForm.setDisabled('aclmode', true, false);
When add form is opened, acltype is `inherit` by default, but `aclmode` is not disabled.

2021-06-22 07:29 UTC, undsoft approved these changes
This may be an intended behaviour, not sure.
I create a dataset with `inherit`. When I then go to edit, it won't say `inherit`, it will instead say whatever the type of the parent was, e.g. `posix`.
Looks good otherwise.

2021-06-22 07:29 UTC, undsoft commented on src/app/helptext/storage/volumes/datasets/dataset-form.ts
> + type changes and permissions modifications.'),
Sorry, can we keep the line break, but remove the empty line at least on the first two.
We need to indicate to the user that there is more text there and that he can scroll.

2021-06-22 07:56 UTC, undsoft commented
Also please retarget towards `master`. We are too far in release process of 21.06 to add it in. It's going to be a known issue there.

2021-06-22 09:03 UTC, RehanY147 commented
> 
> 
> This may be an intended behaviour, not sure.
> I create a dataset with `inherit`. When I then go to edit, it won't say `inherit`, it will instead say whatever the type of the parent was, e.g. `posix`.
> Looks good otherwise.

That is intended behavior. Middleware sets the `INHERIT` value to whatever the parent`s value is.

2021-06-22 09:42 UTC, RehanY147 commented
Too many conflicts with master to change base in this PR. Will be creating a new PR.

2021-06-22 09:42 UTC, closed without merging