Changing base to master, Setting defaults for ACL Type/ACL Modes
truenas/webui pull request #5605
Opened 2021-06-22 09:43 UTC by RehanY147

NAS-111036

2021-06-22 09:43 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111036

2021-06-22 10:56 UTC, undsoft approved these changes
Retested, looks good.

2021-06-22 18:31 UTC, AlexKarpov98 requested changes
I can't change `acl-type` from `posix` to `inherit`.
![edit_acl_inherit](https://user-images.githubusercontent.com/22980553/122980242-19bdda00-d3a1-11eb-8bb2-2ad95b4d1a6f.gif)

2021-06-23 08:55 UTC, RehanY147 commented
> 
> 
> I can't change `acl-type` from `posix` to `inherit`.
> ![edit_acl_inherit](https://user-images.githubusercontent.com/22980553/122980242-19bdda00-d3a1-11eb-8bb2-2ad95b4d1a6f.gif)

That behavior is intended. Once you click save, middleware figures out what the `acltype` is for the dataset's parent and changes it to that for your dataset as well. So, when INHERIT is changed from whatever the parent's `acltype` was (in your case `POSIX`)

2021-06-24 04:32 UTC, undsoft approved these changes

2021-06-24 15:16 UTC, AlexKarpov98 approved these changes

2021-06-26 06:37 UTC, merged