Storage Widget for Dashboard
truenas/webui pull request #5624
Opened 2021-06-25 17:47 UTC by AlexKarpov98

2021-06-25 17:47 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110964

2021-06-26 07:02 UTC, RehanY147 commented
The pool data should be a bit more centered or maybe a bit more left margin as compared to the top and right margins
![image](https://user-images.githubusercontent.com/24204846/123505037-b7b7db80-d611-11eb-80ef-f6d8af6705e6.png)

2021-06-26 07:21 UTC, RehanY147 commented
When you have 3 pools, the icon looks a bit off center for the 4th box "Create a new pool"
![image](https://user-images.githubusercontent.com/24204846/123505528-7bd24580-d614-11eb-862e-075b6417d736.png)

2021-06-26 07:28 UTC, RehanY147 commented
Also, maybe the text should just say "Create Pool" or "New"

2021-06-26 07:44 UTC, RehanY147 requested changes

2021-06-26 07:44 UTC, RehanY147 commented on src/app/core/components/widgets/widgetstorage/widgetstorage.component.ts
> +      pool.topology.data.forEach((item: any) => {
Can we use `VDevStats` here instead of `any`?

2021-06-26 07:44 UTC, RehanY147 commented on src/app/core/components/widgets/widgetstorage/widgetstorage.component.ts
> +          item.children.forEach((device: any) => {
`VDevStats` here as well

2021-06-26 07:44 UTC, RehanY147 commented on src/app/core/components/widgets/widgetstorage/widgetstorage.component.ts
> +      const unhealthy: any[] = []; // Disks with errors
If possible, we should replace this `any` too.

2021-06-28 16:10 UTC, AlexKarpov98 commented
@RehanY147 Fixed.

2021-06-29 09:01 UTC, undsoft requested changes
It works, but would be cooler to get closer to designs. 
Doesn't have to be pixel perfect, but there are some easy to spot differences.
<img width="1132" alt="Снимок экрана 2021-06-29 в 11 54 40" src="https://user-images.githubusercontent.com/1481270/123769017-853c0600-d8d1-11eb-8e9a-0c9db40c8059.png">

[This plugin](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=en) is pretty cool to be able to compare things side by side.

2021-06-29 10:33 UTC, undsoft commented
Also, before I forget, there is a Configure button on Dashboard, which sets which widgets are shown by default. Would be good to show Storage widget by default, but hide individual Pool widgets, so that users can only enable them if needed.

2021-06-29 20:41 UTC, AlexKarpov98 commented
@undsoft Fixed

2021-07-01 09:28 UTC, undsoft approved these changes
It looks pretty good.

Some minor things:
1. I think the name of the pool is intended to be all uppercase. We can make the font a bit smaller.
2. When pool name is too long, let's try to use text-overflow with ....
3. Can we make the color of warning icons more orange. Currently they are somewhat similar to green okay icons.
4. 
<img width="572" alt="Снимок экрана 2021-07-01 в 12 26 57" src="https://user-images.githubusercontent.com/1481270/124101187-c6661e80-da67-11eb-8b72-5707f922d2fe.png">

2021-07-02 20:50 UTC, RehanY147 approved these changes
LGTM

2021-07-06 15:35 UTC, merged