Don't assume REMOVED status will be present
truenas/webui pull request #5630
Opened 2021-06-29 18:02 UTC by dszidi

To test/reproduce:

- Create a pool and add a vdev of type SPARE
- remove one of the none SPARE disks
- Make sure Enclosure UI still displays the pools once resilver has started

2021-06-29 18:02 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111222

2021-06-29 19:19 UTC, RehanY147 requested changes

2021-06-29 19:19 UTC, RehanY147 commented on src/app/core/classes/system-profiler.ts
> +          if (disk.device && disk.status != 'REMOVED') {
The new condition would be true for a modal
`disk.device = true;
disk.status = 'REMOVED'`

The condition isn't exactly matched. With these values, the code would run before in the else block but won't now

2021-06-29 20:04 UTC, RehanY147 approved these changes
LGTM

2021-06-30 14:05 UTC, dszidi commented
@undsoft I posted a video into the ticket comments to demo the problem as well as the fix

https://jira.ixsystems.com/browse/NAS-111222?focusedCommentId=134655&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-134655

2021-06-30 16:11 UTC, darkfiberiru commented
![image](https://user-images.githubusercontent.com/8406051/123995270-255e6180-d99c-11eb-8c11-bb1941a14f61.png)
Fix looks good.

2021-06-30 16:43 UTC, undsoft approved these changes
Approving based on Damian's video.

2021-06-30 16:43 UTC, merged

2021-06-30 16:44 UTC, darkfiberiru reviewed
Lgtm tested and shared screenshot of fixed system after drive pull