Added 'xattr' with different messages/labels for PUSH/PULL
truenas/webui pull request #5654
Opened 2021-07-11 08:23 UTC by RehanY147

NAS-110544

2021-07-11 08:23 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110544

2021-07-12 06:40 UTC, undsoft commented on src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
> +        const xattr_fc = entityForm.fieldConfig.find((config: any) => config.name === 'xattr');
`xattr_fc` => `xattrFc` or even `xAttrControl`

`config` is probably of type `FieldConfig`

2021-07-14 08:53 UTC, undsoft commented
Is this something that was not implemented by middleware? I just get 'Field not expected' when I try to submit form.

2021-07-14 08:53 UTC, undsoft requested changes
Is this something that was not implemented by middleware? I just get 'Field not expected' when I try to submit form.

2021-07-14 10:31 UTC, RehanY147 commented
Yes. Seems like the related middleware ticket is on the back burner for now. Labeling this blocked.

2021-11-23 21:53 UTC, closed without merging