Added new field 'name_regex'
truenas/webui pull request #5669
Opened 2021-07-16 12:55 UTC by RehanY147

NAS-110543

2021-07-16 12:55 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110543

2021-07-19 09:59 UTC, undsoft requested changes
The following comments from previous pull request are still valid:
1. If I use Regular Expression, Radio button is not set when I edit replication task.
2. Would it be possible to talk to Vladimir and come up with better name for Naming Schema or Snapshot Name Regular Expression label. Something like Filter snapshots?

Otherwise seems to be working okay.

2021-07-19 10:25 UTC, RehanY147 commented on src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
> +    const enabled = false;
Alright. Just seemed confusing to me to always remember that `true` means `disabled`. So I made variables.

2021-07-20 13:18 UTC, themylogin commented on src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
> +    const enabled = false;
For push replication:
```
Also include snapshots with the name:
[*] Matching naming schema
[ ] Matching regular expression
```
For pull replication:
```
Also include snapshots with the name:
[*] Matching naming schema
[ ] Matching regular expression
```

2021-07-21 09:06 UTC, undsoft approved these changes
Minor text change from Vladimir, otherwise UI is working correctly.

2021-07-26 12:39 UTC, merged