Add 2 dropdowns
truenas/webui pull request #5676
Opened 2021-07-18 21:16 UTC by RehanY147

NAS-111266

2021-07-18 21:16 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111266

2021-07-20 18:01 UTC, AlexKarpov98 reviewed
@RehanY147 It does not seem to save the new options to middleware correctly.
When you edit the interface having these 2 options, the saved values are not shown on these select controls.

2021-07-27 16:40 UTC, AlexKarpov98 requested changes

2021-07-27 16:40 UTC, AlexKarpov98 commented on src/app/pages/network/forms/interfaces-form.component.ts
> +    this.entityForm.formGroup.get('lag_protocol').valueChanges.pipe(untilDestroyed(this)).subscribe((value: string) => {
@RehanY147 This issue was not fixed yet.
![add_interface](https://user-images.githubusercontent.com/22980553/127193331-5eb4c0d1-81d6-40e7-b9d5-105318fe6072.gif)

2021-07-28 19:49 UTC, RehanY147 commented
@AlexKarpov98 Nice testing. Fixed the issue. Ready for review.

2021-07-29 14:57 UTC, AlexKarpov98 approved these changes
@RehanY147 LGTM

2021-07-29 17:08 UTC, merged