NAS-111466 - View permissions sidebar tests
truenas/webui pull request #5741
Opened 2021-08-07 10:27 UTC by undsoft

2021-08-07 10:28 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111466

2021-08-10 13:20 UTC, RehanY147 requested changes
Getting this error/warning when running `yarn test`. Is this related to this PR?
![image](https://user-images.githubusercontent.com/24204846/128874255-acdbd04a-2715-4d9f-890b-c47824b33ece.png)

2021-08-11 05:39 UTC, undsoft commented
It's entirely possible that my changes introduced the issue. Unfortunately I cannot reproduce the warning, neither with or without the flag.
Tests leaking, while not good, is not too terrible, especially when I can't fix it 🥲

2021-08-12 07:28 UTC, RehanY147 approved these changes
Looks good! All tests pass and the code additions are good too.

2021-08-12 07:30 UTC, merged