Status button should convey warnings to users even if status is success/finished
truenas/webui pull request #5807
Opened 2021-08-22 21:28 UTC by dszidi

2021-08-22 21:28 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111711

2021-08-23 09:02 UTC, undsoft requested changes
Any tips on how I can test this?

2021-08-23 17:25 UTC, dszidi commented
> Any tips on how I can test this?

I've consulted with middleware team and there is unfortunately no easy way to trigger warnings on a completed replication task.

During development I faked it by pushing some strings to the warnings array of the API response.

![image](https://user-images.githubusercontent.com/29865743/130490447-5e5da4d5-dedf-4f04-82ed-f7ea37849fc7.png)

2021-08-30 08:54 UTC, undsoft approved these changes
Appears to be working correctly, assuming that warnings will come as an array of strings.

2021-08-30 11:56 UTC, merged