NAS-112138: Remove services_restart attribute
truenas/webui pull request #5853
Opened 2021-09-02 19:26 UTC by denysbutenko

In additions to #5848: Update related interface

2021-09-02 19:26 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-112138

2021-09-06 08:18 UTC, undsoft requested changes
What about: 
src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts:412
src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts:371
?

2021-09-06 10:06 UTC, denysbutenko commented
> What about:
> src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts:412
> src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts:371
> ?

These related to `pool.unlock` endpoint, the ticket was for `pool.dataset.unlock`. However, `pool.unlock` endpoint is not listed on `api/docs`. I'll check if it's necessary to remove

2021-09-08 07:59 UTC, undsoft approved these changes
Looks good.

2021-09-08 08:12 UTC, merged