NAS-110081 / 22.02-RC.2 / Sentry integration - Errors should be logged at sentry.ixsystems.com automatically
truenas/webui pull request #5994
Opened 2021-10-11 10:18 UTC by RehanY147

NAS-110081

2021-10-11 10:18 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110081

2021-11-16 10:15 UTC, undsoft requested changes
We also need to honour the `Crash Reporting` setting in GUI Settings.

2021-11-16 10:15 UTC, undsoft commented on src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> +    this.ws.call('pool.dataset.query_encrypted_roots_keys').pipe(untilDestroyed(this)).subscribe((res: any) => {
Rogue `any`.

2021-11-16 10:15 UTC, undsoft commented on src/app/app.module.ts
> +      deps: [Sentry.TraceService],
To check if initializer is actually needed.

2021-11-16 10:15 UTC, undsoft commented on src/app/views/sessions/signin/signin.component.ts
> +    if (!environment.production) {
Best to find a way to enable this for nightly builds only.
If too hard, just switch the statement here.

2021-11-20 22:21 UTC, RehanY147 commented
Creating a new PR to avoid merge conflicts

2021-11-20 22:21 UTC, closed without merging