Update R50 rear chassis image (IO plate)
truenas/webui pull request #6109
Opened 2021-11-10 14:53 UTC by dszidi

The image for the rear of the R50 chassis needed to be updated to show the correct IO plate.
This is a purely cosmetic change.

Please refer to JIRA ticket linked below to see what the new UI plate looks like.

https://jira.ixsystems.com/browse/NAS-113101

2021-11-10 14:53 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113101

2021-11-10 16:57 UTC, dszidi commented
The new IO plate is only supposed to apply for rev B models. This branch currently applies the image to all R50 models.

2021-11-11 07:37 UTC, undsoft requested changes
rev B only

2021-11-12 08:35 UTC, undsoft approved these changes
Looks good.

2021-11-12 08:35 UTC, merged