NAS-113125 / 22.02-RC.2 / Should we display WAITING jobs in Task manager
truenas/webui pull request #6111
Opened 2021-11-10 17:32 UTC by AlexKarpov98

2021-11-10 17:32 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113125

2021-11-11 14:24 UTC, denysbutenko requested changes
Waiting for a green checkmark on tests

2021-11-12 14:08 UTC, denysbutenko approved these changes
I wondering if we need to replace the `Pending` state with `Waiting` in other places. Seems like there is no `Pending` state on the middleware side.
Otherwise looks good 👍🏻

2021-11-12 16:38 UTC, AlexKarpov98 commented
> I wondering if we need to replace the `Pending` state with `Waiting` in other places. Seems like there is no `Pending` state on the middleware side. Otherwise looks good 👍🏻

So this change was only happend on jobs and we don't have any other places using this.

2021-11-12 16:38 UTC, merged