NAS-113319: Enabling strict templates
truenas/webui pull request #6116
Opened 2021-11-12 13:02 UTC by undsoft

Enables basic level of strict templates in tsconfig.json.
Removes some unused components.

Testing: quick regression testing paying attention to scheduler form control (for example in data protection tasks schedule).

2021-11-12 13:02 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113319

2021-11-12 16:09 UTC, AlexKarpov98 requested changes
Looks good, just seeing test failure.

2021-11-14 11:09 UTC, undsoft commented
Fixed.

2021-11-15 07:57 UTC, AlexKarpov98 approved these changes

2021-11-15 09:15 UTC, merged