NAS-113575 - Refactoring NFS service form
truenas/webui pull request #6210
Opened 2021-12-17 13:02 UTC by undsoft

Testing: Settings -> Services -> Edit NFS.
If you want to get something to show up in bind IPs dropdown, you need to go to Network, open your interface and add a static IP address to it. Static IP has to be added on the interface, not not in Static Routes.

2021-12-17 13:02 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113575

2021-12-20 08:42 UTC, RehanY147 requested changes
The validation for the port fields isn't applied. Entering alphabets gives no error, forms submits successfully. Invalid values not saved (correctly) when you open the form again.

Furthermore, I feel like there should be some indication of an empty value in the drop down if no value is available. Otherwise, it looks like it's stuck and not working properly. An empty state or a null value maybe?

2021-12-20 08:45 UTC, RehanY147 commented
Here's a video of the issue
![nfs form refactor](https://user-images.githubusercontent.com/24204846/146738440-022a3f32-ab6c-4ced-8491-fe1a11e2fb11.gif)

2021-12-20 11:46 UTC, undsoft commented
I've partially fixed it. Chrome will now show a range error in this case. Unfortunately I cannot fix the issue in Firefox easily, it has to do with how Firefox works with numeric inputs. I've created a separate ticket to address this: https://jira.ixsystems.com/browse/NAS-113903

2021-12-21 10:25 UTC, merged