NAS-113867: Unit tests should not be making real network requests
truenas/webui pull request #6212
Opened 2021-12-17 15:22 UTC by bvasilenko

Several tests were crashing when `environment.remote` was reachable via network
For example at localization-form.component.spec.ts

2021-12-17 15:22 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113867

2021-12-20 12:20 UTC, undsoft requested changes
1. It works, but I would prefer to take a different approach - not using a base class. I feel like it makes system's code more complicated only to accommodate tests.
I would rather either take an approach that was used before in MockWebsocketService:
```
this.call = jest.fn();
this.job = jest.fn();
```
or just redefine `send` in MockWebsocketService.

2. I'm a bit confused as to why it helped. I don't see any new error message in console. Does it mean that there is now some code in localization form that still tries to make network request, gets an Error and catches it?

2021-12-20 13:57 UTC, bvasilenko commented
@undsoft 

> 1. I would prefer to take a different approach - not using a base class. I feel like it makes system's code more complicated only to accommodate tests.

Agree. Let me do it the other way, we'll see which one is better.

> 2. I'm a bit confused as to why it helped. I don't see any new error message in console. Does it mean that there is now some code in localization form that still tries to make network request, gets an Error and catches it?

Steps which cause the issue:
   1.  `new MockWebsocketService` (called by dependency injector)
   2.  `MockWebsocketService.constructor` -> `WebSocketService.constructor` ->  `this.connect();` -> `rxjs` emits, etc (side effects) -> broken test `localization-form.component.spec.ts` 


```
constructor(protected router: Router) {
    this.authStatus$ = new Subject<boolean>();
    this.onOpenSubject$ = new Subject();
    this.onCloseSubject$ = new Subject();
    this.pendingCalls = new Map();
    this.protocol = window.location.protocol;
    this.remote = environment.remote;
    this.connect();     // <== here's the beginning of the story
  }
```

2021-12-20 16:27 UTC, undsoft approved these changes
All tests pass.

2021-12-20 16:32 UTC, merged