Make single SLOG device warning less scary for commercial users
truenas/webui pull request #6217
Opened 2021-12-20 17:30 UTC by AlexKarpov98

2021-12-20 17:31 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113728

2021-12-22 13:00 UTC, undsoft requested changes
1. See image. Two errors in the background. One error in dialog.
2. Not a new issue, but it's also possible to get a dialog which would show no errors, but ask to overwrite them. To do this, I just immediately added one log vdev upon navigating to this page and then pressed Force.

2021-12-22 17:04 UTC, undsoft requested changes
Eh, I don't really want a permanent "This layout is not recommended due to errors". What I want is the list of errors/warnings that were shown on the page to be shown in the dialog.
For example in this case:

<img width="1113" alt="Снимок экрана 2021-12-22 в 19 03 12" src="https://user-images.githubusercontent.com/1481270/147129091-76250f21-1c1a-49fa-a897-a3caf75b1ea0.png">

2021-12-22 20:08 UTC, dszidi commented on src/app/helptext/storage/volumes/manager/manager.ts
> +  manager_logVdevWarningMessage: T('Caution: a stripe log vdev layout can lose data in the unlikely event of simultaneous vdev failure and total power failure.'),
The letter A should be capitalized eg. "Caution: A stripe log..."

2021-12-23 13:52 UTC, dszidi approved these changes
LGTM

![image](https://user-images.githubusercontent.com/29865743/147249765-7d2521c8-926b-45fb-bdaf-3d9dfd4cc332.png)

2021-12-24 13:07 UTC, undsoft requested changes
Issues found:
1. "Caution: A stripe data vdev is highly discouraged and will result in data loss if it fails" is no longer red for some reason.
2. Errors seem to be sticky? I.e. if I set layout to give me a "stripe log vdev" error, but then undo changes, the error still stays. See video:

https://user-images.githubusercontent.com/1481270/147354883-30e35f29-dc7f-410a-8013-cee835552c4f.mov

2022-01-05 12:24 UTC, undsoft approved these changes
Looks good now, thanks.

2022-01-05 12:24 UTC, merged