Added the new field
truenas/webui pull request #6253
Opened 2022-01-04 15:07 UTC by RehanY147

2022-01-04 15:07 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114028

2022-01-05 11:44 UTC, undsoft requested changes
Looks like I no longer can submit form with empty Certificate.

2022-01-05 11:44 UTC, undsoft commented on src/app/pages/services/components/service-s3/service-s3.component.html
> +          *ngIf="form.controls['certificate'].value !== null"
Let's move *ngIf as a first line within ix-input.

2022-01-09 10:26 UTC, RehanY147 commented
Should we working now 
![certificate issue](https://user-images.githubusercontent.com/24204846/148678386-40245a01-a3f7-4c43-973c-fa14aacaa174.gif)

2022-01-09 13:17 UTC, undsoft approved these changes
Works well now.

2022-01-09 13:17 UTC, undsoft commented on src/app/pages/services/components/service-s3/service-s3.component.html
> +          [label]="'TLS Server Uri' | translate"
Let's also add [required]="true"

2022-01-11 13:54 UTC, merged