Translation pl patch 1
truenas/webui pull request #6256
Opened 2022-01-05 13:42 UTC by Rudzik99

Translated some sentences with the word "pool" and a few others.

2022-01-06 17:38 UTC, AlexKarpov98 requested changes
Thanks! LGTM

2022-01-06 17:38 UTC, AlexKarpov98 commented on src/assets/i18n/pl.json
> +  "<b>Boot Pool Condition:</b> {condition}": "<b>Kondycja woluminu Boot:</b> {condition}",
<b>Kondycja puli Boot:</b> {condition}

2022-01-06 17:38 UTC, AlexKarpov98 commented on src/assets/i18n/pl.json
> +  "Export/disconnect pool: '": "Eksportuj/Odłącz pulę: '",
I think `Odłącz` is not proper to `Disconnect`. how about `Eksportuj/Rozłącz`?

2022-01-06 17:38 UTC, AlexKarpov98 commented on src/assets/i18n/pl.json
> +  "Retrieving catalog": "Pobieranie katalogu",
`Pobieranie` looks not good for me.

2022-01-06 17:38 UTC, AlexKarpov98 commented on src/assets/i18n/pl.json
> +  "Rolling back...": "Wycofywanie...",
Rollback -> Wycofaj

2022-04-05 18:38 UTC, undsoft commented
@AlexKarpov98 Need to do something with this PR. Either retarget and fix it yourself, or close it.

2022-04-06 04:58 UTC, AlexKarpov98 approved these changes
LGTM!

2022-04-06 05:51 UTC, merged

2022-04-06 10:02 UTC, undsoft commented
@AlexKarpov98 
PR was targeted to `master-old` (now stable/angelfish). Need to backport changes now.