NAS-114084: Fix ZFS metadata corruption - Pool state green in dashboard
truenas/webui pull request #6281
Opened 2022-01-11 18:53 UTC by bvasilenko

Fixed 2 bugs:
1. `healthy: false` on a pool object was ignored in Pool widget on Dashboard
2. translated wordings were used instead of CSS class names in Chinese and several other translations

Testing: 
You need to a pool which is have "unhealthy" and "online"
I've temporary patched [this line](https://github.com/truenas/webui/blob/bb2e7855a5b5a25065c6659c00ea5a8e79d79a24/src/app/pages/dashboard/components/dashboard/dashboard.component.ts#L540) with `data.healthy = false`. This is exact condition which leads to the depicted "ONLINE (Unhealthy)" status wording at /storage (see below)

![image](https://user-images.githubusercontent.com/20611516/149003278-2681e794-c06b-4463-8e15-4ed7b68d94ee.png)

Now when you visit /dashboard:

![image](https://user-images.githubusercontent.com/20611516/149003319-24db5732-5b73-4950-ba99-2e1cdad6a1fa.png)

![image](https://user-images.githubusercontent.com/20611516/149003487-980259aa-3d41-4b84-b44a-7955078ea16c.png)

2022-01-11 18:53 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114084

2022-01-12 11:35 UTC, undsoft requested changes
I've used http://manpages.ubuntu.com/manpages/bionic/man8/zinject.8.html to simulate a degraded vdev and it resulted in mis-aligned icon: 
<img width="760" alt="Снимок экрана 2022-01-12 в 13 20 50" src="https://user-images.githubusercontent.com/1481270/149131186-da1bfa73-e787-407a-9118-53a36d206fe3.png">

2022-01-12 14:56 UTC, bvasilenko commented on src/app/pages/dashboard/components/widget-pool/widget-pool.component.ts
> +      this.poolHealth.errors.push('Pool status is ' + poolState.status);
actually these aren't used, so I removed them

2022-01-13 11:50 UTC, undsoft approved these changes
Confirmed with mock data from https://jira.ixsystems.com/browse/NAS-113238
<img width="760" alt="Снимок экрана 2022-01-13 в 13 49 30" src="https://user-images.githubusercontent.com/1481270/149325289-1e9e764e-01ee-4e1e-bb2f-daec5b3533b8.png">

2022-01-13 12:34 UTC, merged