Removed welcome dialog and added "Help" widget on dashboard
truenas/webui pull request #6308
Opened 2022-01-18 08:37 UTC by RehanY147

To test
- Make sure that the help widget shows up by default on the dashboard page
- Make sure that it's configurable and hides when unchecked on the Dashboard Configure form
- Check responsive on phone screens

2022-01-18 08:37 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-112741

2022-01-18 13:17 UTC, AlexKarpov98 commented on src/app/pages/dashboard/components/widget-help/widget-help.component.ts
> +  turnOffWelcomeDialog(): void {
Good work!
Image in ticket
![image](https://user-images.githubusercontent.com/22980553/149943913-57a5e676-c8d6-4f51-836b-2c9e38ea8f7a.png)

Web UI
![Screenshot_7](https://user-images.githubusercontent.com/22980553/149943569-16f0cdb8-6e99-4530-b4cd-1d5d48138a7e.png)

![Screenshot_8](https://user-images.githubusercontent.com/22980553/149943603-de7f16c8-0ac9-4a9e-be42-0a75550f918d.png)

There is some difference in UI. Not sure to add a logo like the Welcome dialog.
Missing unit testing.
Please remove all prev codes of the Welcome dialog.

2022-01-18 13:18 UTC, AlexKarpov98 requested changes
Good work!
Image in ticket
![image](https://user-images.githubusercontent.com/22980553/149943913-57a5e676-c8d6-4f51-836b-2c9e38ea8f7a.png)

Web UI
![Screenshot_7](https://user-images.githubusercontent.com/22980553/149943569-16f0cdb8-6e99-4530-b4cd-1d5d48138a7e.png)

![Screenshot_8](https://user-images.githubusercontent.com/22980553/149943603-de7f16c8-0ac9-4a9e-be42-0a75550f918d.png)

There is some difference in UI. Not sure to add a logo like the Welcome dialog.
Missing unit testing.
Please remove all prev codes of the Welcome dialog.

2022-01-20 12:08 UTC, RehanY147 commented
@AlexKarpov98 All of the content on this widget is static except for the product type. Nothing to test. No actions can be performed except link clicks. Also, the ticket suggests that instead of having a form there to subscribe to the newsletter we can just redirect the user to the page on the website for subscription.
Extra code removed. Thanks for pointing that out!

2022-01-20 18:42 UTC, undsoft approved these changes
Looks good to me too. Maybe in the future we should consider having a faster way to remove the widget from dashboard.

2022-01-20 21:23 UTC, merged

2022-01-31 17:31 UTC, undsoft commented
backport