NAS-114214: Deleting a dataset causes the deletion of a replication task
truenas/webui pull request #6309
Opened 2022-01-18 13:12 UTC by bvasilenko

Testing:
1. Storage -> Create 2 Datasets
2. Create ZVol inside each dataset
3. Data Protection -> Replication task ZVol -> ZVol2. You may also try ZVol -> Dataset, etc.
4. Storage -> Delete ZVol2
Expected result: confirmation dialog will have a list of related replication tasks, which will be deleted automatically

2022-01-18 13:13 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114214

2022-01-20 10:40 UTC, RehanY147 requested changes
The warning shows up if I try to delete the source dataset of the replication task. But deleting the destination dataset/zvol of the replication task shows no warning about replication task. Not sure if that's intended.

2022-01-20 10:40 UTC, RehanY147 commented on src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts
> +    let res = '';
Here too

2022-01-20 10:40 UTC, RehanY147 commented on src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts
> +    const flattenAttachment = (obj: PoolAttachment): string => obj.attachments.map((a) => a.split(',').map((i) => `<br> - ${i}`).join()).join();
We should break down this code into multiple properly named variable assignments on multiple lines so its more readable and understandable what's happening.

2022-01-24 08:12 UTC, bvasilenko commented
>Not sure if that's intended. 
To me that seems to be by design. Because if the destination Dataset/ZVol does not exists, it will be created automatically.

2022-01-25 07:45 UTC, RehanY147 approved these changes
Looks good to me

2022-01-27 06:45 UTC, merged