NAS-114411: Refactor network configuration into a separate component
truenas/webui pull request #6321
Opened 2022-01-20 18:24 UTC by undsoft

Testing: go to Network and compare Global Configuration widget on multiple machines.

2022-01-20 18:24 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114411

2022-01-21 16:17 UTC, AlexKarpov98 commented on src/app/pages/network/network-configuration-card/network-configuration-card.component.scss
> +.mat-toolbar-row {
Cards' height is not arranged when loading config and after loaded as before.
![Screenshot_17](https://user-images.githubusercontent.com/22980553/150561571-79d143e2-ba20-4f0b-8ac9-9a0d7d7a66d2.png)

Please try to add following style or something:
```
:host {
  display: block;
  flex: 1 1 1e-9px;

  .mat-card {
    height: calc(100% - 8px);
    max-width: 100%;
  }
}
```

2022-01-21 16:18 UTC, AlexKarpov98 requested changes
LGTM! 👍

2022-01-21 16:42 UTC, undsoft commented
Fixed.

2022-01-24 05:09 UTC, AlexKarpov98 approved these changes

2022-01-24 08:39 UTC, merged