Better implementation of IxUserCombobox
truenas/webui pull request #6328
Opened 2022-01-21 14:46 UTC by RehanY147

Go to Credentials -> Groups -> Add and observe the bottom two fields. Which now both use the same component to implement the combobox. Also check out the code.

2022-01-21 14:46 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-112767

2022-01-24 09:44 UTC, undsoft requested changes
General architecture looks good, had some issues when using comboboxes:
1. First combobox has 2.5 second delay every time I type in a letter.
2. There seems to be a large delay or a change detection issue between typing something and seeing dropdown values.
3. Sometimes I see an infinite scrolling bar, for example when I open normal checkbox and scroll down.

2022-01-24 09:44 UTC, undsoft commented on src/app/pages/common/ix-forms/classes/user-combobox-provider.ts
> +  private ProviderUpdater$ = new Subject();
bad case

2022-01-24 09:44 UTC, undsoft commented on src/app/pages/common/ix-forms/classes/user-combobox-provider.ts
> +  isLoading = false;
should be private

2022-01-24 09:44 UTC, undsoft commented on src/app/pages/common/ix-forms/classes/user-combobox-provider.ts
> +  get providerUpdater$(): Subject<any> {
Here and in definition this is probably a Subject<void>

2022-01-24 09:44 UTC, undsoft commented on src/app/pages/account/groups/group-form/group-form.component.ts
> +    this.userProvider.providerUpdater$.pipe(untilDestroyed(this)).subscribe(() => {
I'm struggling to understand the point of this. Is this to make change detection work? If so, then `ix-combobox2` should be responsible for rerunning change detection after new options have been received from the provider.

2022-01-24 09:44 UTC, undsoft commented on src/app/pages/account/groups/group-form/group-form.component.ts
> +      this.normalProvider = _.cloneDeep(this.normalProvider);
Why clone?

2022-01-24 09:44 UTC, undsoft commented on src/app/pages/account/groups/group-form/group-form.component.ts
> +
It's nice to see an example of a more advanced provider with static values. I would also like to see an example of simplified version for developer use, something like:
```
normalProvider = new ArrayProvider([
       { label: UUID.UUID().substring(0, 6), value: UUID.UUID() },
       { label: UUID.UUID().substring(0, 6), value: UUID.UUID() },
       { label: UUID.UUID().substring(0, 6), value: UUID.UUID() },
]);

```

2022-01-24 09:44 UTC, undsoft commented on src/app/pages/common/ix-forms/components/ix-combobox2/ix-combobox2-provider.interface.ts
> +  pageOffset: number;
I am not sure that we need `pageOffset` in this interface. Seems like this should be something for provider to figure out internally.

2022-01-25 09:49 UTC, undsoft requested changes
Works much better.
I think we should also consider having some indication that search is happening or about to happen. Maybe loading indicator should instead appear within the input box (like a spinner on the right or a very thin line) and appear immediately as I type.
Right now because of debounce and probably because of network request there is a noticeable delay between me typing something and seeing results.
If I was a user who didn't know that this UI control performs a search, I may give up sooner than I see suggestions.

2022-01-25 09:49 UTC, undsoft commented on src/app/pages/common/ix-forms/classes/user-combobox-provider.ts
> +  private ProviderUpdater$ = new Subject<void>();
The case is still incorrect.

2022-01-25 09:49 UTC, undsoft commented on src/app/pages/account/groups/group-form/group-form.component.ts
> +
Still would like to see this example.

2022-01-25 09:49 UTC, undsoft commented on src/app/pages/common/ix-forms/components/ix-combobox2/ix-combobox2-provider.interface.ts
> +  options: Option[];
How about not having `providerUpdater$` and instead just have `options$` be a stream?

2022-01-27 13:47 UTC, RehanY147 commented
Going a different route for now.

2022-01-27 13:47 UTC, closed without merging