webUI network interface icons not working
truenas/webui pull request #6392
Opened 2022-02-08 18:50 UTC by AlexKarpov98

Removed states icons completely.

2022-02-08 18:51 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114597

2022-02-09 14:38 UTC, undsoft requested changes
I am not convinced we should remove this completely.
1. We still have something very similar on the dashboard.
2. As a user there is value in seeing what network interfaces are connected.

How about either making it more reliable and fixing the underlying undefined issue or finding if we can change this indicator to only show whether interface is connected, but leave out bytes sent/received.

2022-02-21 08:26 UTC, AlexKarpov98 commented
Updated:
- Hide tooltip when `sent` or `received` is undefined.
- Update link_status of the interface from interfaces value of the subscription `reporting.realtime`

2022-02-21 13:06 UTC, undsoft requested changes
1. It looks like at least for machines from here https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20(Full%20-%20Nightly%20ISO)/ the indication is wrong on Network page. NIC is shown as disconnected, which is not true.
2. When I then switch from Network page to Dashboard, arrows won't show anything. If I reload the page, they will work.

https://user-images.githubusercontent.com/1481270/154961070-7a5cbef6-554a-4021-a547-0d9d7e53bc84.mov

2022-02-21 13:06 UTC, undsoft commented on src/app/pages/dashboard/components/widget-network/widget-network.component.ts
> +    return null;
Usually successful scenario is the last one.

2022-03-03 15:08 UTC, undsoft approved these changes
Tested basic configurations on 4 machines. They seem to work fine.

2022-03-03 17:35 UTC, merged