NAS-110284: Added upload progress
truenas/webui pull request #6398
Opened 2022-02-09 21:15 UTC by RehanY147

Go to the Update page and choose to update a manual file to update TrueNAS. During the upload, you should be able to see the upload progress and afterwards, the update process should go smoothly.

2022-02-09 21:16 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110284

2022-02-10 10:49 UTC, undsoft requested changes
What is the way to test this? I'm just getting Unauthorized error when I submit the form.

2022-02-10 11:28 UTC, RehanY147 commented on src/app/modules/entity/entity-job/entity-job.component.ts
> +      });
That's what did before, but I thought a lot of the code was redundant. Let me try to rework it.

2022-02-10 12:01 UTC, RehanY147 commented
Not sure about the auth error. I haven't had that issue. Pick an upload file and click submit after selecting a dataset basically. The upload process should start with progress.

2022-02-10 14:10 UTC, merged