NAS-114608 / None / Refactor TwoFactorComponent to ix-forms
truenas/webui pull request #6404
Opened 2022-02-10 20:25 UTC by AlexKarpov98

Testing:

Credentials -> 2FA

2022-02-10 20:25 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114608

2022-02-11 09:25 UTC, undsoft requested changes
1. I'm thinking we should rearrange the form a little bit. For most users the workflow is to click Enable and scan the code. The rest of the form is advanced settings really.
Let's move status text ("Two-factor authentication is NOT enabled."), Enable Two-Factor Authentication button and Show QR to be above the form. 
We should also remove the primary color from Save (since it's not a primary action) and give it to Enable/Disable button.
2. I think we should always show the QR code after Enable button is pressed.

2022-02-11 09:25 UTC, undsoft commented on src/app/pages/system/two-factor/two-factor.component.html
> +            {{helptext.two_factor.message}}
Need `| translate` here and in tooltips and labels below.

2022-02-18 19:31 UTC, AlexKarpov98 commented
Rearranged the form:
![Screenshot_18](https://user-images.githubusercontent.com/22980553/154748315-2b1aefa5-4dcc-40d9-aa65-09ab51b53b79.png)

Read-only input behaviors:
- Shallow background style
- Select all when focus
- Copy cursor
![Screenshot_19](https://user-images.githubusercontent.com/22980553/154748852-520b5d91-5ce4-47c3-8c9f-c0d22328d59a.png)

Added tooltip to Title:
![Screenshot_20](https://user-images.githubusercontent.com/22980553/154748933-138a452d-a6bf-47be-bad0-ee4c584e884d.png)

2022-02-18 19:58 UTC, AlexKarpov98 commented
@undsoft I need help with:
Current there are 3 skipped failed tests in [two-factor.component.spec.ts](https://github.com/truenas/webui/blob/0257ee95d482b1cb9f558926ad44690485e8bc37/src/app/pages/system/two-factor/two-factor.component.spec.ts)
![image](https://user-images.githubusercontent.com/22980553/154751394-b0cc3146-e9b9-4485-9307-422fba551300.png)
I have a problem expecting calling after dialog confirmation in the test.
Let me know how to get it sorted. Thank you!

2022-02-21 11:28 UTC, undsoft approved these changes
Nice work! Functionality works well, will message you about tests in Slack.

2022-02-25 12:24 UTC, undsoft commented
Basically, the problem (at least in some tests) is that `this.dialogService.confirm` is not set to return anything in `mockProvider`.
It should be something like this:
```
mockProvider(DialogService, {
  confirm: jest.fn(() => of()),
}),
```

As for `disable 2FA when click `Disable Two-Factor Authentication` button` case, you need to set up necessary pre-conditions for `Disable Two-Factor Authentication` button to appear.
I think it would be okay to do something like:
```
spectator.inject(MockWebsocketService).mockCallOnce('auth.twofactor.config', ...config to make button appear);
spectator.component.ngOnInit();
```

2022-02-27 21:16 UTC, merged