Added buttons around icons to make them interactable
truenas/webui pull request #6411
Opened 2022-02-14 10:10 UTC by RehanY147

Added transparent `<button>` around mat-icons as per the recommendations here https://material.angular.io/components/icon/overview

Check the snapshots page and use it with a screen reader (NVDA) or just use the system with a keyboard. The icons should be intractable.

2022-02-14 10:11 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-109881

2022-02-14 15:40 UTC, denysbutenko commented
From first view it looks good. These changes affected each `entity-table` not only `snapshot-list`. Even if refactored `snapshot-list` don't use `entity-table-actions` component it has value for other pages. I'll test it in details a bit later.
Thanks for pointing out snapshots-related code in `entity-table`. I'll remove it in PR #6384.

`ix-expand-column` [component](https://github.com/truenas/webui/blob/master/src/app/pages/common/ix-tables/components/ix-expand-toggle-column/ix-expand-toggle-column.component.html) is not affected

cc @undsoft

2022-02-15 09:18 UTC, denysbutenko requested changes
It works using a keyboard. Something weird happens when I click on the three dots button. It doesn't open the menu, but sometimes it appears if I click multiple times.

https://user-images.githubusercontent.com/351613/154030561-c6607ae2-0f2d-48fa-bcbc-aba7181e315f.mp4

For column toggling, it works for a single column only. `Reset to defaults` and `Unselect All` and `Select All` don't anything

https://user-images.githubusercontent.com/351613/154030842-f2f6ea75-c951-4c06-9250-11ef96e05d39.mp4

2022-02-15 11:16 UTC, RehanY147 commented
Nice catch @denysbutenko! Fixes added.

2022-02-15 11:38 UTC, denysbutenko commented
@RehanY147  the build is failed and new image is not available for testing

2022-02-15 13:35 UTC, RehanY147 commented
@denysbutenko fixed now.

2022-02-15 16:03 UTC, denysbutenko commented on src/app/modules/entity/entity-table/entity-table-actions/entity-table-actions.component.html
> +      [attr.aria-label]="translateLabels('Actionable Options')"
why use the `translateLabels` method instead of translate pipe?

2022-02-16 04:06 UTC, denysbutenko approved these changes
Looks good!

2022-02-16 07:33 UTC, merged