NAS-113464 / None / Added ix-table-extended
truenas/webui pull request #6420
Opened 2022-02-16 10:42 UTC by RehanY147

The `ix-table-extended` approach needs to be reviewed. Plus typical code review. The NTP Servers List under General Settings is used as an example.

2022-02-16 10:42 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113464

2022-02-17 16:01 UTC, denysbutenko approved these changes
Looks good to me. Perhaps it can replace `app-table` on the Sharing and Data Protection pages

2022-02-17 21:50 UTC, AlexKarpov98 commented on src/app/modules/ix-tables/components/ix-table-extended/ix-table-extended.component.ts
> +        break;
May remove break lines.

2022-02-17 21:56 UTC, AlexKarpov98 approved these changes
LGTM! 👍
![Screenshot_15](https://user-images.githubusercontent.com/22980553/154577262-a04bd5b4-014d-4e17-b7a4-7b6a68f0a0af.png)
![Screenshot_16](https://user-images.githubusercontent.com/22980553/154577274-267db298-eee5-4def-885f-f5faada45509.png)

2022-02-18 11:49 UTC, undsoft requested changes
I cannot say that I like the approach. 
One of the major design goals with entity-table was to have a set of components that can be connected together to build the table. As in not do what entity-table was doing by wrapping logic inside of component. This goes back on this goal.
For example, I don't see why title or buttons should be part of the `table` component.
The table tag is now hidden from a developer.

What I really wanted by this ticket is to reduce boilerplate by taking all of these emptyConf, loadingConf, errorConf and extracting that part in a way that can be connected to ix-table.

2022-02-23 21:49 UTC, closed without merging