NAS-114383: enclosure plugin rewritten on 13 needs webUI changes
truenas/webui pull request #6427
Opened 2022-02-18 10:14 UTC by bvasilenko

Summary: adapted response of `EnclosureData` to existing UI logic.

Testing:

To see **System -> View Enclosures**:
1. edit src/app/services/navigation/navigation.service.ts
   ![image](https://user-images.githubusercontent.com/20611516/154661347-c34db97d-d6a7-469b-a56a-6d557ebf83a6.png)

2. edit src/app/pages/system/viewenclosure/view-enclosure.component.ts:
   ![image](https://user-images.githubusercontent.com/20611516/154661525-5d7f1de4-f544-4530-a584-e5085a8b585b.png)

3. remove condition at src\\app\\pages\\system\\viewenclosure\\view-enclosure.component.html:2
   ![image](https://user-images.githubusercontent.com/20611516/154661601-26e4ac92-326c-41da-94eb-3b861fb05a1f.png)

   
To see contents of **View Enclosures**:
1. Download new JSON response for  `EnclosureData` query from attachments of the ticket https://jira.ixsystems.com/browse/NAS-114383
2. Extract responses  `PoolData`, `SensorData` and `DisksData` queres from the machine mentioned in the ticket https://jira.ixsystems.com/browse/NAS-114383
3. Paste JSON to src/app/pages/system/viewenclosure/view-enclosure.component.ts  
   ![image](https://user-images.githubusercontent.com/20611516/154662705-792a314f-e8b4-4fc0-8065-4036f1ab1ea0.png)

2022-02-18 10:14 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114383

2022-02-18 11:51 UTC, undsoft commented
@bvasilenko Isn't there a real machine that can be used for testing?

2022-02-18 14:06 UTC, bvasilenko commented
There is a machine mentioned in the ticket.
> from the machine mentioned in the ticket https://jira.ixsystems.com/browse/NAS-114383

2022-02-20 20:45 UTC, RehanY147 requested changes
The changes work but I can't see the difference between the normal system or post changes. What is the problem behavior that we're trying to fix? And how? @bvasilenko Please provider screenshots. Could I simply test this on the machine mentioned on the ticket? Or do I need to do all of the steps described above to test it?

2022-02-20 20:45 UTC, RehanY147 commented on src/app/pages/system/viewenclosure/view-enclosure.component.ts
> +  private _parseEnclosureData(enclosure) {
Should have type for the parameter and the name shouldn't start with `_`

2022-02-20 20:45 UTC, RehanY147 commented on src/app/pages/system/viewenclosure/view-enclosure.component.ts
> +    enclosure.forEach((e, idx) => {
One letter variable name should be avoided.

2022-02-20 20:45 UTC, RehanY147 commented on src/app/pages/system/viewenclosure/view-enclosure.component.ts
> +    const parsedEnclosure = [];
Should have a type

2022-02-21 08:25 UTC, bvasilenko commented
Here's the screenshots depicting how WebUI looks during testing with mockup responses (which I provided instructions for above at the description):

Before my fix (`parseEnclosureData`)
![image](https://user-images.githubusercontent.com/20611516/154915787-12f98927-47dc-440c-b7aa-cc85f18c7252.png)

After my fix:
![image](https://user-images.githubusercontent.com/20611516/154916074-f64728e4-112d-4da0-91b3-9bf533c43be4.png)

Testing on real machine: We actually don't have a machine to test with. The machine we currently have is v12 does not produce the response in the expected format. Instead, it produces the response in the old format. We need a machine with middleware v13 for testing on the hardware. I've also left a comment here: https://jira.ixsystems.com/browse/NAS-114383?focusedCommentId=148512&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-148512

2022-02-21 13:47 UTC, bvasilenko commented
@RehanY147 
Update: here's the machine for testing [tn24.lab.ixsystems.net](http://tn24.lab.ixsystems.net/) user: `root` pass: `abcd1234`

2022-02-21 13:56 UTC, RehanY147 approved these changes
Looks good. The messy view enclosure is fixed now.

2022-02-21 15:24 UTC, merged