NAS-114872: Hide expandable rows from DOM to improve performance
truenas/webui pull request #6432
Opened 2022-02-21 11:35 UTC by denysbutenko

Changes:

- Remove `user-details` components
- Add `ix-detail-row` directive to reduce boilerplate code
- One row can be expanded at the same time
- One row is present in DOM when it's expanded

Testing:
Open Users page and try to expand rows (click or expand button)

2022-02-21 11:35 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114872

2022-02-21 12:45 UTC, undsoft requested changes
I liked the idea of having a separate component for user details. `UserListComponent` is already kinda large with a lot of concerns, so anything we can do to make it smaller is good.
Even with the current approach you could still have a details component and use it within:
```
<ng-template #expandedRowTemplate>
  <user-details-row>
```

Current approach is not type-safe.
I wonder if we can do a structural directive instead, something like a `*matNoDataRow`, but keep it type-safe like `*matCellDef`.

2022-02-21 12:45 UTC, undsoft commented on src/app/modules/ix-tables/directives/ix-detail-row.directive.ts
> +  @Input('ixDetailRowTpl')
Nothing wrong with `ixDetailRowTemplate`

2022-02-21 12:56 UTC, undsoft commented
Also, is there any way `when` property in `MatRowDef` can help us?

2022-03-02 10:16 UTC, bvasilenko approved these changes
Works and looks good to me.

2022-03-07 09:01 UTC, undsoft approved these changes
I'm assuming `when` property wasn't too useful?

In any case, looks good.

2022-03-08 08:48 UTC, merged