NAS-114805: Refactoring scheduler component
truenas/webui pull request #6440
Opened 2022-02-24 15:46 UTC by undsoft

Testing: go to Settings -> General -> GUI, observe new "test" input.

Notes:
* The form is not designed to save.
* Pay extra attention to Custom option.
* Pay extra attention to timezones.
* Modal looks different - that's okay, review it from usability perspective.

2022-02-24 15:46 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114805

2022-02-25 14:27 UTC, dszidi reviewed
On a fresh page reload with caches cleared I get this. The current date is not highlighted and dates in the past that match the cron rule settings are also selected. Editing fields in the form seem to fix this though.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/29865743/155731831-4066be15-1651-42c6-ada7-fcfac7d5325d.png">

2022-02-25 14:40 UTC, dszidi reviewed
This rule causes incorrect preview showing the date in the past. It only does this when you select the current month. 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/29865743/155733389-9eeb42b4-ab61-4cf9-9948-d547ee6e9653.png">


We probably don't want to show anything in the past in the preview or the controls (month drop down selector), since the main goal is to help users understand what the cron tab settings would schedule in the future.

2022-02-27 02:36 UTC, RehanY147 requested changes
I noticed the same issues as described by Damian above.

2022-02-27 08:56 UTC, undsoft commented on src/app/modules/scheduler/classes/cron-schedule-preview/cron-schedule-preview.ts
> +      i = i + 1;
Because there is a `continue` condition that doesn't actually need it.

2022-02-27 08:57 UTC, undsoft commented on src/app/modules/scheduler/classes/cron-schedule-preview/cron-schedule-preview.ts
> +    // TODO: Will be implemented later.
Because I got tired :) It's an edge case feature that I will address in coming PRs soon.

2022-02-27 09:00 UTC, undsoft commented on src/app/modules/scheduler/components/scheduler-modal/scheduler-modal.component.ts
> +      console.error(error);
Here and in other places, I have `console.error` to log error in Sentry mostly.
This particular try catch wraps around `cronParser.parseExpression`

2022-02-28 17:02 UTC, undsoft commented
Comments got addressed.

> We probably don't want to show anything in the past in the preview or the controls (month drop down selector), since the main goal is to help users understand what the cron tab settings would schedule in the future.

While I generally agree that there is no use for being able to go back in time, I decided to keep this functionality for two reasons. It doesn't harm, provides some clues and it would require a bit of ugly code to fix it.

2022-03-01 08:14 UTC, RehanY147 requested changes
When selecting daily, the first of each month is shown not selected when a timestamp for it is visible in the list. Same for weekly. If the first day of the period falls on the 1st of the month, it is not shown as selected.
![image](https://user-images.githubusercontent.com/24204846/156130483-857f09fe-6455-41ae-9540-da6b2d9c024c.png)

2022-03-01 12:32 UTC, RehanY147 requested changes
There should be some visual separation between what is the value and what is the description.
![image](https://user-images.githubusercontent.com/24204846/156169541-3676f11a-c304-402b-9583-2c4e130dbab8.png)
Also, should add a white space between `)At`
![image](https://user-images.githubusercontent.com/24204846/156169666-c7f3aa8c-f763-45e3-80e2-b3cd81359398.png)

2022-03-01 13:08 UTC, undsoft commented
Fixed. 

<img width="677" alt="Снимок экрана 2022-03-01 в 16 08 21" src="https://user-images.githubusercontent.com/1481270/156174560-37d65ca7-c14b-411c-915b-93391131c1e3.png">

2022-03-01 15:08 UTC, dszidi commented
Since we're allowing events in the past, the calendar should also respect this. When I select a specific hour that has already passed in the current day, the calendar view does not highlight the current day.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/29865743/156193876-4c0070ee-c7f3-43a9-8d9e-57e0c9bc389a.png">

2022-03-01 15:22 UTC, undsoft commented
That's kinda not what I meant. You can go to past months - yes, mostly to keep code clean, but also to keep calendar UI consistent, but we won't be showing past events.

2022-03-01 15:41 UTC, dszidi commented
> That's kinda not what I meant. You can go to past months - yes, mostly to keep code clean, but also to keep calendar UI consistent, but we won't be showing past events.

So to clarify, users should be able to navigate the calendar view into the past but no dates should be highlighted?

2022-03-01 15:48 UTC, dszidi approved these changes
LGTM

2022-03-02 11:55 UTC, merged

2022-03-02 23:30 UTC, Hexagon commented
@undsoft If you use croner to build cron strings, but actually run tasks using system cron. I would recommend using 4.2 and enabling THE legacyMode option

See https://github.com/Hexagon/croner/issues/53 for details