Option to global set SED password missing from Advanced
truenas/webui pull request #6446
Opened 2022-02-25 08:42 UTC by AlexKarpov98

Testing:

System -> Advanced
![Screenshot_22](https://user-images.githubusercontent.com/22980553/155683421-330f7609-cf49-4b37-a363-e7e67ac8e3f9.png)

2022-02-25 08:42 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114915

2022-02-25 12:51 UTC, undsoft requested changes
1. Ticket's fix version is set to SCALE-22.02.1. Please retarget PR to stable/angelfish.
2. Shouldn't there be some indication when password is set?

2022-02-25 12:51 UTC, undsoft commented on src/app/pages/system/advanced/advanced-settings.component.ts
>      if ([AdvancedCardId.Kernel].includes(name)) {
Or just add an array element here.

2022-02-27 19:06 UTC, AlexKarpov98 commented
Targeted to stable/angelfish https://github.com/truenas/webui/pull/6454

2022-02-27 19:06 UTC, closed without merging

2022-02-27 20:04 UTC, AlexKarpov98 commented
> 2. Shouldn't there be some indication when password is set?

How can confirm if a password was set?
Advanced Config does not let to know it.