NAS-114525: Fixing memory leaks in enabledWhile/disabledWhile.
truenas/webui pull request #6482
Opened 2022-03-05 14:23 UTC by undsoft

Turns out `enabledWhile/disabledWhile` creates a subscription that you need to unsubscribe yourself.
Code review should be enough.

2022-03-05 14:23 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114525

2022-03-07 09:46 UTC, RehanY147 requested changes

2022-03-07 09:46 UTC, RehanY147 commented on src/app/pages/system/advanced/syslog-form/syslog-form.component.ts
> +  subscriptions: Subscription[] = [];
No `UntilDestroy({ arrayName: 'subscription' })`?

2022-03-07 09:55 UTC, undsoft commented on src/app/pages/system/advanced/syslog-form/syslog-form.component.ts
> +  subscriptions: Subscription[] = [];
Good catch. Fixed.

2022-03-07 10:15 UTC, RehanY147 approved these changes
Looks good

2022-03-07 11:05 UTC, AlexKarpov98 approved these changes
LGTM! 👍

2022-03-07 11:14 UTC, merged