NAS-115200 / 22.12 / NAS-115200: Refactoring OpenvpnServerComponent to ix-forms
truenas/webui pull request #6504
Opened 2022-03-10 14:26 UTC by undsoft

Testing: Network -> OpenVPN -> Server.
You may also need to create certificates in Credentials -> Certificates. You can use appropriate profile when creating a certificate.

2022-03-10 14:26 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-115200

2022-03-14 22:35 UTC, RehanY147 requested changes
The `ix-select` on clicking `Download Client Config` shows no options and is empty. Previously, it showed a list of certificates available.

2022-03-14 22:35 UTC, RehanY147 commented on src/app/pages/network/components/download-client-config-modal/download-client-config-modal.component.spec.ts
> +  it('shows a list of client certificates', async () => {
This test should be fixed too.

2022-03-15 13:51 UTC, undsoft commented on src/app/pages/network/components/download-client-config-modal/download-client-config-modal.component.spec.ts
> +  it('shows a list of client certificates', async () => {
Thanks, fixed.

2022-03-15 15:25 UTC, RehanY147 approved these changes
Looks good to me

2022-03-16 10:26 UTC, merged