NAS-115365: Refactoring DatasetTrivialPermissionsComponent
truenas/webui pull request #6538
Opened 2022-03-19 15:34 UTC by undsoft

Create a dataset and go to View Permissions -> Edit.

2022-03-19 15:34 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-115365

2022-03-21 19:45 UTC, AlexKarpov98 commented on src/app/pages/storage/volumes/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.ts
> -    data['acl'] = [];
There is a missing - `acl` is set empty array.

2022-03-21 19:49 UTC, AlexKarpov98 requested changes
![Screenshot_6](https://user-images.githubusercontent.com/22980553/159352229-f4c96583-f126-4e11-93d9-503ebdfb3137.png)

2022-03-21 19:59 UTC, undsoft commented on src/app/pages/storage/volumes/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.ts
> +    const dialogRef = this.matDialog.open(EntityJobComponent, {
I deliberately didn't choose to change this. I think EntityJobComponent is used to show progress when there are a lot of files that need to be updated when recursive flag is used.

2022-03-21 22:00 UTC, AlexKarpov98 approved these changes
LGTM! 👍

2022-03-22 09:22 UTC, merged