NAS-115184: Refactoring Groups
truenas/webui pull request #6614
Opened 2022-04-18 13:59 UTC by denysbutenko

2022-04-18 13:59 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-115184

2022-04-20 12:16 UTC, RehanY147 requested changes

2022-04-25 07:01 UTC, denysbutenko commented on src/app/pages/account/groups/group-list/group-list.component.ts
> +  error$ = this.store$.select(selectGroupState).pipe(map((state) => state.error));
Yeah, good point!

2022-04-25 07:02 UTC, denysbutenko commented on src/app/pages/account/groups/groups.routing.ts
> +        data: { title: 'Update Members', breadcrumb: 'Members' },
Probably some issues in the breadcrumb generation. Checking details

2022-04-28 02:28 UTC, RehanY147 approved these changes
Looks good. Changes are persistent and form submits successfully. One minor note, the "Save" button doesn't disable while the form is submitting. It's possible to keep clicking the button multiple times.

2022-04-28 06:19 UTC, denysbutenko commented
> Looks good. Changes are persistent and form submits successfully. One minor note, the "Save" button doesn't disable while the form is submitting. It's possible to keep clicking the button multiple times.

Good note, thanks!

2022-04-28 09:27 UTC, merged