HTTPS redirect disables browser VNC display
truenas/webui pull request #6645
Opened 2022-04-29 17:39 UTC by AlexKarpov98

Testing:

System Settings -> General -> GUI Setting -> Enable HTTPS Redirect and Restart WebUI
![Screenshot_36](https://user-images.githubusercontent.com/22980553/165995223-7b12d6c3-ab9e-4823-b4ec-b104a6201803.png)

Virtualization -> Virtual Machine -> Click `<...> Display` Button
![Screenshot_35](https://user-images.githubusercontent.com/22980553/165995253-5092ae6a-28de-4c37-b250-2d461d18898f.png)

2022-04-29 17:39 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-112226

2022-04-29 18:05 UTC, undsoft requested changes

2022-04-29 18:05 UTC, undsoft commented on src/app/services/redirect.service.ts
> +      this.ws.call('system.general.config')
You can use `waitForGeneralConfig` instead of request.

2022-04-29 18:05 UTC, undsoft commented on src/app/services/redirect.service.ts
> +  open(url: string, target?: string): void {
Maybe a more descriptive name than `open`?

2022-04-29 18:05 UTC, undsoft commented on src/app/pages/system/general-settings/gui-form/gui-form.component.ts
> +      this.ws.call('system.general.update', [body]).pipe(
can switchMap here.

2022-04-29 18:05 UTC, undsoft commented on src/app/pages/system/general-settings/gui-form/gui-form.component.spec.ts
> +  it('shows confirm dialogs of enable redirect and service restart and restarts it', async () => {
Better to add another test case to test this specifically.

2022-04-29 18:05 UTC, undsoft commented on src/app/pages/network/network.component.ts
> +        this.redirect.open(`http://${row.ipaddress}`);
The problem only happens when user is trying to access paths under truenas host. This is probably going to be a different ip, so warning is not needed here.
Same for ipmi form above.

2022-05-01 21:21 UTC, bvasilenko approved these changes
Looks good overall, just a small comment about the text

2022-05-02 07:51 UTC, undsoft commented on src/app/services/redirect.service.ts
> +You can try opening app url in a fresh browser or incognito mode.<br>
New window or tab won't solve the issue. I guess we can just remove the part about "fresh browser".

2022-05-10 08:42 UTC, undsoft approved these changes
There is a weird behavior in Gui Form when checkbox is changed. When Save button is pressed, it momentarily reverts to previous value.
It's confusing especially if form takes a bit of time to save.

https://user-images.githubusercontent.com/1481270/167587365-2fb85468-ca3c-4f1c-a474-17c28a3eded0.mov

Other than that, works well.

2022-05-10 08:42 UTC, undsoft commented on src/app/modules/common/dialog/redirect-dialog/redirect-dialog.component.spec.ts
> +  xit('copies URL when Copy URL is pressed', async () => {
Is test disabled on purpose?

2022-05-10 08:42 UTC, undsoft commented on src/app/pages/system/general-settings/gui-form/gui-form.component.ts
> +        this.isFormLoading = true;
Probably needs `this.cdr.markForCheck()` as I don't see loading indicator.

2022-05-12 06:07 UTC, merged