NAS-115852 - Better header with custom html elements
truenas/webui pull request #6652
Opened 2022-05-02 02:14 UTC by RehanY147

2022-05-02 02:14 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-115852

2022-05-02 06:41 UTC, denysbutenko requested changes
Will provide more feedback after testing

2022-05-02 06:41 UTC, denysbutenko commented on src/app/pages/account/users/user-list/user-list.component.html
> +        <label>Show Built-in Users</label>
Missing translation pipe

2022-05-02 06:41 UTC, denysbutenko commented on src/app/modules/common/page-title-header/page-title-header.component.scss
> +  color: white;
Seems better to use some variable here

2022-05-02 06:41 UTC, denysbutenko commented on src/app/modules/common/page-header-actions-wrapper/header-input.directive.ts
> +    private templateRef: TemplateRef<any>,
any is not good

2022-05-02 08:43 UTC, denysbutenko commented
https://user-images.githubusercontent.com/351613/166207691-00208382-31ef-4825-9377-5758a0bd6962.mp4

1. The search input does not look well. No focus when clicking on the icon. UI jumps on focus.
2. Hover effect on the primary button looks inconsistent to other pages

2022-05-05 12:16 UTC, denysbutenko commented
Groups old one:
![image](https://user-images.githubusercontent.com/351613/166920148-c4cbcc6f-5e2a-48ee-809c-ef6410bfa720.png)
Users new one:
![image](https://user-images.githubusercontent.com/351613/166920156-76d6db4b-3aa9-4350-923a-3f61ddca7707.png)
Still looks and behaves inconsistently. 

- Content goes below on a few pixels when search input is focused.
- search icon requires `pointer-events: none` to pass clicks on the input
- The primary button does not have a hover effect on other pages but there become gray

2022-05-05 12:17 UTC, denysbutenko requested changes

2022-05-05 12:27 UTC, denysbutenko commented
Focus state on buttons looks nice 👍🏻

2022-05-09 13:01 UTC, denysbutenko requested changes
![image](https://user-images.githubusercontent.com/351613/167412957-1200ce15-c201-4b83-9c55-a87037e95e93.png)
![image](https://user-images.githubusercontent.com/351613/167413004-172d2eb2-815f-48a9-aae7-f2747dd7bdde.png)
Looks better now. I like how the page looks now without the border and gap below

Still see minor differences:

- breadcrumb and title on the users page look collapsed in comparison to the groups page
- search icon size mismatch between groups and users page
- search input has different border width on focus state
- height of search input is a bit different

2022-05-10 12:38 UTC, RehanY147 commented
@denysbutenko The height and width issue of the input might be related to different screen zoom while comparing. Otherwise, I don't see significant difference. Can you confirm please?

2022-05-10 12:42 UTC, denysbutenko commented
> @denysbutenko The height and width issue of the input might be related to different screen zoom while comparing. Otherwise, I don't see significant difference. Can you confirm please?

There are 36px and 40px same zoom ~ 10% diff

2022-05-10 14:49 UTC, merged