Migrating system dataset pool does not change displayed system dataset pool until page reload
truenas/webui pull request #6673
Opened 2022-05-08 18:18 UTC by AlexKarpov98

Testing:

System Settings -> Advanced -> System Dataset Pool -> Configure

2022-05-08 18:18 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116096

2022-05-09 21:50 UTC, dszidi approved these changes
Updates system dataset without needing to refresh the page.
LGTM

2022-05-10 09:23 UTC, undsoft requested changes
I don't see what the difference between old code and new code is.
I still get old system dataset pool shown in the table.

Also, there is another issue if user selects Cancel in restart dialog. This stops saving, but does not clear loading indicators.

2022-05-11 12:47 UTC, AlexKarpov98 commented
Solved issues already in [6678](https://github.com/truenas/webui/pull/6678) 

- if user selects Cancel in restart dialog. This stops saving, but does not clear loading indicators
- closes slide even if the state of the job is not successful
- not displayed any validation error in the interface

so close this PR

2022-05-11 12:48 UTC, closed without merging