Useless / broken breadcrumbs
truenas/webui pull request #6699
Opened 2022-05-17 08:23 UTC by AlexKarpov98

2022-05-17 08:23 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116149

2022-05-17 17:16 UTC, dszidi reviewed
@undsoft  IMO if we're going to remove these breadcrumbs, then the titles themselves will probably need to be a little bit more descriptive. Couple of examples are below

<img width="726" alt="image" src="https://user-images.githubusercontent.com/29865743/168871960-2b2e1bce-caa0-46d5-89bd-1003755117e4.png">

This could be something like "Advanced System Settings"

<img width="726" alt="image" src="https://user-images.githubusercontent.com/29865743/168872208-3d5fb9e0-06d5-4f51-a0ea-711dbb88f3be.png">

This title could be something like "Memory Reports"

2022-05-18 16:28 UTC, undsoft requested changes
Yes, agreed, we should either improve wording, i.e. Advanced -> Advanced Settings, CPU -> CPU Reports, etc. or maybe we could have non-clickable tooltips, but show them styled differently?
Also Local Users and other subpages in Credentials have broken breadcrumbs.

2022-05-19 14:25 UTC, undsoft approved these changes
Maybe let's use a slightly more muted color for disabled breadcrumbs (like --alt-fg2).
Otherwise looks good.

2022-05-25 19:46 UTC, merged