"Maximum Upload Parts" is shown in "Authentication" section of S3 cloud sync credentials
truenas/webui pull request #6717
Opened 2022-05-24 06:22 UTC by AlexKarpov98

Testing:
Credentials -> Backup Credentials -> Cloud Credentials -> Add (Provider: Amazon S3)
Removed `Maximum Upload Parts` field

2022-05-24 06:23 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116345

2022-05-24 08:40 UTC, undsoft requested changes
I think Vladimir meant that field doesn't belong to this section and thus should be in some other section, not that it should be removed completely.

2022-05-24 10:24 UTC, themylogin requested changes
😱😱😱

2022-05-25 12:03 UTC, undsoft approved these changes
Looks good.

2022-05-25 19:45 UTC, merged