NAS-115711: Support CPU pinning
truenas/webui pull request #6735
Opened 2022-05-31 11:59 UTC by heppu

UI for already merged CPU pinning support in middleware. https://github.com/truenas/middleware/pull/9045

2022-06-01 05:27 UTC, AlexKarpov98 commented on src/app/pages/vm/vm-form/vm-form.component.ts
> +          inputType: 'string',
Please remove `inputType: 'string'`

2022-06-01 05:28 UTC, AlexKarpov98 commented on src/app/pages/vm/vm-form/vm-form.component.ts
> +          inputType: 'string',
Same here remove `inputType: 'string'`

2022-06-01 06:49 UTC, heppu commented on src/app/pages/vm/vm-form/vm-form.component.ts
> +          inputType: 'string',
Done

2022-06-01 07:13 UTC, AlexKarpov98 commented on src/app/pages/vm/vm-form/vm-form.component.ts
> +          tooltip: helptext.cpuset.tooltip,
Also add validations for `cpuset`, `nodeset` fields in [vm-wizard.component.ts](https://github.com/truenas/webui/blob/c812ab457749c1073388ff9018698f759bc845c7/src/app/pages/vm/vm-wizard/vm-wizard.component.ts)

2022-06-01 07:16 UTC, AlexKarpov98 reviewed
LGTM!
![Screenshot_78](https://user-images.githubusercontent.com/22980553/171348789-717efeb7-9370-4886-91a7-26e6bb0cddad.png)
![Screenshot_79](https://user-images.githubusercontent.com/22980553/171348886-792701c3-e3f7-406f-8f69-98d8829e2b0a.png)

2022-06-01 07:17 UTC, heppu commented on src/app/pages/vm/vm-form/vm-form.component.ts
> +          tooltip: helptext.cpuset.tooltip,
Where in the repo should I place this validator logic?

2022-06-01 20:18 UTC, heppu commented on src/app/pages/vm/vm-form/vm-form.component.ts
> +          tooltip: helptext.cpuset.tooltip,
Oh I did not notice your edit. I will just use inline regex then.

2022-06-02 13:01 UTC, heppu commented on src/app/pages/vm/vm-form/vm-form.component.ts
> +          tooltip: helptext.cpuset.tooltip,
Done.

2022-06-02 13:34 UTC, heppu commented
Rebased to lates master and added validation. Should be now ready to merge.

2022-06-05 08:07 UTC, AlexKarpov98 requested changes
Seems validation does not work properly.
![Screenshot_99](https://user-images.githubusercontent.com/22980553/172041497-a0bf7f4f-5005-42d2-9eba-8046f2a4135c.png)
![Screenshot_100](https://user-images.githubusercontent.com/22980553/172041500-9c56fa37-e629-4cd7-8633-19de5d33f6e4.png)

2022-06-08 10:57 UTC, heppu commented
Hmm I don't have access to TrueNAS server right now to test against with so I used only online regex tool to validate it. I will update this once I get back home and can properly test it.

2022-07-13 06:19 UTC, AlexKarpov98 requested changes
This issue doesn't still work.

![image](https://user-images.githubusercontent.com/22980553/178664206-d6f41d19-8d27-47c6-8ca9-2ef8d2c00926.png)

2022-07-22 06:02 UTC, heppu commented
@AlexKarpov98 Should be now fixed. Didn't remember that \ had to be escaped in js :D

2022-07-28 10:08 UTC, heppu commented
Ping @AlexKarpov98

2022-07-29 06:39 UTC, undsoft requested changes
New fields are not passed to websocket when form is saved.
You need to add:
```
    vmPayload['cpuset'] = value.cpuset;
    vmPayload['nodeset'] = value.nodeset;
    vmPayload['pin_vcpus'] = value.pin_vcpus;
```
in `VmWizardComponent` `customSubmit`.

2022-07-29 07:18 UTC, heppu commented
@undsoft Done

2022-07-29 10:12 UTC, undsoft approved these changes
Looks good, thanks.

2022-07-29 10:12 UTC, merged