Nas 116040 Clean up SysInfoComponent
truenas/webui pull request #6788
Opened 2022-06-14 10:20 UTC by Raz-Dva

Check SysInfoComponent.
System Settings -> General ( Support widget )

2022-06-15 08:53 UTC, undsoft requested changes
Looks good overall.

2022-06-15 08:53 UTC, undsoft commented on src/app/pages/system/general-settings/support/sys-info/sys-info.component.ts
> +  @Input() license_info: LicenseInfoInSupport;
need to be camelCase.

2022-06-15 08:53 UTC, undsoft commented on src/app/pages/system/general-settings/support/sys-info/sys-info.component.html
> +      ( {{'expires in' | translate}} {{ '{n, plural, one {# day} other {# days} }' | translate: {n: license_info.daysLeftinContract} }}
Needs to be one string: 'expires in {n...}'

2022-06-15 08:53 UTC, undsoft commented on src/app/pages/system/general-settings/support/sys-info/sys-info.component.html
> +    <span class="value">{{ system_info.model}}</span>
Inconsistent spacing around {{ }}. Should be with spaces.

2022-06-15 08:53 UTC, undsoft commented on src/app/pages/system/general-settings/support/sys-info/sys-info.component.html
> +    <span *ngIf="license_info.daysLeftinContract && license_info.daysLeftinContract > 0" class="value">
First part of if statement seems unnecessary.

2022-06-15 08:53 UTC, undsoft commented on src/app/pages/system/general-settings/support/sys-info/sys-info.component.ts
>    templateUrl: './sys-info.component.html',
Please add changeDetection.onPush.

2022-06-15 08:53 UTC, undsoft commented on src/app/pages/system/general-settings/support/sys-info/sys-info.component.spec.ts
> +    spectator = createHost('<ix-sys-info [system_info]="systemInfo"></ix-sys-info>', {
You don't need to use createHost here. You can use normal createComponent, there is a second argument in it that allows to pass in Inputs.

2022-06-15 08:53 UTC, undsoft commented on src/app/pages/system/general-settings/support/sys-info/sys-info.component.spec.ts
> +    const sysInfoItems = spectator.queryAll('.sys-info-wrapper .value');
would be good to also test labels. You could use reduce to form a dictionary: { Label1: Value, Label2: Value }, etc.

2022-06-16 12:59 UTC, undsoft commented
Some machines may have two serial numbers. There is a bug that doesn't show them properly.
It was fixed here: https://github.com/truenas/webui/pull/6796 
Can you also incorporate this fix in your code?

2022-06-20 12:53 UTC, Raz-Dva commented
Yea. I added changes from https://github.com/truenas/webui/pull/6796

2022-06-20 13:37 UTC, undsoft approved these changes
Looks good.

2022-06-20 14:17 UTC, Raz-Dva commented
Thanks.

2022-06-20 14:18 UTC, merged