Add basic capacity management card and ix-dataset-node component
truenas/webui pull request #6799
Opened 2022-06-16 14:52 UTC by denysbutenko

2022-06-16 14:52 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116409

2022-06-17 21:44 UTC, RehanY147 requested changes

2022-06-17 21:44 UTC, RehanY147 commented on src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
> +  readonly trackByFn: TrackByFunction<Dataset> = (_, node) => node.id;
Might as well replace `node` with `dataset` here too

2022-06-18 08:18 UTC, undsoft commented on src/app/pages/datasets/components/dataset-management/dataset-management.component.html
> +                [attr.aria-label]="'toggle ' + dataset.name"
Should be translated.

2022-06-18 08:18 UTC, undsoft commented on src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts
> +          combineLatest([
forkJoin without `take(1)` should be better suited here.

2022-06-18 08:18 UTC, undsoft commented on src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts
> +      take(1),
I don't think take(1) is necessary.

2022-06-18 08:18 UTC, undsoft commented on src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts
> +  ngOnChanges(): void {
Would be good to split this into a method or two.

2022-06-18 08:18 UTC, undsoft commented on src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.html
> +        <a [routerLink]="['/storage/user-quotas', dataset.id]">{{ 'Manage User Quotas' | translate }}</a>
Remember to copy quota management to new module in this or future PRs.

2022-06-19 12:18 UTC, denysbutenko commented on src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts
> +  editDataset(): void {
What would be the preferred way to do that. Separate component or tweak an existing form to display quotas fields only?

2022-06-20 13:52 UTC, undsoft approved these changes
👍🏻

2022-06-20 15:28 UTC, RehanY147 approved these changes
Looks good now. I've created a ticket for the chart here [NAS-116788](https://jira.ixsystems.com/browse/NAS-116788). Once designs are finalized. When ready the ticket will be available in the queue.

2022-06-20 15:47 UTC, merged