NAS-116395: Pool usage details widget/card
truenas/webui pull request #6817
Opened 2022-06-22 07:39 UTC by bvasilenko

Testing:
Temporary location of this widget is Storage2 page

2022-06-22 07:40 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116395

2022-06-22 08:33 UTC, denysbutenko reviewed
I'll test it and provide more feedback

2022-06-22 08:33 UTC, denysbutenko commented on package.json
> +    "ng2-charts": "~2.4.1",
We already have d3 and probably other libraries for charts, what is benefit of this one?

2022-06-22 08:33 UTC, denysbutenko commented on src/app/pages/storage2/components/pools-dashboard/widget-usage/widget-usage.component.ts
> +  Warn = 'warn',
Keys don't need shortcuts

2022-06-22 08:33 UTC, denysbutenko commented on src/app/pages/storage2/components/pools-dashboard/widget-usage/widget-usage.component.ts
> +    '../../../../dashboard/components/widget/widget.component.scss',
Perhaps can be replaced with absolute path

2022-06-22 08:33 UTC, denysbutenko commented on src/app/pages/storage2/components/pools-dashboard/pools-dashboard.component.html
> +  <div class="spinner-container" *ngIf="isLoading">
There is new approach for loading state, look for ngx-skeleton-loader examples

2022-06-22 15:11 UTC, denysbutenko requested changes
![image](https://user-images.githubusercontent.com/351613/175064770-3f107f73-0097-4cd2-9b2b-2a4762260200.png)
Does not follow design according to [discussions#6767](https://github.com/truenas/webui/discussions/6767) and other widgets

![name](https://user-images.githubusercontent.com/29865743/172702141-16271f37-1385-4a1e-9c9c-e6cba5b6bb92.png)

2022-06-28 08:52 UTC, bvasilenko commented
@denysbutenko 
I've done the improvements according to the feedback. Could you please test one more time?

2022-06-28 13:02 UTC, denysbutenko approved these changes
![image](https://user-images.githubusercontent.com/351613/176185015-185a62c4-888e-4fb0-a351-d90993f45db0.png)

Looks good 👍🏻

2022-06-30 06:33 UTC, merged