Unused Resources component for Pools Dashboard
truenas/webui pull request #6821
Opened 2022-06-23 09:58 UTC by AlexKarpov98

![image](https://user-images.githubusercontent.com/22980553/175272809-42b59803-5d88-48a5-a9be-d72a2ad39ec7.png)

2022-06-23 09:58 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116398

2022-06-23 12:07 UTC, undsoft commented on src/app/pages/storage2/components/pools-dashboard/pools-dashboard.component.html
> +      ix-auto-identifier="_POOL_CREATE"
ix-auto identifiers and matTooltip can be removed.

2022-06-23 12:08 UTC, undsoft commented on src/app/pages/storage2/components/unassigned-disk/manage-unassigned-disk-dialog/manage-unassigned-disk-dialog.component.ts
> +})
changeDetection.OnPush

2022-06-23 12:09 UTC, undsoft commented on src/app/pages/storage2/components/unassigned-disk/unassigned-disk.component.ts
> +})
onPush

2022-06-27 07:55 UTC, RehanY147 requested changes
Instead of listing down the pools in a single column table, I think a select with the pool options followed by a button would be a better. Also, since this does not need much vertical space, giving it its own column in the model will waste space.
Furthermore, if you don't intent to add disks to pool, showing the pool selection is confusing and unnecessary. I think it should only be shown if the user clicks a button "Add to Pool" similar to "Create Pool". We can maybe show another confirm dialog that takes the pool selection before proceeding. Or conditionally show the pool select from a checkbox maybe.
"Add disks to existing pool" that would show the pool select and update the button to say "Add disks" instead of "Create a Pool"

2022-06-29 07:08 UTC, AlexKarpov98 commented
![Screenshot_100](https://user-images.githubusercontent.com/22980553/176373870-0190b86c-c916-4335-82cf-139af8d1fe41.png)

2022-06-29 12:09 UTC, RehanY147 requested changes
Unused heading shows when there's nothing to show
![image](https://user-images.githubusercontent.com/24204846/176424934-e8103e15-f94b-44f6-8fb1-dd0c826398d0.png)

Furthermore, when you have many disks, the view doesn't work.
![disks issue](https://user-images.githubusercontent.com/24204846/176432766-2ba4a150-ce50-4322-9252-4b565e71daa6.gif)

We should limit disks list view to a portion of the screen and have a nested scroll. The bottom checkboxes should be always visible. And let's replace the radio button list of pools with a select drop down.

2022-07-01 09:41 UTC, AlexKarpov98 commented
![image](https://user-images.githubusercontent.com/22980553/176869802-5ae84283-8288-4bd1-8edd-10403aa27652.png)

2022-07-05 01:12 UTC, RehanY147 approved these changes
Looks good. Nice work!

2022-07-07 09:49 UTC, undsoft approved these changes
I don't know if I fully like how Unused Disks modal looks, but it's probably more of a question to Damian.
Good to merge.

2022-07-07 17:33 UTC, dszidi reviewed
Just from looking at the images posted so far, I would suggest that the unassigned disks should be shown as an inventory. The current approach would have us listing potentially hundreds of meaningless disk labels. They should instead be broken down by type and capacity. 
For example:

### Unused Disks

- 2 X 2 TB NVME
- 10 X 4 TB SSD
- 12 X 12 TB HDD

2022-07-08 18:54 UTC, merged