NAS-116914: Various improvements to datasets page
truenas/webui pull request #6829
Opened 2022-06-25 09:53 UTC by undsoft

1. Better styling for first cell in tree table on smaller screens.
2. Encryption cell and size cell updated.
3. Details header.

2022-06-25 09:53 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116914

2022-06-25 11:26 UTC, RehanY147 requested changes
Getting this error when I select a zvol on the permissions card I think.
![image](https://user-images.githubusercontent.com/24204846/175771472-774e3a00-71a4-4876-896f-a88b9c786031.png)

2022-06-25 11:27 UTC, undsoft commented
This is not because of this PR.

2022-06-26 10:58 UTC, RehanY147 approved these changes
Looks good to me

2022-06-27 11:15 UTC, merged