NAS-117212: Auto TRIM and label updates
truenas/webui pull request #6877
Opened 2022-07-16 07:06 UTC by undsoft

Testing: go to new Storage dashboard and check Auto Trim in ZFS Health card.

2022-07-16 07:06 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117212

2022-07-16 16:53 UTC, denysbutenko requested changes
https://user-images.githubusercontent.com/351613/179364404-6163ad17-88ae-4754-906f-6965ef1068a7.mp4

Getting error in the console and it's not handled in UI

2022-07-18 10:38 UTC, undsoft commented
I think it should work now, but would be interesting to see what kind of error it gives you.

2022-07-18 12:15 UTC, denysbutenko approved these changes
<img width="613" alt="image" src="https://user-images.githubusercontent.com/351613/179508895-eef05d50-0a33-481b-8cb8-402b60ed2e6a.png">

Looks good!

2022-07-18 12:16 UTC, merged