NAS-117108: Added custom form controls
truenas/webui pull request #6892
Opened 2022-07-22 00:22 UTC by RehanY147

2022-07-22 00:23 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117108

2022-07-25 11:06 UTC, undsoft requested changes
Couldn't install `photoprism` or `home-assistant`. The save button stays disabled.

2022-07-27 08:14 UTC, undsoft approved these changes
Didn't find any obvious regressions. Any tests we can add?

2022-07-27 08:14 UTC, undsoft commented on src/app/modules/ix-forms/components/ix-dynamic-form/classes/custom-untyped-form-field.ts
> +    CustomUntypedFormArray |
`|` usually does in the beginning of the line:
```
export type A =
  | B
  | C
```

2022-07-27 09:35 UTC, RehanY147 commented
Not really. These changes don't impact how the form behaves. Just changes how code handles it.

2022-07-27 09:35 UTC, merged