NAS-117153: Created checkbox create_empty_src_dirs in Cloud Sync Task
truenas/webui pull request #6905
Opened 2022-07-27 09:08 UTC by Raz-Dva

Data Protection -> Cloud Sync Tasks -> button "Add"
For the "Cloud Sync Task" form, the "Create empty ..." checkbox has been added.
Check the new checkbox. An update needs to be done.

2022-07-27 09:08 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117153

2022-07-29 09:06 UTC, AlexKarpov98 requested changes
- A `create_empty_src_dirs` attribute isn't registered into `CloudSyncTask` type.
- A **tooltip** needs to be defined, I think.

2022-07-29 14:56 UTC, Raz-Dva commented
- _create_empty_src_dirs_ added to CloudSyncTask interface
- I checked with Eugene. There will be no tooltip for this field

2022-07-30 09:51 UTC, AlexKarpov98 approved these changes
Code change looks good.

2022-07-31 21:49 UTC, merged