NAS-117249: Fixing errors in replication tasks
truenas/webui pull request #6946
Opened 2022-08-05 14:06 UTC by undsoft

Testing: go to Data Protection, try to create a replication task, but make request fail (for example by changing something in code).
Check that there are no unexpected errors in the console and that there are no new periodic snapshot tasks.

2022-08-05 14:07 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117249

2022-08-07 01:44 UTC, RehanY147 requested changes
I changed the payload to `{}` wherever a call was being made to `this.createCalls` and got this error on the console.
![image](https://user-images.githubusercontent.com/24204846/183271507-226b417c-2fb7-475e-a81c-1718591f9924.png)

2022-08-07 08:24 UTC, undsoft commented
I've added a small check, but still this method of testing is bit contrived. I would suggest adding a new dummy field in the payload.

2022-08-08 23:14 UTC, RehanY147 approved these changes
Looks good

2022-08-09 07:42 UTC, merged