Make WebUI compatible with iSCSI API changes
truenas/webui pull request #6967
Opened 2022-08-11 06:05 UTC by bvasilenko

**Testing**

Go to **Sharing > Block (iSCSI) Shares Targets > Settings**, and follow the ticket's description

2022-08-11 06:05 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117350

2022-08-11 09:59 UTC, undsoft requested changes

2022-08-11 09:59 UTC, undsoft commented on src/app/pages/sharing/iscsi/target-global-configuration/target-global-configuration.component.ts
> +    listen_port: [null as number],
Needs required validator and [required] attribute.

2022-08-11 09:59 UTC, undsoft commented on src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.html
> +                [multiple]="true"
I don't think we need multiple=true anymore.

2022-08-11 09:59 UTC, undsoft commented on src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
> +        const ips = portal.listen.map((ip) => ip.ip);
Port not removed from the form that is shown when you select `Create New` under Portals.

2022-08-11 09:59 UTC, undsoft commented on src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
>          field.options.push({ label: portal.tag + ' (' + ips + ')', value: portal.id });
Authorized networks not removed from Wizard.

2022-08-15 16:11 UTC, bvasilenko commented
All the requested changes now addressed

2022-08-16 12:12 UTC, undsoft commented on src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
> +        const ips = portal.listen.map((ip) => ip.ip);
Not properly addressed. There is still a port field.

2022-08-16 12:13 UTC, undsoft approved these changes
Wizard wasn't updated correctly, otherwise okay.

2022-08-18 20:23 UTC, bvasilenko commented
Now wizard is working as well

2022-08-19 06:58 UTC, merged