NAS-117581: Fix Launch Docker Image button bugs
truenas/webui pull request #6968
Opened 2022-08-11 06:11 UTC by bvasilenko

2022-08-11 06:12 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117581

2022-08-11 20:01 UTC, AlexKarpov98 commented on src/app/pages/applications/applications.component.ts
> +      this.dockerImagesTab.onToolbarAction(evt);
I think that it should apply an event exactly into a tab content when the tab is changed so a `switch-case` condition should be keep as original code.

A `disabled` property of the **`Launch Docker Image`** button depends on `isSelectedPool` state.
So I think that the solution is to set `isSelectedPool` state correctly when the page is loaded.

2022-08-11 20:04 UTC, AlexKarpov98 requested changes
Need to change.

2022-08-18 05:58 UTC, bvasilenko commented
Thanks for your review, @AlexKarpov98  . I realized that I need to push more changes. 
I'm closing this, and once ready, I'll create a new PR.

2022-08-18 05:58 UTC, closed without merging