Nas-117566 Add support for snapdev
truenas/webui pull request #6990
Opened 2022-08-17 19:59 UTC by Raz-Dva

Added new field in create/update  dataset/zvol form (Advanced settings) in new storage
Create or update dataset/zvol. Test the new snapdev field. The default value is hidden. Field is inheritable.

2022-08-17 19:59 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117566

2022-08-18 15:56 UTC, undsoft requested changes
1. In zvol form `snapdev` is not in Advanced settings.
2. I think the way it works for most fields is that it tries to inherit value first before going for the default value.

2022-08-19 12:55 UTC, Raz-Dva commented
Fixed.

2022-08-20 09:05 UTC, undsoft approved these changes
Needs better name for enum, otherwise looks good.

2022-08-22 09:09 UTC, Raz-Dva commented on src/app/enums/dataset.enum.ts
> +export enum DatasetCommonOpt {
Added new enum DatasetSnapdev.

2022-08-22 09:47 UTC, undsoft approved these changes
👍🏻

2022-08-22 12:23 UTC, merged