NAS-117734: Handle nulls in disk temperatures
truenas/webui pull request #6995
Opened 2022-08-20 05:36 UTC by AlexKarpov98

**Testing:**
Storage => Disk Health Card
The min, max or avg temperature value should show 'No Data' instead of 0 if it returns null from the endpoint.

2022-08-20 05:36 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117734

2022-08-20 08:56 UTC, undsoft requested changes
```
InvalidPipeArgument: 'No Data is not a number' for pipe 'DecimalPipe'.
```

May be better to have that if condition in template.

2022-08-21 16:27 UTC, AlexKarpov98 commented
> ```
> InvalidPipeArgument: 'No Data is not a number' for pipe 'DecimalPipe'.
> ```
> 
> May be better to have that if condition in template.

Fixed.

2022-08-22 10:01 UTC, undsoft approved these changes
Looks good
<img width="443" alt="Снимок экрана 2022-08-22 в 12 00 42" src="https://user-images.githubusercontent.com/1481270/185895101-6c19e4b9-0f63-4afb-bc15-26bca228ddd9.png">

2022-08-22 10:04 UTC, merged