NAS-117854: Add 'validate_host_path' field
truenas/webui pull request #7018
Opened 2022-08-25 14:10 UTC by bvasilenko

**Testing**

On the **Apps** page, at the toolbar **Settings > Advanced Settings**

- New checkbox "Validate host path" saves/loads to a new field `validate_host_path` in `kubernetes.update`  (this field presents at the latest nightly build)

- When user unchecks this checkbox (in other words when it is `false`), UI shows a warning: "Disabling validation of host path can result in a data loss."

2022-08-25 14:11 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117854

2022-08-30 15:35 UTC, RehanY147 requested changes
Instead of showing a warning on submit, we should show a yellow warning underneath the field immediately when it is unchecked

2022-09-02 05:42 UTC, bvasilenko commented
@RehanY147 Now warning is displayed right below the UI element

2022-09-02 22:37 UTC, RehanY147 approved these changes
Looks good

2022-09-05 06:28 UTC, merged