NAS-117631: Rework to expansible/collapsible snapshots rows
truenas/webui pull request #7037
Opened 2022-08-31 09:44 UTC by bvasilenko

**Details**

According to the ticket, the table is reworked:

  - details which was previously in the "extra columns" now moved to the expandable detail block under every row

  - for every row, when row expanded - now it gets additional details from `zfs.snapshot.query` with `id = ...` condition

2022-08-31 09:44 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117631

2022-08-31 12:21 UTC, undsoft requested changes
I don't think ticket called for removal of `Show extra columns` option. It's more like the version without extra columns should have details view.
We could also use a bit of loading indication when details view loads data. Right now it just flashes N/A, at the very least it should show empty space.

2022-08-31 12:21 UTC, undsoft commented on src/app/pages/datasets/modules/snapshots/store/snapshot.effects.ts
> -        snapshotExcludeBootQueryFilter,
So what did this condition got removed?

2022-09-02 05:45 UTC, bvasilenko commented
Now "Show extra columns" mode is restored, as well as `snapshotExcludeBootQueryFilter `

2022-09-02 12:12 UTC, undsoft approved these changes
There is an issue that probably existed before your changes, that would be good to fix, while we are here.
1. Go to Datasets, click on Manage Snapshots,
2. I'll be taken to a pre-filtered list of snapshots. 
3. If I then perform an action that results in snapshots being refreshed (such as deleting one), the filter will be re-applied, but only partially. There will be nothing in filter box.
If not easy to fix, this can be a separate ticket.

Other than that looks good.

2022-09-05 09:49 UTC, bvasilenko commented
The issue should be fixed now

2022-09-06 08:33 UTC, undsoft approved these changes

2022-09-07 06:12 UTC, merged