Preserve pool disks for Disk Temperature Reports
truenas/webui pull request #7051
Opened 2022-09-02 08:28 UTC by denysbutenko

<img width="663" alt="image" src="https://user-images.githubusercontent.com/351613/188097963-fe8475a1-ba47-49ea-a930-4d530845d2b4.png">

Changes: pool related disks are preserved on reports

2022-09-02 08:28 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118004

2022-09-02 08:28 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118004

2022-09-02 12:05 UTC, AlexKarpov98 requested changes
please review my comments

2022-09-05 07:31 UTC, denysbutenko commented on src/app/pages/storage/modules/disks/utils/disks.utils.ts
> +  (['cache', 'data', 'dedup', 'log', 'spare', 'special'] as PoolTopologyCategory[]).forEach((categoryName) => {
Ok, I did some refactoring and added unit tests

2022-09-05 10:46 UTC, AlexKarpov98 approved these changes

2022-09-05 10:47 UTC, merged