NAS-117953: Add 'serializeConfig' method
truenas/webui pull request #7055
Opened 2022-09-05 06:24 UTC by bvasilenko

Fix for a bug when user clicks **Edit** and array fields are empty.

For testing, please see example in the ticket

2022-09-05 06:24 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117953

2022-09-06 11:38 UTC, RehanY147 requested changes

2022-09-06 11:38 UTC, RehanY147 commented on src/app/services/app-schema.service.ts
> +          this.serializeConfig(valueConfig, formConfig);
Not sure what this method is meant to do. Code needs to be more readable.

2022-09-08 07:14 UTC, bvasilenko commented
@RehanY147 

> Shouldn't change the array while we're traversing it

Good one. Now it returns a modified value, and there's no mutable reference arguments

> Not sure what this method is meant to do. Code needs to be more readable.

Now I've renamed the method and added javadoc-style commentary

2022-09-11 09:38 UTC, RehanY147 approved these changes
Looks good. Nice!

2022-09-11 09:38 UTC, RehanY147 commented on src/app/services/app-schema.service.ts
> +   * @param form Form group to restore keys from
form Form group

2022-09-11 09:38 UTC, RehanY147 commented on src/app/services/app-schema.service.ts
> +   * @returns Object with keys. Example: { objectList: [{ nestedList: ['test4', 'test5'] }] }
The example is the same as `@param config`

2022-09-12 07:42 UTC, merged