NAS-117298: timemaching_quota added in smb-form
truenas/webui pull request #7074
Opened 2022-09-12 20:47 UTC by AlexKarpov98

2022-09-13 12:56 UTC, undsoft requested changes
According to ticket value for `timemachine_quota` is number of bytes, so it needs to use [formatter] to show it properly.

2022-09-13 12:56 UTC, undsoft commented on src/app/pages/sharing/smb/smb-form/smb-form.component.html
> +        {{ isLoading ? 'loading' : 'noload' }}
😞

2022-09-13 12:56 UTC, undsoft commented on src/app/pages/sharing/smb/smb-form/smb-form.component.html
> +            helptextSharingSmb.placeholder_aapl_name_mangling | translate
Weird layout.

2022-09-13 12:56 UTC, undsoft commented on src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> +                  ['/'].concat([
I think previous layout was easier to read.

2022-09-15 16:30 UTC, AlexKarpov98 commented
@undsoft - Updated PR

2022-09-16 08:20 UTC, undsoft requested changes
1. Looks like not sending a value doesn't remove it.
2. I think we should also not send it (clear value) if user unticks Time Machine.

2022-09-16 08:20 UTC, undsoft commented on src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> +    timemachine_quota: [],
This probably results in type being not defined for this field. You should probably have something like:
```
timemachine_quota: [null as number]
```

2022-09-16 08:20 UTC, undsoft commented on src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> +    if (!this.timemachineQuota) {
Or just `smbShare.timemachine_quota` and getter can be removed.

2022-09-16 08:52 UTC, AlexKarpov98 commented
@undsoft  - fixed

2022-09-16 13:55 UTC, undsoft requested changes
No changes since my last review.

2022-09-17 10:12 UTC, AlexKarpov98 commented
@undsoft Please check it now :)

2022-09-17 17:46 UTC, undsoft requested changes
Same issues as during last review:
1. Once I set Time Machine Quota there is no way for me to remove it.
2. If I set Time Machine Quota, but then untick `Time Machine` checkbox, my expectation is that this removes quota when saved.

2022-09-19 20:39 UTC, AlexKarpov98 commented
@undsoft 
<img width="848" alt="Screen Shot 2022-09-19 at 23 38 59" src="https://user-images.githubusercontent.com/22980553/191112154-f8d4422a-47a0-48c4-8c90-9d01589e9538.png">
We need to set 0 manually once the value is empty (updated PR)

2022-09-20 07:59 UTC, undsoft approved these changes
Works correctly now.

2022-09-20 10:56 UTC, merged