NAS-118003: Refactor Cloud Sync Form to ix-forms
truenas/webui pull request #7076
Opened 2022-09-13 06:20 UTC by bvasilenko

2022-09-13 06:20 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118003

2022-09-14 07:03 UTC, denysbutenko requested changes
The docker image is unavailable due to merge conflict

2022-09-18 18:47 UTC, bvasilenko commented
@denysbutenko Now all remarks have been addressed

2022-09-19 12:43 UTC, denysbutenko approved these changes
![image](https://user-images.githubusercontent.com/351613/191014723-08eca779-74e1-42f5-823a-28bcfbbecb7f.png)

observed some cosmetic issues:
- icon below the transfer mode
- manage credentials link

other than that looks good

2022-09-23 05:21 UTC, merged