Adding warnings for unused disks with exported pools
truenas/webui pull request #7078
Opened 2022-09-13 14:21 UTC by RehanY147

2022-09-13 14:22 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117805

2022-09-14 14:06 UTC, undsoft requested changes
In manager selecting disk always shows warning despite the code that should prevent it. On the other hand selecting multiple disks via select all checkbox doesn't show a warning.

2022-09-14 14:06 UTC, undsoft commented on src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.ts
> +      this.unusedDisks = unusedDisks;
This is an unexpected side-effect - unusedDisks$ now has two responsibilities. 
You should remove both of these and a new loadUnusedDisks method in ngOnInit.

2022-09-14 14:06 UTC, undsoft commented on src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.ts
> +  warnAboutExportedPoolForUnusedDiskIfNeeded = (diskIdentifier: string): void => {
Same notes about extra functions, long names and template strings.

2022-09-14 14:06 UTC, undsoft commented on src/app/pages/system/bootenv/boot-pool-attach/boot-pool-attach-form.component.ts
>    dev = {
Same.

2022-09-15 09:35 UTC, RehanY147 commented
The check to not show warning is there to avoid showing warning for a disk that was already selected. If the disk is unchecked and then checked again, showing the warning again.

2022-09-16 09:06 UTC, undsoft requested changes
Replace disk dialog seems to be broken.

2022-09-18 11:36 UTC, bvasilenko approved these changes
Works good for me!

Just one minor observation: it's still possible to bypass the warning if user clicks **Suggest Layout** button:


https://user-images.githubusercontent.com/20611516/190899495-0a469d06-5a22-4511-9b6b-68bd80261fda.mp4

2022-09-23 14:49 UTC, undsoft approved these changes
👍🏻

2022-09-23 19:59 UTC, merged