NAS-110516: Add 'retention' to the details-row at snaphots page
truenas/webui pull request #7081
Opened 2022-09-14 07:17 UTC by bvasilenko

**Testing**

On **Snapshots** table, new column "Retention" should be displayed at expanded details panel

2022-09-14 07:17 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-110516

2022-09-14 12:57 UTC, undsoft requested changes
Looks good, but I think we can improve messaging here. Seems there different states for this field and we should show this to the user:
* Will be automatically destroyed at datetime by periodic snapshot task
* Is planned to be automatically destroyed at datetime.
* "Will not be destroyed automatically" for null values.

2022-09-14 12:57 UTC, undsoft commented on src/app/interfaces/zfs-snapshot.interface.ts
> +    source: string;
Enum.

2022-09-16 06:24 UTC, bvasilenko commented
@undsoft Now it has enum and improved wordings

2022-09-16 08:33 UTC, undsoft approved these changes
Looks good

2022-09-19 05:05 UTC, merged