NAS-113216: Hide 'acltype' and 'aclmode' when creating or editing first level dataset
truenas/webui pull request #7098
Opened 2022-09-18 18:13 UTC by bvasilenko

**Summary**

Removed **ACL Type** and **Mode**,  if dataset is a **_root dataset_** , as suggested by the ticket's description

2022-09-18 18:13 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-113216

2022-09-19 10:58 UTC, undsoft requested changes
I think you misunderstood the task.
Root dataset is the first dataset in the hierarchy, it's the one that is created when you add a pool and can only be edited. It is this dataset that shouldn't have Acl Type and Acl Mode fields.
Right now this is not the case. I can still edit these fields on the root dataset, but cannot edit them on first child.

2022-09-19 10:58 UTC, undsoft commented on src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
> +  isRootDataset(path: string): boolean {
we have `isRootDataset` in `dataset.utils.ts` that you can use here.

2022-09-22 06:44 UTC, bvasilenko commented
@undsoft Done! Now it uses `isRootDataset` in `dataset.utils.ts`

2022-09-22 12:21 UTC, undsoft approved these changes
Works well 👍🏻

2022-09-23 05:23 UTC, merged