NAS-118270: Seek and destroy
truenas/webui pull request #7117
Opened 2022-09-21 18:12 UTC by undsoft

Removes storage module and some other unused code.
Testing: shallow regression testing.

2022-09-21 18:13 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118270

2022-09-22 22:39 UTC, RehanY147 requested changes
Why are we removing the json translation files?

2022-09-23 14:05 UTC, undsoft commented
@RehanY147 We aren't, only some strings were removed.

2022-09-24 14:31 UTC, RehanY147 approved these changes
Looks good

2022-09-24 15:36 UTC, merged