New reasons in `failover.disabled.reasons`
truenas/webui pull request #7124
Opened 2022-09-23 17:39 UTC by yocalebo

Added 3 new reasons in PR: https://github.com/truenas/middleware/pull/9904 so adding them here.

2022-09-23 17:39 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118303

2022-09-26 12:24 UTC, AlexKarpov98 requested changes
we also need to add new translations into all .json files

2022-09-26 12:35 UTC, undsoft approved these changes
That's fine, translations will get picked up on next PR.

@yocalebo 
If you do `yarn` next time, it should install git hooks that generate translation files when you commit.

2022-09-26 12:51 UTC, yocalebo commented
> That's fine, translations will get picked up on next PR.
> 
> @yocalebo If you do `yarn` next time, it should install git hooks that generate translation files when you commit.

great to know, thanks for the tip!

2022-09-26 12:52 UTC, merged