NAS-118375: Close mobile details after delete dataset
truenas/webui pull request #7150
Opened 2022-09-30 14:33 UTC by bvasilenko

2022-09-30 14:43 UTC, undsoft requested changes
Can we do this via store instead? Like have something that clears `selectedDatasetId`. 
Feels like there are now too many ways for components to communicate with each other.

2022-10-03 05:11 UTC, bvasilenko commented
@undsoft  Now `showMobileDetails` is in the store

2022-10-03 08:00 UTC, undsoft requested changes
This feels kinda weird. Some presentational logic is in the component (media observers) and some is in the store now.
What if instead of having a separate property in the state, you do redirect and every time there is a redirect you close mobile details?

Also, would be nice to select parent dataset when child is deleted, not reset user to the root of the tree.

2022-10-03 11:18 UTC, AlexKarpov98 requested changes

2022-10-03 11:18 UTC, AlexKarpov98 commented on src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.ts
> +        this.router.navigate(['/datasets']);
Let's navigate at the end of the .subscribe

2022-10-03 11:18 UTC, AlexKarpov98 commented on src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.ts
> +  ChangeDetectionStrategy, Component, Input, OnInit,
one line should be enough I think

2022-10-03 11:18 UTC, AlexKarpov98 commented on src/app/pages/datasets/components/dataset-management/dataset-management.component.html
> +      [class.details-container-mobile]="showMobileDetails$ | async"
please follow the ordering rules 
**ixDetailsHeight** should be higher than **[class.details-container-mobile]**

2022-10-04 15:28 UTC, bvasilenko commented
@AlexKarpov98 minor improvements done to the code.
@undsoft looks like I was going wrong direction. I've reverted and pushed another solution based on the router - now it looks much better to me.

2022-10-05 10:18 UTC, undsoft approved these changes
Works okay.

2022-10-05 10:18 UTC, undsoft commented on src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.ts
> +          this.datasetStore.selectDatasetById(null);
`selectDatasetById` doesn't seem to be necessary

2022-10-06 12:44 UTC, merged