Minor improvements for Datasets module
truenas/webui pull request #7156
Opened 2022-10-03 11:30 UTC by RehanY147

2022-10-04 18:16 UTC, undsoft requested changes
1. It used to be that if you toggle switch on quotas lists and press Cancel the toggle went to the previous state. This is not the case anymore.
2. We should probably discuss order of methods as a team. My habit is to separate properties and methods and then sort them by private/public. This conflicts with an approach of having things together based on context.

2022-10-04 18:16 UTC, undsoft commented on src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-settings/dataset-capacity-settings.component.ts
> +  readonly defaultReqQuotaWarning = 80;
What's `reqquota`?

2022-10-04 18:16 UTC, undsoft commented on src/app/pages/datasets/components/dataset-quotas/dataset-quota-edit-form/dataset-quota-edit-form.component.ts
> +    + this.translate.instant(globalHelptext.human_readable.suggestion_tooltip)
Needs indentation.

2022-10-04 18:16 UTC, undsoft commented on src/app/pages/datasets/components/dataset-quotas/dataset-quota-edit-form/dataset-quota-edit-form.component.ts
> +  getGroupDataQuotaLabel(): string {
New methods are private.

2022-10-04 18:16 UTC, undsoft commented on src/app/pages/datasets/components/dataset-quotas/dataset-quota-edit-form/dataset-quota-edit-form.component.ts
> +    }
Nice.

2022-10-04 18:16 UTC, undsoft commented on src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
> +  getDeleteConfirmation(quota: DatasetQuota): Observable<boolean> {
or `confirmDeletion`

2022-10-04 18:16 UTC, undsoft commented on src/app/pages/datasets/components/delete-dataset-dialog/delete-dataset-dialog.component.ts
> +  tryDeletingDataset(): Observable<boolean> {
I think `try` is a bit misleading here. I mean I get that in context of `onDelete` method we are trying, but there is nothing that would explain `try` in the method itself. I'd go with just `deleteDataset`.

2022-10-04 19:49 UTC, RehanY147 commented
> We should probably discuss order of methods as a team. My habit is to separate properties and methods and then sort them by private/public. This conflicts with an approach of having things together based on context.
I generally agree with that. What I tried here was just put methods right after the first time they were used so the flow of the code is natural. That way you don't have to scroll around to find a method from where it was used.

2022-10-06 14:33 UTC, undsoft requested changes
Toggle in user quotas still doesn't work correctly.
It switches and if you press Cancel, it stays in new position, even though it's incorrect.

2022-10-08 10:44 UTC, undsoft approved these changes
👍🏻

2022-10-09 02:50 UTC, merged