NAS-118454 / 22.12 / ACL manager after dataset creation fix
truenas/webui pull request #7178
Opened 2022-10-07 12:53 UTC by AlexKarpov98

Now breadcrumbs are fixed and navigation works.
Updated /mnt string to CONST aswell in this commit. (all matches now)

2022-10-07 12:53 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118454

2022-10-07 12:54 UTC, AlexKarpov98 commented
@undsoft I'am sorry for pushing "mnt" in this commit

2022-10-07 17:55 UTC, undsoft requested changes
Redirect mostly works okay, just need to bring back the `homeShare` param.

I don't know if replacing `/mnt` with a constant provides value in tests. I mean, it's used in tests as specific example of a path. It is not meant to be easily changeable. It's like extracting "John" into a constant.
We can keep this change I suppose.

2022-10-07 17:55 UTC, undsoft commented on src/app/services/route-parts/route-parts.service.ts
> +      if (title === 'Datasets') {
This is pretty bad. You are hardcoding specific strings in a service that should not know anything about datasets or storage.

2022-10-07 17:55 UTC, undsoft commented on src/app/pages/sharing/smb/smb-form/smb-form.component.spec.ts
> +      ['datasets', datasetId, 'permissions', 'acl'],
I believe `homeShare` needs to be preserved.

2022-10-10 16:57 UTC, undsoft requested changes
I found an issue. It's probably not a regression as I don't see anything in the code that would cause it, but on the other hand I can only reproduce it on localhost.
1. Connect to m40.
2. Go to shares -> click Edit permissions next to `x` SMB share.
3. If you don't see the error, reload and keep reloading until the error appears.

Would be good to fix it here if not too hard. Otherwise a new ticket can be created.

2022-10-11 09:06 UTC, undsoft commented
@AlexKarpov98 
Reproduction steps I've given you were probably incorrect. Try creating a SMB share with Home Share enabled.

https://user-images.githubusercontent.com/1481270/195047862-0ff69f2a-2ba1-414a-87b1-fa0834e473e9.mov

2022-10-12 11:12 UTC, AlexKarpov98 commented
Gonna make another PR to **release/22.12-BETA.2**

2022-10-12 11:12 UTC, closed without merging