NAS-118472: Display buckets after S3 credentials are selected
truenas/webui pull request #7183
Opened 2022-10-09 19:12 UTC by bvasilenko

Testing:

1. Create AWS S3 credential at **Credentials -> Backup Credentials** make sure you set proper permissions for your credentials to retrieve list of buckets from your S3 

2. **Data Protection -> Cloud Sync Tasks -> Add** , select your S3 credential

3.  Open **Bucket** dropdown

      **Expected result:** options of **Bucket** contains list of buckets from your S3

2022-10-09 19:12 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118472

2022-10-10 12:04 UTC, AlexKarpov98 requested changes
looks good, but fix naming please (**buckets** & **bucket**)

2022-10-11 05:15 UTC, bvasilenko commented
@AlexKarpov98 

> looks good, but fix naming please (**buckets** & **bucket**)

done!

2022-10-11 09:44 UTC, AlexKarpov98 approved these changes

2022-10-11 18:52 UTC, merged

2022-10-13 15:18 UTC, undsoft commented
backport