NAS-118451 / 22.12 / - Resets 'Transfer Mode' to COPY after changing 'Direction'
truenas/webui pull request #7186
Opened 2022-10-10 14:47 UTC by Raz-Dva

Data Protection -> Cloud Sync Tasks -> Add
Changing the 'Direction'(PUSH, PULL ) should resets the Transfer Mode to COPY.
'Transfer Mode' should be saved after the change.

2022-10-10 14:47 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118451

2022-10-14 11:49 UTC, undsoft requested changes
See comment in ticket.

2022-10-14 13:20 UTC, Raz-Dva commented on src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
> +    this.form.controls.direction.valueChanges.pipe(
Added function resetTransferMode().

2022-10-14 18:33 UTC, undsoft approved these changes
This should do it.
Make sure to also remove unused strings from the helptext file before merging.

2022-10-16 19:46 UTC, merged