Update uk.json
truenas/webui pull request #7194
Opened 2022-10-11 20:08 UTC by Balasarko

more clear, bugs fixed

2022-10-12 10:25 UTC, AlexKarpov98 requested changes
Thanks for some uk.json gaps catches :)
Please, have a look at my comments and fix them.

2022-10-12 10:56 UTC, Balasarko commented on src/assets/i18n/uk.json
> +  "Check the box for full upgrade. Leave unchecked to download only.": "Встановіть для повного оновлення. Залиште знятим лише для завантажування.",
Погоджуюсь

2022-10-12 10:58 UTC, Balasarko commented on src/assets/i18n/uk.json
> +  "Local User Upload Bandwidth: ": "Локальна пр-кна смуга вивантаження користувача:",
пр-кна - пропускна, не впевнений чи добре видно в інтерфейсі. Щодо "ємність" - то це значення не пояснює добре контекст...

2022-10-12 10:59 UTC, Balasarko commented on src/assets/i18n/uk.json
> +  "Locality": "Місцевість",
Там двічі Місцезнаходження. Location також.

2022-10-12 19:28 UTC, AlexKarpov98 commented on src/assets/i18n/uk.json
> +  "Locality": "Місцевість",
@Balasarko - можна зразу скріном?

2022-10-12 19:29 UTC, AlexKarpov98 commented on src/assets/i18n/uk.json
> +  "Local User Upload Bandwidth: ": "Локальна пр-кна смуга вивантаження користувача:",
залежить від контексту, треба подивитись, було б добре зробити скіншот :)

2022-10-17 12:59 UTC, AlexKarpov98 commented
Closing due to inactivity

2022-10-17 12:59 UTC, closed without merging