NAS-118517: fix: CalledProcessError dialog appears when I open /ui/storage page
truenas/webui pull request #7223
Opened 2022-10-18 15:31 UTC by bvasilenko

2022-10-18 15:31 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118517

2022-10-22 04:21 UTC, bvasilenko commented
@undsoft I've updated the code to filter out particular error (CalledProcessError)

2022-10-24 12:27 UTC, undsoft requested changes
That's not what I meant. There are several network requests in this file. Some of these requests may fail with `CalledProcessError` and this will be a valid error that we may want to show to user.
Instead we only want to silence errors for getting disk temperatures.

2022-10-26 11:10 UTC, undsoft approved these changes
Looks good.

2022-10-26 11:10 UTC, merged