NAS-118545 / 22.12-RC.1 / Make Dataset Space Management chart smaller
truenas/webui pull request #7229
Opened 2022-10-20 06:18 UTC by AlexKarpov98

So, in result the chart & card are more tight and smaller now.

Before:
<img width="336" alt="Screen Shot 2022-10-20 at 09 12 02" src="https://user-images.githubusercontent.com/22980553/196870371-b19d5d65-0ec4-4a7c-bd26-43f25a72c680.png">

After: 
<img width="334" alt="Screen Shot 2022-10-20 at 09 11 49" src="https://user-images.githubusercontent.com/22980553/196870401-ed50e47c-fe9b-4fd6-a053-7a2297c462aa.png">

___

Before: 
<img width="375" alt="Screen Shot 2022-10-20 at 09 12 11" src="https://user-images.githubusercontent.com/22980553/196870438-ff40d516-a6fe-4206-bf2f-c3e9ba1e0498.png">

After: 
<img width="351" alt="Screen Shot 2022-10-20 at 09 11 34" src="https://user-images.githubusercontent.com/22980553/196870472-2522ea17-9bb9-42d3-8269-8116f9d8b298.png">

2022-10-20 06:50 UTC, undsoft requested changes
Would there be enough space to try to always use horizontal layout?

2022-10-21 09:33 UTC, undsoft approved these changes
Generally looks okay.
On some resolutions however legend may get too close to the right border - need additional margins and can reduce margins on the left between legend and donut.
<img width="373" alt="Снимок экрана 2022-10-21 в 11 30 40" src="https://user-images.githubusercontent.com/1481270/197164144-3b27d98d-69c8-484b-b1ac-60a381fd47de.png">

2022-10-21 12:25 UTC, AlexKarpov98 commented
@undsoft  - please have a look at it now :)

2022-10-24 11:59 UTC, undsoft approved these changes
Looks good.

2022-10-24 12:56 UTC, merged