APPS: Add bulk upgrade action
truenas/webui pull request #7257
Opened 2022-10-26 17:48 UTC by denysbutenko

Testing requires a few apps that have updates.

Or use a mock response for `chart.release.query` to see apps with updates and failures while upgrading.
```
midclt call test.set_mock chart.release.query '{"return_value": [{"name":"test-pihole","version":1,"namespace":"ix-test-pihole","id":"test-pihole","catalog":"OFFICIAL","catalog_train":"charts","path":"/mnt/tank/ix-applications/releases/test-pihole","dataset":"tank/ix-applications/releases/test-pihole","status":"ACTIVE","history":{},"update_available":true,"human_version":"2022.10_1.0.7","human_latest_version":"2022.10_1.0.7","pod_status":{"desired":1,"available":1},"used_ports":[],"chart_metadata":{"icon":"https://github.com/pi-hole/graphics/raw/master/Vortex/Vortex_Vertical_wordmark_lightmode.png?raw=true"},"container_images_update_available":false,"item_update_available":true},{"name":"test-nextcloud","version":1,"namespace":"ix-test-nextcloud","id":"test-nextcloud","catalog":"OFFICIAL","catalog_train":"charts","path":"/mnt/tank/ix-applications/releases/test-nextcloud","dataset":"tank/ix-applications/releases/test-nextcloud","status":"ACTIVE","history":{},"update_available":false,"human_version":"25_1.6.15","human_latest_version":"25_1.6.15","pod_status":{"desired":2,"available":2},"used_ports":[],"chart_metadata":{"icon":"https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg"},"container_images_update_available":true,"item_update_available":true},{"name":"true-nextcloud","version":1,"namespace":"ix-true-nextcloud","id":"true-nextcloud","catalog":"TRUECHARTS","catalog_train":"stable","path":"/mnt/tank/ix-applications/releases/true-nextcloud","dataset":"tank/ix-applications/releases/true-nextcloud","status":"ACTIVE","history":{},"update_available":true,"human_version":"24.0.6_15.3.35","human_latest_version":"24.0.6_15.3.35","pod_status":{"desired":1,"available":1},"used_ports":[],"chart_metadata":{"icon":"https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg"},"container_images_update_available":false,"item_update_available":true},{"name":"true-pihole","version":1,"namespace":"ix-true-pihole","id":"true-pihole","catalog":"OFFICIAL","catalog_train":"charts","path":"/mnt/tank/ix-applications/releases/true-pihole","dataset":"tank/ix-applications/releases/true-pihole","status":"ACTIVE","history":{},"update_available":false,"human_version":"2022.10_1.0.7","human_latest_version":"2022.10_1.0.7","pod_status":{"desired":4,"available":4},"used_ports":[],"chart_metadata":{"icon":"https://github.com/pi-hole/graphics/raw/master/Vortex/Vortex_Vertical_wordmark_lightmode.png?raw=true"},"container_images_update_available":true,"item_update_available":true}]}'
```

To see the happy journey, additionally need to mock `chart.release.upgrade` response:

```
midclt call test.set_mock chart.release.upgrade '{"return_value": {"container_images_to_update":{},"changelog":"<h1>Changelog</h1>\n<h2><a href=\"https://github.com/truecharts/charts/compare/nextcloud-15.3.34...nextcloud-15.3.35\">nextcloud-15.3.35</a> (2022-10-25)</h2>\n<h3>Chore</h3>\n<ul>\n<li>Auto-update chart README [skip ci]</li>\n<li>update helm general non-major</li>\n</ul>\n<h2><a href=\"https://github.com/truecharts/charts/compare/nextcloud-15.3.33...nextcloud-15.3.34\">nextcloud-15.3.34</a> (2022-10-25)</h2>\n<h3>Chore</h3>\n<ul>\n<li>Auto-update chart README [skip ci]</li>\n<li>update helm general non-major (<a href=\"https://github.com/truecharts/charts/issues/4182\">#4182</a>)</li>\n</ul>\n<h2><a href=\"https://github.com/truecharts/charts/compare/nextcloud-15.3.32...nextcloud-15.3.33\">nextcloud-15.3.33</a> (2022-10-25)</h2>\n<h3>Chore</h3>\n<ul>\n<li>Auto-update chart README [skip ci]</li>\n<li>update docker general non-major (<a href=\"https://github.com/truecharts/charts/issues/4181\">#4181</a>)</li>\n</ul>\n<h2><a href=\"https://github.com/truecharts/charts/compare/uptimerobot-prometheus-4.0.40...prometheus-4.0.110\">prometheus-4.0.110</a> (2022-10-21)</h2>\n<h3>Chore</h3>\n<ul>\n<li>Auto-update chart README [skip ci]</li>\n<li>update docker general non-major (<a href=\"https://github.com/truecharts/charts/issues/4139\">#4139</a>)</li>\n</ul>\n<h2><a href=\"https://github.com/truecharts/charts/compare/prometheus-4.0.108...prometheus-4.0.109\">prometheus-4.0.109</a> (2022-10-19)</h2>\n<h3>Chore</h3>\n<ul>\n<li>Auto-update chart README [skip ci]</li>\n<li>update helm general non-major (<a href=\"https://github.com/truecharts/charts/issues/4122\">#4122</a>)</li>\n<li>update docker general non-major (<a href=\"https://github.com/truecharts/charts/issues/4128\">#4128</a>)</li>\n</ul>\n<h2><a href=\"https://github.com/truecharts/charts/compare/prometheus-4.0.107...prometheus-4.0.108\">prometheus-4.0.108</a> (2022-10-18)</h2>\n<h3>Chore</h3>\n<ul>\n<li>Auto-update chart README [skip ci]</li>\n<li>update docker general non-major (<a href=\"https://github.com/truecharts/charts/issues/4120\">#4120</a>)</li>\n</ul>\n<h2><a href=\"https://github.com/truecharts/charts/compare/prometheus-4.0.106...prometheus-4.0.107\">prometheus-4.0.107</a> (2022-10-17)</h2>\n<h3>Chore</h3>\n<ul>\n<li>Auto-update chart README [skip ci]</li>\n<li>update docker general non-major (<a href=\"https://github.com/truecharts/charts/issues/4119\">#4119</a>)</li>\n</ul>\n<h2><a href=\"https://github.com/truecharts/charts/compare/prometheus-4.0.105...prometheus-4.0.106\">prometheus-4.0.106</a> (2022-10-16)</h2>\n<h3>Chore</h3>\n<ul>\n<li>Auto-update chart README [skip ci]</li>\n<li>update docker general non-major (<a href=\"https://github.com/truecharts/charts/issues/4108\">#4108</a>)</li>\n</ul>\n<h2><a href=\"https://github.com/truecharts/charts/compare/prometheus-4.0.104...prometheus-4.0.105\">prometheus-4.0.105</a> (2022-10-14)</h2>\n<h3>Chore</h3>\n<ul>\n<li>Auto-update chart README [skip ci]</li>\n<li>update docker general non-major (<a href=\"https://github.com/truecharts/charts/issues/4084\">#4084</a>)</li>\n</ul>\n<h2><a href=\"https://github.com/truecharts/charts/compare/prometheus-4.0.103...prometheus-4.0.104\">prometheus-4.0.104</a> (2022-10-12)</h2>\n<h3>Chore</h3>","available_versions_for_upgrade":[{"version":"15.3.35","human_version":"24.0.6_15.3.35"},{"version":"15.3.34","human_version":"24.0.6_15.3.34"}],"item_update_available":true,"image_update_available":false,"latest_version":"15.3.35","upgrade_version":"15.3.35","latest_human_version":"24.0.6_15.3.35","upgrade_human_version":"24.0.6_15.3.35"}}'
```

2022-10-26 17:48 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-111965

2022-11-02 12:04 UTC, AlexKarpov98 commented on src/app/pages/applications/chart-releases/chart-releases.component.ts
>    private dialogRef: MatDialogRef<EntityJobComponent>;
can we refactor this .ts file to remove **this.dialogRef** and use const **dialogRef** instead?

2022-11-03 13:43 UTC, undsoft requested changes
It generally looks good. 
Some things that I've noticed:
1. When I have mouse connected, there is scrollbar in the accordion.
2. I've started an update and then opened an accordion. It showed me a weird progress bar on top.
<img width="672" alt="Снимок экрана 2022-11-03 в 14 31 16" src="https://user-images.githubusercontent.com/1481270/199736135-db7f9ff4-4a1b-4efd-a6c0-eea8a4ecec8b.png">

3. It seems like update status doesn't update until all apps finish updates. Would be better to show status app by app as it is coming in.
4. If possible, it would be good to show status more prominently when I start the upgrade. Like I've started the upgrade, but all I see is spinners. I have to open job manager in another tab to see % reported.
Once one of the updates failed, I had to know to hover over the icon to see the error.
Would be good to show this instead of summary in the accordion once update starts.

2022-11-07 13:56 UTC, denysbutenko commented on src/app/pages/applications/dialogs/chart-bulk-upgrade/chart-bulk-upgrade.component.ts
> +  originalOrder(): number {
No, getting errors with text: `Cannot convert undefined or null to object`

2022-11-08 08:18 UTC, denysbutenko commented
> * It seems like update status doesn't update until all apps finish updates. Would be better to show status app by app as it is coming in.
> * If possible, it would be good to show status more prominently when I start the upgrade. Like I've started the upgrade, but all I see is spinners. I have to open job manager in another tab to see % reported.
>   Once one of the updates failed, I had to know to hover over the icon to see the error.
>   Would be good to show this instead of summary in the accordion once update starts.

3. Perhaps related to how `core.bulk` handle these requests.
4. Displaying the `core.bulk` job does not provide as much information as a single one.
![image](https://user-images.githubusercontent.com/351613/200511169-837bfd1d-03e0-4b72-bf1e-c5e2318b2e19.png)


Looking for own rxjs solution to handle bulk requests.

2022-11-10 18:23 UTC, undsoft approved these changes
Looks good, but if we could show minimize animation and pre-open task manager like you did somewhere else before, that would be even cooler.

2022-11-10 22:13 UTC, AlexKarpov98 approved these changes
That's working good, nice job!

2022-11-12 13:35 UTC, merged