NAS-118777: Default cloudsync credential name to provider name
truenas/webui pull request #7262
Opened 2022-10-28 08:55 UTC by undsoft

Go to Credentials -> Backup credentials. 
When adding a new cloud credential the order of fields is different and name will default to provider name until user interacts with Name control.

2022-10-28 08:55 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118777

2022-10-31 06:44 UTC, denysbutenko requested changes
It doesn't work on the initial load. I see two empty fields, provider options are loaded, and provider input is set to the `Storj iX` value, but the `Name` field is still empty. If I change the provider it works well.

2022-10-31 09:19 UTC, undsoft commented
Fixed.

2022-10-31 09:32 UTC, denysbutenko approved these changes
Looks good 👍🏻

2022-10-31 11:01 UTC, merged