WIP | NAS-116577: Sentry updates
truenas/webui pull request #7302
Opened 2022-11-10 15:33 UTC by AlexKarpov98

Currently Exploring a way to extend default error extractor.
Updated one package to avoid this error: **[(...).transition is not a function]**

2022-11-10 15:33 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-116577

2022-11-14 10:56 UTC, undsoft requested changes
1. Second argument in `extractor` is the `defaultExtractor`. You call the default extractor and then if it fails, do something else.
2. It would be good to try to extract error message, not just put in JSON, as it may be huge with stacktrace and other data.
See `EntityUtils.handleWsError` and `EntityUtils.errorReport`.

2022-11-18 13:29 UTC, AlexKarpov98 commented
would be good to check how much new default messages will we get 
`iXsystems [sentry] default handled error`

2022-11-18 21:17 UTC, undsoft requested changes
`error.message` is already extracted by default extractor. Not sure what `error.name` is.

You need to use custom extractor to extract error messages that we may get from middleware. You can look at `WebsocketError` and `Job` for relevant fields and at `EntityUtils` for how errors are currently being processed.

2022-11-29 13:23 UTC, undsoft commented
Bump.

2022-11-30 18:42 UTC, undsoft approved these changes
Looks good.

2022-11-30 18:42 UTC, undsoft commented on src/app/helpers/sentry-custom-extractor.helper.ts
> +  const errorReportValue = errorReport(errorCandidate as WebsocketError);
`as WebsocketError | Job`

2022-11-30 18:42 UTC, undsoft commented on src/app/helpers/sentry-custom-extractor.helper.ts
> +const errorReport = (err: WebsocketError | Job): string | void => {
Isn't really `errorReport`, morel like `extractApiError`

2022-11-30 18:42 UTC, merged

2022-11-30 18:42 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-116577 is targeted to the following versions which have not received their corresponding PRs: 22.12.1

2022-11-30 18:43 UTC, undsoft commented
Would be good to fix comments as well. @AlexKarpov98

2022-11-30 21:19 UTC, AlexKarpov98 commented
@undsoft, yes, sorry, auto push triggered after approval.
Changes are here now: https://github.com/truenas/webui/pull/7403