NAS-118937: Add dispatch `loadHaStatus()`
truenas/webui pull request #7327
Opened 2022-11-16 09:15 UTC by bvasilenko

**Summary**

Forgotten call `dispatch()` at `loadHaStatus()`. In my previous PR I didn't notice that it wasn't called after user was logged in. 

**Testing**

For regular server the button should be displayed because it is not HA. 

If you have (or simulate) HA server, then the button should not be displayed.

2022-11-16 09:16 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118937

2022-11-17 03:38 UTC, denysbutenko commented on src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
> +    this.store$.select(selectHaStatus).pipe(filter(Boolean), untilDestroyed(this)).subscribe((haStatus) => {
```diff
- *ngIf="showImportData"
+ *ngIf="showImportButton$ | async"
```

```diff
- hasHa: boolean;
- get showImportData(): boolean {}
- loadHaStatus(): void {}
+  /**
+   * Hidden on HA systems.
+   * Issues: fenced reservations and the potential to cause a kernel panic, as well as +an alert being raised.
+   */
+  showImportButton$: Observable<boolean> = this.store$
+    .select(selectHaStatus)
+    .pipe(
+      filter(Boolean),
+      map((haStatus) => !haStatus.hasHa),
+    );
```

2022-11-17 09:20 UTC, bvasilenko commented
> Technically speaking this action should already be dispatched: `admin-layout` dispatches `adminUiInitialized` this loads system info in `SystemInfoEffects` and if system has an HA license `loadHaStatus` is dispatched.
> 
> Please check what's going on there, maybe there is a mistake there.

@undsoft 
Ok, now the `adminUiInitialized` will trigger the `loadHaStatus`. And I've rolled back direct call to `dispatch(loadHaStatus)`.

2022-11-17 11:07 UTC, undsoft commented on src/app/store/system-info/system-info.effects.ts
> +    ofType(loadHaStatus, haSettingsUpdated, passiveNodeReplaced, adminUiInitialized),
If we are always going to load HA status on admin ui init, we should remove `loadHaStatus` being dispatched a couple lines above.

2022-11-17 11:13 UTC, undsoft requested changes
So, I've tried it with one of the machines from Jenkins that doesn't have HA and I don't see the button.

2022-11-17 19:21 UTC, bvasilenko commented
> So, I've tried it with one of the machines from Jenkins that doesn't have HA and I don't see the button.

@undsoft 
Ah, I finally noticed the missing condition checks, and this explains why it was working for one box, but not for the other. Now it should work correctly on any box.

2022-11-18 11:01 UTC, undsoft approved these changes
In the future we probably need to streamline how we work with HA status in one central store, this is quite complicated.
But for the purposes of this ticket, the button is there and works okay.

2022-11-20 15:32 UTC, merged