NAS-119101: New process for first UI login when root password is not set up
truenas/webui pull request #7385
Opened 2022-11-28 12:39 UTC by AlexKarpov98

2022-11-28 12:40 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119101

2022-11-29 11:45 UTC, undsoft requested changes
Well, the code looks okay and it submits correct values, but I couldn't find a machine that had 'user.setup_local_administrator'. 
Latest nightly gives me an error that this method is not found.

Also, in English radio buttons go in one row. I like it better how they look in your screenshot.
<img width="659" alt="Снимок экрана 2022-11-29 в 12 39 20" src="https://user-images.githubusercontent.com/1481270/204520619-1513076d-f744-4fb3-b86b-9c753f5e93fa.png">

2022-11-29 11:50 UTC, AlexKarpov98 commented
@undsoft 
Vladimir Vinogradenko
  [13:48]
Also we have not merged this yet, you can ping 
[@Andrew Walker]
 so he makes another PR review round on https://github.com/truenas/middleware/pull/10117

2022-12-01 12:09 UTC, undsoft approved these changes
Works well on latest middleware.

2022-12-02 08:15 UTC, merged