NAS-117633: Improving event subscriptions
truenas/webui pull request #7461
Opened 2022-12-12 12:23 UTC by RehanY147

2022-12-12 12:24 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117633

2022-12-13 13:13 UTC, undsoft requested changes
I think we can still simply syntax.
Current approach would require a Subject every time you want to use subscription. If you take a look at something like `AlertEffects`, it would add quite a bit of boilerplate there for both subscribing and unsubscribing.
Perhaps we could just return an observable from `newSub` and unsubscribe from middleware when there are no more subscriptions to this observable.

2022-12-19 11:07 UTC, RehanY147 commented
This ticket requires https://ixsystems.atlassian.net/browse/NAS-119462 to be done before it can be tested 100%. It works generally but fails when there's a case of removing an event using the deprecated `cleared` flag from middleware.

Test for regressions to even subscriptions in different places. Also check testing methodology.

2022-12-25 11:19 UTC, undsoft requested changes
Something doesn't work with events, not sure if middleware or UI.
On a fresh instance from Jenkins, I don't seem to be getting any events whether old or new.
On m40, old code has events coming from middleware, but new one doesn't.

I am also happy to abandon this PR if we are going to get the same functionality in WebsocketService2.

2022-12-25 11:19 UTC, undsoft commented on src/app/services/ws.service.ts
> +// type ApiSubscriptionDirectory = ValuesType<ApiEventDirectory | LogsEventDirectory>['response'];
Dead comment.

2022-12-25 11:19 UTC, undsoft commented on src/app/services/ws.service.ts
> +    return 'error' in data && data.error.error === 13;
Don't forget to change error code here to what's in master.

2022-12-25 11:19 UTC, undsoft commented on src/app/services/ws.service.ts
> +  newSub<K extends keyof ApiEventDirectory>(apiMethod: K | string): Observable<ApiEvent<ApiEventDirectory[K]['response'] & LogsEventDirectory[K]['response']>> {
newSub can be renamed back to `subscribe` since there are no *old* subs anyway.

2022-12-26 09:14 UTC, RehanY147 commented
Implementing these changes in `WebSocketService2`

2022-12-26 09:14 UTC, closed without merging