Nas-119049 - Fixed LDAP slide-in is sometimes blank
truenas/webui pull request #7483
Opened 2022-12-19 13:47 UTC by Raz-Dva

Go to Credentials ->  Configure Active Directory 

![image](https://user-images.githubusercontent.com/22006748/208439661-b11c9acf-6d01-420d-b432-0c7c5b2fc49b.png)

2022-12-19 13:47 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119049

2022-12-19 19:33 UTC, undsoft requested changes
I don't really understand what these changes do or how they should help. Can you explain?

2022-12-19 19:47 UTC, Raz-Dva commented
If click a row in Сertificate Signing Requests and create an ACME certificate(button), the slide is blank. 
The reason for this 
`  onCreateAcmePressed(): void {
    this.slideInService.close();
    const acmeForm = this.slideInService.open(CertificateAcmeAddComponent);
  }`
The code in setTimeout (`this.slideInBody.clear()`) will run after the component instance is created in the `open` method

2022-12-26 21:43 UTC, undsoft approved these changes
I now see what you're trying to do. Make sense and good catch.
It's a good idea to also clear timeout if it's set in `ngOnDestroy`.

2022-12-26 21:43 UTC, undsoft commented on src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.ts
> +    this.clearBodyExpected = true;
Let's rename to `wasBodyCleared` instead.

2022-12-26 21:43 UTC, undsoft commented on src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.ts
> +  timeOutOfClear: any;
There is a `Timeout` type in our project for this.

2022-12-28 16:21 UTC, merged