Nas-119412 Removed popup after getting logs received
truenas/webui pull request #7494
Opened 2022-12-22 12:06 UTC by Raz-Dva

Go to Applications -> Choose Logs -> Pod Logs
Click Reconnect for getting logs

2022-12-22 12:06 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119412

2022-12-27 14:19 UTC, RehanY147 reviewed
Not sure how to test for this. Need more info. @Raz-Dva

2022-12-28 10:30 UTC, RehanY147 requested changes
We should show a different message if the call is failing or show a loading indicator if the call is taking too long to respond. Showing nothing is not a better solution than the original bug.

2023-01-03 12:28 UTC, Raz-Dva commented
Added text and spinner.

![spinnerLG](https://user-images.githubusercontent.com/22006748/210357360-ceca1056-b39a-407e-91dd-5a78ee12915c.png)

2023-01-05 21:49 UTC, RehanY147 requested changes
If we get no logs, meaning there's no strings returned from the middleware, we should show muted text `<Empty>` or `<No logs>`.

2023-01-10 09:18 UTC, RehanY147 requested changes
https://user-images.githubusercontent.com/24204846/211510859-803d31d6-e92a-4275-94c1-7622d375e3cf.mov

I still see a blank page when there's no logs to show. What I meant was that not only show <Empty> or <No logs> when the request is loading but until you get an actual string from middleware to show in the blank page, we want to show the user that the ui didn't crash. There's just nothing to show. So, until middleware responds with at least one character/line of logs, show <Empty> in the blank page.

2023-01-20 09:29 UTC, RehanY147 requested changes

2023-01-20 09:29 UTC, RehanY147 commented on src/app/pages/apps-old/pod-logs/pod-logs.component.html
> +      <span  class="no-logs">{{ 'No logs' }}</span>
You should instead do something like
`<div *ngIf="isLoadingPodLogs">...show loading spinner....</div> <div *ngIf="!isLoadingPodLogs"> <div *ngIf="!podLogs.length">{{ 'No logs yet' | translate }}</div><div *ngIf="podLogs.length">...show logs...</div></div>`

2023-01-20 09:29 UTC, RehanY147 commented on src/app/pages/apps-old/pod-logs/pod-logs.component.ts
> +  areLoadingPodLogs = false;
`isLoadingPodLogs`

2023-01-23 11:09 UTC, RehanY147 approved these changes
`No logs to show` or `No logs yet` would be a better message. But looks good.

2023-01-23 12:19 UTC, merged