Manual disk selection layout
truenas/webui pull request #7533
Opened 2023-01-01 12:02 UTC by RehanY147

2023-01-01 12:03 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119477

2023-01-02 11:48 UTC, undsoft requested changes
Needs more CSS work to make it look like in the designs.

2023-01-03 20:40 UTC, undsoft requested changes
It's closer, but there are some things that can be improved.
I would recommend this extension https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=en
You can add designs, set scale to something like 0.54 and compare different elements.
Common elements like inputs and buttons don't have to be exactly 1 to 1, but new elements can be closer to designs.

Among other things to fix:
* Dark backdrop is missing.
* Enclosure icon is too big.
* Disk icon is too wide.
* Vdev corners shouldn't be rounded.
* Colors look different?
* etc.

2023-01-10 13:50 UTC, dszidi commented
For reference here is what the mockup had for the disk icons.

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/29865743/211565809-ba1adf5e-ae69-42fa-ad81-16f1d27a96dc.png">
The background colors are off for the `.identifier-container` and `.size-container` The color used in the mockup is #575757

Instead of listing all the things that are off with the icon, I think you might save yourself a lot of hassle if you just used the svg as the disk icon component template. [Angular allows this](https://angular.io/guide/svg-in-templates) and you can use your usual interpolations and `ngIf` type tricks in the markup.

There isn't an svg of just the disk icon component yet in the webui designs repo. I'll add it real quick and give you a link in slack

2023-01-14 19:21 UTC, undsoft approved these changes
Looks pretty good. I would try larger width and smaller text for `RaidZ2 / 24 Tib Est. Usable Capacity` text, because at least on my resolution vdevs and text wraps.

2023-01-14 19:21 UTC, undsoft commented on src/app/pages/storage/modules/pool-manager/components/disk-icon/disk-icon.component.ts
> +    @Input() identifier: string;
Indentation is off, also needs `ChangeDetection.OnPush`.

2023-01-14 19:21 UTC, undsoft commented on src/app/pages/storage/modules/pool-manager/components/disk-info/disk-info.component.html
> +        <strong class="title">Slot:</strong> {{ slot }}
Let's add translate pipe now.

2023-01-14 19:21 UTC, undsoft commented on src/app/pages/storage/modules/pool-manager/components/disk-info/disk-info.component.ts
> +    @Input() slot: number;
Same about indentation and `OnPush`.

2023-01-16 10:41 UTC, merged