NAS-120049: Adding sudo fields to replication and connection forms
truenas/webui pull request #7651
Opened 2023-01-29 13:16 UTC by undsoft

Adds new field to Advanced replication form and to an SSH connection form in automatic mode, when username is not root.
Testing requires latest Bluefin.

2023-01-29 13:16 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120049

2023-01-29 13:17 UTC, undsoft commented
@themylogin Please take a look at wording. I also didn't add this checkbox to a replication wizard. Not sure if we need it there, feels too technical. Perhaps we can make it easier on the user somehow.

2023-01-29 13:57 UTC, themylogin requested changes

2023-01-29 13:57 UTC, themylogin commented on src/app/helptext/data-protection/replication/replication-wizard.ts
> +  sudo_tooltip: T('Controls whether the user used for SSH/SSH+NETCAT replication should use sudo to execute zfs commands on the remote host.\
```suggestion
  sudo_tooltip: T('Controls whether the user used for SSH/SSH+NETCAT replication will have passwordless sudo enabled to execute zfs commands on the remote host.\
```

2023-01-29 13:57 UTC, themylogin commented on src/app/pages/credentials/backup-credentials/ssh-connection-form/ssh-connection-form.component.html
> +          [label]="'Allow sudo zfs commands with no password' | translate"
```suggestion
          [label]="'Enable passwordless sudo for zfs commands' | translate"
```

2023-01-30 15:13 UTC, denysbutenko approved these changes
![image](https://user-images.githubusercontent.com/351613/215513196-14a1b995-0433-497b-9362-1b63f293a204.png)

![image](https://user-images.githubusercontent.com/351613/215513137-ee7d534b-93fa-42cd-8941-df2ea7c1e576.png)

Wonder if zfs needs to be uppercased. It looks good.

2023-01-30 16:17 UTC, merged