NAS-120076: Unable to edit an App
truenas/webui pull request #7683
Opened 2023-02-02 22:40 UTC by AlexKarpov98

2023-02-02 22:41 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120076

2023-02-06 08:03 UTC, RehanY147 requested changes
The way you've described the problem, it makes me think we should investigate why `undefined` was received. That may be another related bug that needs fixing.

2023-02-06 09:36 UTC, AlexKarpov98 commented
@RehanY147 
added check for non empty value, so it will not send null or undefined anymore.
As well added **console.error()** statement, to see errors in console for Apps.

2023-02-06 09:39 UTC, RehanY147 approved these changes

2023-02-06 10:45 UTC, merged