NAS-120126 / 23.10 / Reinit SigninComponent after connect
truenas/webui pull request #7695
Opened 2023-02-06 09:01 UTC by bvasilenko

**Testing**

Please see ticket

Note: fix for Bluefin is coming soon in a separate PR

2023-02-06 09:01 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120126

2023-02-06 13:04 UTC, undsoft requested changes
After resetting config, I got to signin form and it got rendered correctly.
Then after I entered new password and submitted, I got to Reset config screen again.
Config got reset again and I was back to signin form.
You probably need to add `skipLocationChange` on reset config button.

2023-02-07 13:43 UTC, bvasilenko commented
Fixed an issue caused by the updates made to `master`, now it should work as expected

2023-02-08 11:21 UTC, undsoft approved these changes
Looks good.

2023-02-08 11:21 UTC, merged