NAS-120279: NAS-117934: Generate token periodically
truenas/webui pull request #7731
Opened 2023-02-09 19:04 UTC by RehanY147

Ticket description has an explanation of the bug

2023-02-09 19:04 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120279

2023-02-09 19:08 UTC, undsoft commented
Please note that we've recently added a feature where we log user out after certain period of inactivity. https://github.com/truenas/webui/pull/7667
We need to make sure during testing that that functionality still works.

2023-02-10 11:27 UTC, undsoft requested changes
Does not build.

2023-02-10 16:10 UTC, dszidi requested changes
Would be nice if there was a spec file for auth.service that makes sure things like the token regeneration works.

2023-02-12 12:19 UTC, RehanY147 commented
@undsoft It's building for me. I can login and use the UI normally. Can you help me reproduce that issue?

2023-02-12 12:20 UTC, RehanY147 commented
@dszidi NAS-120307 will add tests for the AuthService

2023-02-13 12:37 UTC, undsoft requested changes

2023-02-13 12:37 UTC, undsoft commented on src/app/services/auth/auth.service.ts
> +      this.generateTokenSubscription = timer(0, 290 * 1000).pipe(
Let's extract 300 to a variable to explain that this is a default middleware token duration.

2023-02-13 12:37 UTC, undsoft commented on src/app/services/auth/auth.service.ts
> +  }
I don't see any code that would clear this subscription. Wouldn't logging out and logging-in again result in two timers?

2023-02-14 13:45 UTC, undsoft approved these changes
Looks good, nice work.
One thing we may want to do is explicitly set timeout duration when generating a token, just so that it's definitely 300 and not some other value that middleware may change in the future.

2023-02-14 16:15 UTC, dszidi approved these changes
Code looks good. Tested and token gets regenerated without any duplicates

2023-02-14 23:23 UTC, RehanY147 commented
Please review again. Found a bug where if you were to redirect directly to a component which immediately needed the token, the token wouldn't be ready and the component would break.

The new added commit makes it so that when logged in using credentials, token is generated together with the login request. If you want to check the logic, successful login call emits `true` to `isLoggedIn$` which triggers the subscription in the `AuthService` constructor where we call the method to setup token generation. But in the original login method, after issuing `true` to `isLoggedIn$`, it is now waiting on `authToken$` which will emit when eventually we get a token from middleware and only then will the login method complete and the login request complete basically. I explained the logic because I want that reviewed as well.

2023-02-15 12:43 UTC, undsoft approved these changes
Still appears to be working correctly.

2023-02-15 21:00 UTC, merged