NAS-120264: Dataset names don't have to begin with an alphanumeric character.
truenas/webui pull request #7739
Opened 2023-02-10 15:18 UTC by AlexKarpov98

2023-02-10 15:18 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120264

2023-02-11 06:08 UTC, denysbutenko requested changes
The title and description of the ticket need to be more consistent.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/351613/218243287-380fa250-ece1-4d28-bebb-26f941479038.png">

<img width="217" alt="image" src="https://user-images.githubusercontent.com/351613/218243195-a57a7a69-8354-459f-b810-06f6b6d2f307.png">

The `name` field accepts non-alphanumeric and alphanumeric values at the beginning. It depends on the goal of the ticket.

2023-02-11 06:53 UTC, AlexKarpov98 commented
@denysbutenko as an examiner this was sent to me
![image](https://user-images.githubusercontent.com/22980553/218245066-68d7796a-8410-4497-88bd-17ae738035de.png)

2023-02-13 13:23 UTC, denysbutenko approved these changes
![image](https://user-images.githubusercontent.com/351613/218468908-da3e946e-0bc6-4e6c-a6d6-766c34c96d2a.png)

It works as described. Other non-alphanumeric characters are still allowed.

2023-02-13 15:38 UTC, merged