NAS-120274: Fixed logout
truenas/webui pull request #7745
Opened 2023-02-12 21:32 UTC by RehanY147

2023-02-12 21:32 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120274

2023-02-13 05:10 UTC, denysbutenko requested changes
Sometimes after logging out, the sign-in form appears for a second, then switches to the "Connecting to TrueNAS..." state, and the sign-in form appears again. However, it works well mainly.

Tests need to be completed.

2023-02-16 14:03 UTC, denysbutenko approved these changes
It looks good and works well.

2023-02-17 05:04 UTC, RehanY147 commented on src/app/services/websocket-connection.service.ts
> +    timer(this.reconnectTimeoutMillis).pipe(untilDestroyed(this)).subscribe({
`timer` is from rxjs. It only emits once after specified milliseconds. Then the observable completes. So, don't need to unsubscribe.

2023-02-17 05:04 UTC, merged