Create the Installed Apps table
truenas/webui pull request #7773
Opened 2023-02-15 06:53 UTC by bvasilenko

2023-02-15 06:53 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120087

2023-02-15 15:42 UTC, denysbutenko requested changes
I did a code review. The checks need to be completed to continue.

2023-02-15 15:42 UTC, denysbutenko commented on src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
> +    <span> 2% </span>
Let's use `N/A` instead of dummy data. Here and there in other places.

2023-02-15 15:42 UTC, denysbutenko commented on src/app/pages/apps/components/installed-apps/installed-apps.component.ts
> +import { ApplicationsService } from 'app/pages/apps-old/applications.service';
I am unsure if we will use the app service from the old apps module. There is a new one - [app/pages/apps/services/applications.service.ts](https://github.com/truenas/webui/blob/master/src/app/pages/apps/services/applications.service.ts)

2023-02-17 14:53 UTC, bvasilenko commented
@denysbutenko remarks and linter errors should be fixed now. Would you please take another look?

2023-02-18 04:12 UTC, denysbutenko requested changes
Just a heads up, we still need to complete the checks before moving forward.

2023-02-21 06:09 UTC, merged