NAS-120052: Migrate Input, Select, Autocomplete, FormField to MDC (related)
truenas/webui pull request #7788
Opened 2023-02-17 10:37 UTC by AlexKarpov98

2023-02-17 10:37 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120052

2023-02-17 15:48 UTC, undsoft requested changes
Some minor things look different than what they used to:
- checkbox is now bigger
- icons in filters (like in /sharing/smb) are larger now
- when you hover over a password field (for example in user form) there is a small x icon appears in corner, which we didn't have before.
- when adding a certificate authority, when you go step 3 "subject alternate names" has misaligned text
- add certificate -> extra constraints -> extended key usages. Usages dropdown has misaligned tooltips.

2023-02-17 15:48 UTC, undsoft commented on src/app/modules/ix-forms/classes/simple-async-combobox-provider.ts
> +    options$.pipe(take(1)).subscribe((value) => this.options = value);
This is incorrect, this class is not designed to load things on its own. If you are concerned about combobox constantly spinning in some forms, then this is another bug: https://ixsystems.atlassian.net/browse/NAS-120116

2023-02-17 17:39 UTC, undsoft requested changes
Other comments not addressed.

2023-02-24 10:53 UTC, undsoft approved these changes
Tooltips in select in Add Certificate -> Extra Constraints -> Key Usage also need to be aligned.
Otherwise looks good.

2023-02-24 11:29 UTC, AlexKarpov98 commented
<img width="369" alt="Screenshot 2023-02-24 at 13 29 07" src="https://user-images.githubusercontent.com/22980553/221168423-b9e37ee9-bc2d-4db4-bfae-0c5b0b9422c7.png">
now it's fixed

2023-02-24 11:59 UTC, merged