NAS-120419: Improvements for Installed Apps table
truenas/webui pull request #7802
Opened 2023-02-21 14:54 UTC by bvasilenko

**Testing**

Test 4 improvements mentioned in the ticket

2023-02-21 14:54 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120419

2023-02-23 13:58 UTC, denysbutenko requested changes

2023-02-23 13:58 UTC, denysbutenko commented on src/app/pages/apps/components/installed-apps/installed-apps.component.html
> +            {{ 'Kubernetes is not running or does not have installed apps' | translate }}
Let's keep the old wording.

- When Kubernetes is not running – `Applications are not running`. 
- When no installed apps - `No Applications Installed`

![image](https://user-images.githubusercontent.com/351613/220927737-f7d48aa8-450f-4019-8aa4-d6dde97726d9.png)
![image](https://user-images.githubusercontent.com/351613/220927756-5195eb7c-ce7f-40f2-9b51-dd7b42354be1.png)

2023-02-23 13:58 UTC, denysbutenko commented on src/app/pages/apps/components/installed-apps/installed-apps.component.html
>                  ix-auto
`ix-auto` directive has been removed

2023-02-23 13:58 UTC, denysbutenko commented on src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
> +      <img [src]="application.chart_metadata.icon" [src-fallback]="imagePlaceholder" />
There is [app-card-logo component](https://github.com/truenas/webui/blob/master/src/app/pages/apps/components/app-card-logo/app-card-logo.component.ts#L13), please consider if it is applicable here.

2023-02-28 06:25 UTC, bvasilenko commented
@denysbutenko Ok, should be fixed now

2023-03-02 07:13 UTC, denysbutenko approved these changes
![image](https://user-images.githubusercontent.com/351613/222356920-771f3a2e-1372-4718-988d-31a4ada8f4d1.png)
![image](https://user-images.githubusercontent.com/351613/222356936-7af3e0ce-f6f0-432d-bc7a-0ba939e3272b.png)
![image](https://user-images.githubusercontent.com/351613/222356959-0e0577b9-ad48-468d-8cf6-f1612f240622.png)

Looks good.

2023-03-03 07:11 UTC, merged