Implement Available Apps header with filtering/searching
truenas/webui pull request #7888
Opened 2023-03-10 07:18 UTC by bvasilenko

See ticket

2023-03-10 07:19 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119864

2023-03-10 09:36 UTC, undsoft requested changes
1. The header is too cramped horizontally. We should have max-width on search block and we should add more free space between large numbers.
2. When filters are open, block with numbers jumps. It should stay locked to the top.
3. I think it's awkward to have to unselect app categories to filter by what you want. We should start with empty filter meaning all categories and let user select instead, preferably with autocomplete.
4. Design calls for a help text below app categories filter.
5. We can add unit tests for available-apps-header already.

2023-03-10 09:37 UTC, undsoft commented
@dszidi We probably need to add a filter by trains here as well.

2023-03-13 11:03 UTC, RehanY147 requested changes
Please note that there is a new call `app.available` that we want to use to filter apps info. We want to use this endpoint instead of `catalog.query`. This endpoint also supports filters like the ones in the designs directly.

2023-03-15 17:40 UTC, bvasilenko commented
@RehanY147 Ok, the requested changes are done

2023-03-16 13:16 UTC, undsoft approved these changes
Generally looks okay.

ix-chips had a stroke on me.
<img width="446" alt="Снимок экрана 2023-03-16 в 14 15 30" src="https://user-images.githubusercontent.com/1481270/225628509-d76d25ca-299c-4d7a-8e96-7840a1d40267.png">

2023-03-16 13:16 UTC, undsoft commented on src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.spec.ts
> +        mockCall('chart.release.query', [{}, {}, {}] as unknown as ChartRelease[]),
Casting to unknown is unnecessary here and a line above.

2023-03-16 13:16 UTC, undsoft commented on src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.spec.ts
> +  });
Component does a bit more than just showing 3 numbers.

2023-03-16 13:16 UTC, undsoft commented on src/app/pages/apps/services/applications.service.ts
> +    return this.ws.call('app.available', [firstOption]).pipe(switchMap((app) => of(app[0])));
Or you know, just `map` :)

2023-03-20 11:21 UTC, RehanY147 approved these changes
Please address feedback by @undsoft

2023-03-21 09:54 UTC, merged