NAS-120508: WebUI validation of VDEV redundancy across VDEV types
truenas/webui pull request #7990
Opened 2023-03-24 15:57 UTC by AlexKarpov98

2023-03-24 15:57 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120508

2023-03-28 12:21 UTC, dszidi requested changes
Please update src/app/services/storage.service.spec.ts file to reflect affected scenarios and desired outcomes.

2023-03-29 17:05 UTC, dszidi requested changes
Requested adjustment to topology card spec file

2023-03-29 17:05 UTC, dszidi commented on src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
> +    expect(values[1]).toHaveText('1 x MIRROR | 3 wide | 8 TiB');
For this test let's have both redundancy mismatched and matched scenarios. Both Metadata and Dedup need to match redundancy level of data vdevs. Perhaps leave the metadata vdevs as you already have it but add dedup topology category to mockstorage and deliberately mismatch it? That way we can test for the error message.

2023-03-30 15:16 UTC, AlexKarpov98 commented on src/app/core/testing/utils/mock-storage-generator.utils.ts
> +        // if (options.layout === TopologyItemType.Stripe || options.layout === TopologyItemType.Disk) {
my mistake

2023-03-31 10:29 UTC, AlexKarpov98 commented
@dszidi - please check it now :)

2023-03-31 16:37 UTC, dszidi approved these changes
LGTM

2023-03-31 16:37 UTC, merged