More improvements for the installed apps
truenas/webui pull request #7995
Opened 2023-03-27 11:27 UTC by denysbutenko

WIP. Merge after #7895

2023-03-27 11:27 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121106

2023-03-27 15:56 UTC, denysbutenko commented
Better empty states:

![Kapture 2023-03-27 at 21 59 06](https://user-images.githubusercontent.com/351613/227995431-03fa1096-6ed2-439c-909f-ea14125c7e6d.gif)

![Kapture 2023-03-27 at 22 11 17](https://user-images.githubusercontent.com/351613/227995523-b953588b-76f1-435c-804b-e9b14f78cc7d.gif)

![image](https://user-images.githubusercontent.com/351613/227996054-9d7c3bb6-3803-4834-936f-7afaac1323c5.png)

![image](https://user-images.githubusercontent.com/351613/227995103-a5a28040-b72d-4bda-a7fd-6b0e20025ecf.png)

Note: The search still needs to be implemented.

2023-03-28 15:30 UTC, RehanY147 reviewed
Little confused, Is this PR ready for review?

2023-03-28 15:30 UTC, RehanY147 commented on src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.ts
> +    this.getResources();
This is not needed. `ngOnChanges` will trigger for the first time already.

2023-03-30 02:25 UTC, denysbutenko commented
@RehanY147 The branch has been rebased, and the PR is cleaned up for a simple review.

2023-03-31 01:40 UTC, RehanY147 requested changes
We can give these status tiles some more margin.
<img width="516" alt="image" src="https://user-images.githubusercontent.com/24204846/228999976-52e5561a-34ee-49d0-a770-bd5d5946d920.png">

Also, column names and their values don't seem perfectly aligned. We should make them aligned vertically.

Furthermore, the app name text font is larger than column headers. It seems so in the designs as well but in the designs, the app name text has muted grey color. Should talk to Damian on what's the best way forward. As is, the app name takes attention away from the header.

The items under the `Action` column aren't center aligned. They are center aligned in the designs.

In the designs, the table title and the App Info title have more top-margin than what's there now. When you select a row and bulk actions show, the text and drop down seem too close to the top divider. We should have a bit more separation there if not exactly not like the designs.

The text of Bulk Actions has a larger font than the designs. As does the text inside the dropdown it feels like.

We can improve the message on empty state where it says `click here to see the TrueNAS catalog to get started`. We should say, `click here to see all the available apps to get started`.

Selected app should have a "selected" state to show that it's selected. Some indication like a highlighter that shows this row is selected.

2023-04-03 04:49 UTC, denysbutenko commented
> We can give these status tiles some more margin. <img alt="image" width="516" src="https://user-images.githubusercontent.com/24204846/228999976-52e5561a-34ee-49d0-a770-bd5d5946d920.png">

Do you mean to add some vertical space between columns?

> Also, column names and their values don't seem perfectly aligned. We should make them aligned vertically.
> 

Some regression in this branch. It was fixed.

> Furthermore, the app name text font is larger than column headers. It seems so in the designs as well but in the designs, the app name text has muted grey color. Should talk to Damian on what's the best way forward. As is, the app name takes attention away from the header.
> 

That's true. There are many differences in fonts, sizes, and colors between design mockups and the default theme in WebUI. For example,

- `h1` font-size is `35px` in mockups and `30.478px` in webui.
- `h2` font-size is `24.19px` in mockups and `25.40px` in webui.
- Side Menu items is `14px` in mockups and `12.25px` in webui.

As for colors, I believe we should use existing variables for theme compatibility.
The font size requires a complex solution and can be handled in a separate task.

> The items under the `Action` column aren't center aligned. They are center aligned in the designs.
> 

I made changes to align the text and buttons in the last column by center.

> In the designs, the table title and the App Info title have more top-margin than what's there now. When you select a row and bulk actions show, the text and drop down seem too close to the top divider. We should have a bit more separation there if not exactly not like the designs.
> 

Done 👍🏻 

> The text of Bulk Actions has a larger font than the designs. As does the text inside the dropdown it feels like.
> 

It was the default font size of the button. The font size was decreased for this element only.

> We can improve the message on empty state where it says `click here to see the TrueNAS catalog to get started`. We should say, `click here to see all the available apps to get started`.

Thanks for the suggestion. The text has been updated.

> Selected app should have a "selected" state to show that it's selected. Some indication like a highlighter that shows this row is selected.

The regression was fixed.

2023-04-03 21:43 UTC, RehanY147 commented
> Do you mean to add some vertical space between columns?
No, I mean horizontal margins.

> As for colors, I believe we should use existing variables for theme compatibility.
I'm not recommending that we change any colors or add any custom colors. I'm saying that app name having larger font-size only works if the text color is muted. Since, we don't have a muted color for text that is supported by themes, we shouldn't have app name font-size larger than table headers. It should be at max the same size. Or smaller. We can discuss with @dszidi

2023-04-03 21:58 UTC, RehanY147 requested changes
Add a bit of horizontal margin to the `Action` column from the right border.

I think we can reduce the margins around the app name column as app names aren't going to be that long. We can add a hover effect to show the name so if it is too long, we can show it separately.
Also I think the margin is now a bit too much around the state tiles column. We want the margin there, just we can reduce it a little bit.
Please note that these column values don't look center aligned. They look left aligned. We want them to be center aligned.
<img width="188" alt="image" src="https://user-images.githubusercontent.com/24204846/229635358-be9220e5-783b-4ffa-ad80-ccb0b41239f6.png">

When the screen is shortened, the apps info cards disappear and don't reappear when you select a row. Also, the columns are misaligned again.
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/24204846/229636751-64810e2b-9792-494c-a2d5-3d3fe8534ee2.png">

2023-04-03 22:00 UTC, RehanY147 commented
@denysbutenko if you want, we can merge some changes and you can create a new ticket for the remaining changes so you can avoid merge conflicts as the other PRs get merged into `master`.

2023-04-04 07:24 UTC, denysbutenko commented
>>Do you mean to add some vertical space between columns?

> No, I mean horizontal margins.

Ok, it was changed.

> I'm not recommending that we change any colors or add any custom colors. I'm saying that app name having larger font-size only works if the text color is muted. Since, we don't have a muted color for text that is supported by themes, we shouldn't have app name font-size larger than table headers. It should be at max the same size. Or smaller. We can discuss with @dszidi 

I reverted the font size to default values – `12.25px` for the app name. And keep `10px` for the catalog.


> Add a bit of horizontal margin to the `Action` column from the right border.
>

Ok, it was changed.

> I think we can reduce the margins around the app name column as app names aren't going to be that long. We can add a hover effect to show the name so if it is too long, we can show it separately.

The name column fills available space depending on other columns. If you want to make it fixed, please let me know more details.

> Also I think the margin is now a bit too much around the state tiles column. We want the margin there, just we can reduce it a little bit. 

Ok, it changed. This column preserves a space for max possible width when the status is deploying. If you have another value in mind, please let me know.

> Please note that these column values don't look center aligned. They look left aligned. We want them to be center aligned. <img alt="image" width="188" src="https://user-images.githubusercontent.com/24204846/229635358-be9220e5-783b-4ffa-ad80-ccb0b41239f6.png">
> 

They left aligned exactly like in the design. This sounds like a new requirement to me. Let's return to this when we get real values for these columns.
![image](https://user-images.githubusercontent.com/351613/229709506-08cccbd9-0d8c-4103-974b-26387f206231.png)

> When the screen is shortened, the apps info cards disappear and don't reappear when you select a row. Also, the columns are misaligned again. <img alt="image" width="1051" src="https://user-images.githubusercontent.com/24204846/229636751-64810e2b-9792-494c-a2d5-3d3fe8534ee2.png">

Yes, the styles were partially copied from another place, and the mobile details view needs to be implemented. Could you create a ticket for this?

@RehanY147 I'm good to finish the remaining changes in this PR. As for new requirements, it would be better to split the work. Thanks for the feedback.

2023-04-06 16:25 UTC, RehanY147 approved these changes
Looks good

2023-04-07 06:01 UTC, merged

2023-04-07 06:01 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-121106 is targeted to the following versions which have not received their corresponding PRs: 23.10