Using the new `ErrorHandlerService`
truenas/webui pull request #8012
Opened 2023-03-30 00:39 UTC by RehanY147

2023-03-30 00:40 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121171

2023-03-31 17:50 UTC, dszidi requested changes
The code looks reasonable. The only thing I would change is
- ditch the commented out EntityUtils code.
- Add some spec files to test make sure the ErrorHandlerService produces desired behavior.

2023-03-31 17:50 UTC, dszidi commented on src/app/modules/entity/utils.ts
> +// interface HttpError {
We should delete these if not in use

2023-04-03 14:37 UTC, RehanY147 commented
Tests will be added by https://ixsystems.atlassian.net/browse/NAS-121305

2023-04-03 17:01 UTC, dszidi approved these changes
Tested by triggering the dialog after init on snapshots list page. 
LGTM

<img width="881" alt="image" src="https://user-images.githubusercontent.com/29865743/229578029-b843945e-8e19-4644-8ec4-18cc47fc9422.png">

2023-04-03 17:42 UTC, merged