NAS-121307: Resolve issues with old-style timeFormat
truenas/webui pull request #8029
Opened 2023-04-03 17:32 UTC by rickwargo

`timeFormat` in local storage may have an old-style format escape `A` that needs to be converted to `aa`. If not converted, the UI does not work reliably, creating hundreds of RangeError messages in the console and potentially freezing the screen.

2023-04-04 04:29 UTC, denysbutenko requested changes
I think it works great. Thanks for the contribution.

2023-04-04 04:29 UTC, denysbutenko approved these changes
It works great. Thanks for the contribution.

2023-04-04 04:38 UTC, denysbutenko commented
Hey, @undsoft, we need some help with the contribution workflow. Specifically, the test coverage can't be uploaded to codecov because of a missing token, preventing the PR from being merged. Would you happen to have any suggestions for how we can address this issue and move forward with merging the PR? Thanks for your help!

2023-04-04 09:06 UTC, merged

2023-04-08 18:05 UTC, undsoft commented
backport

2023-04-08 18:05 UTC, bugclerk commented
Unable to backport: can't get issue ID from title 'NAS-121308: Resolve issues with old-style timeFormat'