NAS-121177: Refactor IxSlideInService
truenas/webui pull request #8032
Opened 2023-04-04 10:19 UTC by Raz-Dva

Method open of IxSlideInService returns 
      .componentInstance
      .close()
      .afterClosed$

It is possible to pass data to the created component using
@Inject(SLIDEIN_DATA) data

2023-04-04 10:19 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121177

2023-04-04 10:47 UTC, undsoft requested changes
You didn't have to update every usage just yet. It's important to get API right before updating every place.
You can just create `open2` method temporarily for example and update usage in one place or whatever is easier.

2023-04-04 10:47 UTC, undsoft commented on src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.ts
> +    const injector = Injector.create({ providers: [{ provide: SLIDEIN_DATA, useValue: params?.data }] });
SLIDE_IN_DATA

2023-04-04 10:47 UTC, undsoft commented on src/app/services/ix-slide-in.service.ts
> +    };
The idea is to be able to tell when a specific slide in has been closed.
For example, in material dialogs I can open individual dialog, tell when it was closed and receive data from it.
```
this.dialog.open(MyDialog)
  .afterClosed()
  .subscribe((result) => {
    console.log('My Dialog was closed with result', result);
  });
```

This is not possible right now. `onClose$` will emit for every slide in closed, not just the one I'm opening.

2023-04-07 11:51 UTC, undsoft approved these changes
Looks good. You can either update usages everywhere or keep old methods and add new methods and do replacements in future PRs.

2023-04-07 11:51 UTC, undsoft commented on src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in-ref.ts
> +export class IxSlideInRef<T> {
Let's also add second generic R for returning value.

2023-04-07 11:51 UTC, undsoft commented on src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in-ref.ts
> +  closeThisSlide(error?: Error, response?: unknown): void {
Let's rename to just `close` and change arguments to `response: R`. I don't think we need to pass modalType or error. What to return would be up to developer.

2023-04-07 11:51 UTC, undsoft commented on src/app/services/ix-slide-in.service.ts
> +  open<T>(modal: Type<T>, params?: { wide?: boolean; data?: { [key: string]: unknown } }): IxSlideInRef<T> {
Let's also add a generic for returning value, defaulting to `unknown`.

2023-04-07 11:51 UTC, undsoft commented on src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
> +      this.afterClosedSlideIn$.pipe(mergeMap((afterClosed$) => afterClosed$)),
This is perhaps a bad example for this. I think in the future, this component would be split up into smaller card components and each card will responsible for reloading itself once slideIn is closed as opposed to having this method.

2023-04-25 17:41 UTC, Raz-Dva commented
For the working pull request, I will create a new ixSlideService.
I will make pull requests gradually removing the methods of the old service.

2023-04-28 18:28 UTC, undsoft commented
@Raz-Dva Can this PR be closed since you have another one?

2023-05-01 12:15 UTC, closed without merging

2023-05-01 12:18 UTC, Raz-Dva commented
Another one is open for this issue  https://github.com/truenas/webui/pull/8120