Improvements for the apps available filter
truenas/webui pull request #8036
Opened 2023-04-05 17:28 UTC by bvasilenko

**Testing:**

On the **Apps > Available** page:

1. Verify that the filter width looks good
2. Test that checkboxes and radiobuttons now match the design, provided [here](https://github.com/truenas/webui/discussions/7502), under **Search & Inventory** heading
3. Verify that progress bar looks properly when filter is applied

2023-04-05 17:29 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121290

2023-04-06 09:29 UTC, undsoft requested changes
I really don't know if having an `altView` is a good idea. I understand the desire to avoid duplicating code, but having this setting makes API of the component kinda messy. Harnesses would need to be adjusted, you'd need to have another set of tests for this layout. And currently it's used in one place.
I would rather we create a new set of components, maybe even in separate module or within apps module for now.

UI feedback:
1. The filter is now too wide. I think there should some maximum width. If you are on ultra-wide you'll get a very long, inconvenient input. Also numbers on the right need some room to breathe between them and filters.
2. Need to change cursor on new controls.
3. Checkmarks are larger than in designs.
4. In designs there are no "empty" checkmarks.
5. Catalogs and Sort labels have an underline and have different font.

2023-04-06 09:29 UTC, undsoft commented on src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.spec.ts
> -  it('emits (filters) when user selects catalogs', async () => {
We still need tests.

2023-04-07 12:45 UTC, bvasilenko commented
@undsoft 
Ok, now these components extracted to a custom module

2023-04-08 09:28 UTC, undsoft approved these changes
Looks good.

2023-04-08 09:28 UTC, undsoft commented on src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.spec.ts
> +    sortItems = spectator.queryAll('.sort .item');
This is fine, but it would be easier to work with the component in tests if you were to create a harness for `filter-select-list`.

2023-04-10 10:56 UTC, merged