NAS-121266 / 22.12.3 / Ignore EEXIST error while creating snapshots
truenas/webui pull request #8039
Opened 2023-04-06 06:24 UTC by denysbutenko

Please check the ticket for details.

2023-04-06 06:24 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121266

2023-04-06 09:11 UTC, undsoft requested changes
I think we are supposed to have `errname` in Bluefin middleware as well now.

2023-04-06 10:34 UTC, undsoft approved these changes
Middleware nightly is not yet available, but it should work.

2023-04-10 09:40 UTC, denysbutenko commented
[truenas/middleware#11060](https://github.com/truenas/middleware/pull/11060)
[truenas/middleware#11053](https://github.com/truenas/middleware/pull/11053)

The middleware PRs are merged, so it should be fine to go.

2023-04-10 09:41 UTC, merged

2023-04-10 09:41 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-121266 is targeted to the following versions which have not received their corresponding PRs: 22.12.3