Connected manual disk selection modal to pool wizard
truenas/webui pull request #8045
Opened 2023-04-07 22:00 UTC by RehanY147

2023-04-07 22:00 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121205

2023-04-10 06:35 UTC, denysbutenko requested changes
Getting error in console
```
TypeError: Cannot read properties of undefined (reading 'rawSize')
    at rn (create-data-wizard-step.component.html:109:71)
```


https://user-images.githubusercontent.com/351613/230841791-6a3016da-a9b4-4466-89a9-af58fb6d6c89.mp4

2023-04-10 06:35 UTC, denysbutenko commented on src/app/helptext/storage/volumes/manager/manager.ts
> +  edit your selections, press the "Edit Manula Disk Selection" button below. To start again with the\
Typo in "Manual"

2023-04-10 12:35 UTC, undsoft requested changes
1. If I save custom selection, Reset and then click Manual Disk selection, I expect to see the same autogenerated set of vdevs because values in dropdown were not changed.
2. If I open manual selection dialog and remove all vdevs and save, I don't expect it to say that custom layout was applied. Also if I press Edit again, I get a broken modal.
3. If I open manual selection, and make no changes, it would be good to also not say that custom layout was applied.

2023-04-14 06:56 UTC, denysbutenko approved these changes
Minor layout issue with the `Reset` button.
![image](https://user-images.githubusercontent.com/351613/231966714-bdd5e97f-7917-4ff3-b83b-20ee7e12f3f0.png)

Otherwise, it looks great and works great for me.

2023-04-14 12:25 UTC, undsoft approved these changes
Looks good, thanks.

2023-04-14 22:24 UTC, merged