NAS-121189: Minor improvements when installing an app
truenas/webui pull request #8062
Opened 2023-04-13 01:04 UTC by RehanY147

Read ticket description for todos

2023-04-13 01:04 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121189

2023-04-14 12:12 UTC, undsoft requested changes
Ticket number is incorrect. I'm assuming this is the ticket that this relates to:
If so, last two items are still not addressed. I still get two dialogs on receiving an error and I can still minimize job dialog when installing an app.

2023-04-14 12:12 UTC, undsoft commented on src/app/pages/apps/components/chart-wizard/chart-wizard.component.html
> +          {{ isNew ? 'Install' : 'Update' | translate }}
Message extractor won't be picked from this. It should be `isNew ? ('Install' | translate) : ('Update' | translate)`

2023-04-14 21:53 UTC, RehanY147 commented
Wrong branch name.

2023-04-14 21:53 UTC, closed without merging