Refactor replication wizard to ix-forms
truenas/webui pull request #8069
Opened 2023-04-13 20:41 UTC by bvasilenko

**Testing**

Verify the functionality of **Replication Wizard**

2023-04-13 20:41 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121394

2023-04-14 09:39 UTC, undsoft requested changes
Only did superficial testing in UI.
Explorer doesn't seem to work correctly on remote systems.

2023-04-18 06:24 UTC, bvasilenko commented
@undsoft ok, all review remarks should be addressed

2023-04-18 14:15 UTC, undsoft requested changes
I don't know if you pushed all changes, but here are some of the new things I've discovered in addition to _some of the previous items_ that were not fixed:
* Missing a button to switch to advanced replication creation.
* Missing a line that says `14 snapshots found.` when creating a local replication.
* If you select Encryption and Key, untick Generate and switch to Passphrase, you'll see an extra Encryption Key.
* When I set replication with remote component, old UI would show `Include snapshots with the name` fields. New UI doesn't.
* `SSH Connections` field can be renamed to `SSH Connection`
* Old UI didn't have a confirmation step. I'm okay with not having it too.

2023-04-19 18:26 UTC, bvasilenko commented
@undsoft ok, all the remarks should be addressed

2023-04-20 16:54 UTC, undsoft requested changes
1. When I meant that we can remove summary, I mean no step 3 at all (as it currently works). We should either have summary or just save on step 2.
2. When I switch to regex and field is empty I get `[EINVAL] count_eligible_manual_snapshots.name_regex: Empty value not allowed` in console. Probably not worth sending request on empty name_regex.
3. When I create replication from Remote to Local, old UI would show `Include snapshots with the name`. New UI does not and replication cannot be created.

2023-04-20 16:54 UTC, undsoft commented on src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
> +          map((createdSnapshotTasks) => this.createdSnapshotTasks = (createdSnapshotTasks || []).filter((tk) => !!tk)),
`tk` => `task`

2023-04-20 16:54 UTC, undsoft commented on src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
> +      this.callCreateTasks(values).pipe(
Eh, why not just use `switchMap`?

2023-04-20 16:54 UTC, undsoft commented on src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
> +  getSnapshotsСount(payload: CountManualSnapshotsParams): Observable<EligibleManualSnapshotsCount> {
I still get `Name contains both ASCII and non-ASCII symbols: getSnapshotsСount ` in letter `c`.

2023-04-20 16:54 UTC, undsoft commented on src/app/pages/data-protection/replication/replication-wizard/steps/replication-what-and-where/replication-what-and-where.component.ts
> +    this.form.controls.source_datasets_from.setValue(null);
Maybe just do `this.form.patchValue({ ... })`.

2023-04-22 16:35 UTC, undsoft commented
I've merged [a PR](https://github.com/truenas/webui/pull/8087) which refactors Replication Form to ix-forms. 
I don't know if there is anything useful for you there.

I've updated this PR.

2023-04-24 06:22 UTC, bvasilenko commented
@undsoft my last commit should fix the remaining remarks, so this should be ready for review now

2023-04-24 09:57 UTC, undsoft requested changes
1. Auto generated name didn't use to include `mnt` part.
2. When setting up local replication old UI shows `0 snapshots found. Snapshots will be created automatically.`. New UI doesn't show this string.
3. I also believe we are missing colors on these messages.
4. I've selected an existing replication and noticed that Source field didn't get populated correctly.
5. When setting up local-to-remote replication, old UI would only show me two fields in Destination Snapshot Lifetime: Same as source and Never Delete. New UI also shows Custom.

Rest looks okay, tested in multiple scenarios.

2023-04-26 06:32 UTC, bvasilenko commented
@undsoft the latest requests should be addressed now

2023-04-26 11:39 UTC, undsoft approved these changes
Looks good, but one issue is not resolved.
If you go to our m40 and select an existing replication called `pizza`, you'll see that no source datasets are selected.

2023-04-27 16:42 UTC, merged