NAS-121664: Stop or start only the necessary applications
truenas/webui pull request #8119
Opened 2023-04-27 10:38 UTC by bvasilenko

**Testing**

Please follow repro steps described in the ticket, and make sure actual behavior now matches the expected one

2023-04-27 10:38 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121664

2023-05-01 04:06 UTC, denysbutenko requested changes
It also uses different terms, `checkedAppsNames()` vs `startedSelectedApps()`. So let's use consistent naming.

2023-05-02 18:15 UTC, bvasilenko commented on src/app/pages/apps/components/installed-apps/installed-apps.component.ts
> +    return this.dataSource.filter((app) => app.status !== ChartReleaseStatus.Stopped && app.selected);
It's not very clear here: checkedAppsNames - returns a list of names (strings) of selected applications. And startedSelectedApps returns an array of started applications (ChartRelease[]). Is renaming really necessary?

@denysbutenko would you please clarify?

2023-05-03 07:06 UTC, denysbutenko commented on src/app/pages/apps/components/installed-apps/installed-apps.component.ts
> +    return this.dataSource.filter((app) => app.status !== ChartReleaseStatus.Stopped && app.selected);
@bvasilenko Just wanted to give you a heads-up that some methods use the word `checked` while others use `selected` which might be a bit confusing.

2023-05-03 09:10 UTC, undsoft approved these changes
Looks good.

2023-05-03 09:11 UTC, merged