NAS-121596: Fixed creating a new user fails
truenas/webui pull request #8125
Opened 2023-04-28 16:50 UTC by Raz-Dva

Go to **Credentials** -> **Users** 
Create a new user. Check the availability of fields that a new user can change.

2023-04-28 16:51 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121596

2023-04-29 12:52 UTC, undsoft requested changes
What is `param`? I don't see it being documented anywhere.

2023-04-29 20:44 UTC, Raz-Dva commented
This pull request is for bluefin only. The description [NAS-121222](https://ixsystems.atlassian.net/browse/NAS-121222) states that in Bluefin user.shell_choices has 2 arguments. First should be null, second is group IDs list.

2023-05-01 11:13 UTC, undsoft approved these changes
I see, looks good then.

2023-05-01 11:13 UTC, merged