NAS-121844 / 23.10 / Make sure mock utility doesn't break UI
truenas/webui pull request #8156
Opened 2023-05-05 15:43 UTC by dszidi

Removed a condition that broke UI if `mock-pool` was disabled

Try enabling/disabling `mock-enclosure` and `mock-disks` with and without `mock-pools` enabled
There should not be any combination that results in browser console error that breaks the UI

2023-05-05 15:43 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121844

2023-05-05 16:36 UTC, undsoft requested changes
I've added this condition, because we had problems with production installations, where we'd get "cannot read `mockPools` of undefined".

2023-05-05 17:40 UTC, dszidi commented
> I've added this condition, because we had problems with production installations, where we'd get "cannot read `mockPools` of undefined".

Ah ok. In that case since mockConfig is optional, I'll remove it from the prod environment file and do an earlier check in ws.service as a condition for creating mockUtils. That way mockUtils won't get created at all unless we're in dev mode and mockConfig is set

2023-05-08 20:28 UTC, undsoft approved these changes
👍🏻

2023-05-08 21:15 UTC, merged