NAS-121879: Implement notes card with markdown
truenas/webui pull request #8183
Opened 2023-05-11 05:46 UTC by bvasilenko

**Testing**

At **Applications > Installed** the new "notes" card should appear. See details in the ticket

2023-05-11 05:46 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121879

2023-05-13 10:19 UTC, undsoft requested changes
1. Can we alter default styles inside of a markdown block? Currently headers are way too large.
2. View More link implies navigation. Let's use a button.

2023-05-13 10:19 UTC, undsoft commented on src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.html
> +          {{ isCollapsed ? 'View More' : 'Collapse' | translate }}
This won't get picked by message extractor. Needs to be `('View More' | translate) : ('Collapse' | translate)`

2023-05-15 14:45 UTC, bvasilenko commented
For point 2, the **`<a>`** tag is used, as well as in the components on the screenshots

![image](https://github.com/truenas/webui/assets/20611516/78edee4a-d35e-4ebe-a968-b58af4e79272)

![image](https://github.com/truenas/webui/assets/20611516/2172ae2e-249d-4149-bf48-22f65db70bb0)

2023-05-16 09:45 UTC, undsoft requested changes
Let's make headers even smaller, so that they don't stand out. I think h1 in markdown should be less intrusive than h3 on cards.
I'm okay with `19px` with `font-weight: 500`.

As to `a`, in your examples most links are used appropriately and take you to a different place. In notes, View More / Collapse is an action and should be a button.

2023-05-17 12:13 UTC, bvasilenko commented
@undsoft ok, header size is adjusted

2023-05-17 19:31 UTC, undsoft approved these changes
Looks good overall. There is a small issue when viewing notes on smaller screen. When page is loaded in this mode, `View More` button doesn't appear.

https://github.com/truenas/webui/assets/1481270/27518220-522b-4de0-bd3e-734df81ffea8

2023-05-18 05:29 UTC, merged

2023-05-18 05:34 UTC, bvasilenko commented
Was too quick to hit "merge" button. I'll make another PR to fix the last issue.