NAS-121916 / 23.10 / Fix displaying system serial for HA systems
truenas/webui pull request #8195
Opened 2023-05-15 08:56 UTC by denysbutenko

For testing, use the M50 system from a ticket. First, ensure the `System Information` and `System Information(standby)` widgets show the correct system serial number. Then, go to `System -> General` and check the `Support` card if the `System Serial` has two different serials of HA nodes. Initiate failover and recheck it.

2023-05-15 08:57 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121916

2023-05-17 15:31 UTC, dszidi requested changes
Code looks good and both sysinfo widget and support cards are showing the correct values.

After testing it on our team's M40 I noticed a situation that might cause confusion for users. The value shown on the dashboard is basically the hardware serial and the support card shows the serials the license was issued for. Under normal situations these two will match however, there are possible cases where they might not (RMA, Dev License, Human error etc).

To avoid confusion, please change the label on the support card from "System Serial" to "Licensed Serials"

2023-05-18 08:37 UTC, denysbutenko commented
> Code looks good and both sysinfo widget and support cards are showing the correct values.
> 
> After testing it on our team's M40 I noticed a situation that might cause confusion for users. The value shown on the dashboard is basically the hardware serial and the support card shows the serials the license was issued for. Under normal situations these two will match however, there are possible cases where they might not (RMA, Dev License, Human error etc).
> 
> To avoid confusion, please change the label on the support card from "System Serial" to "Licensed Serials"

Ok. I assume that if the system has a license (non-HA) it should display the license serial as well. Otherwise, it will show `Serial Number`. Is that correct?

2023-05-19 18:15 UTC, denysbutenko commented
Adapted the `system.is_ix_hardware` endpoint and added `Licensed Serials` along with `System Serial`.

2023-05-23 04:42 UTC, denysbutenko commented
@dszidi, please take another look at it.

2023-05-24 07:29 UTC, denysbutenko commented on src/app/pages/system/general-settings/support/support-card/support-card.component.ts
>        this.systemInfo.serial = this.systemInfo.system_serial;
This condition was removed. The template gets serials directly from the data. If there is `this.licenseInfo.system_serial` or `this.licenseInfo.system_serial_ha` are null, then the `Licensed Serials` row won't be rendered on the card. The hardware serial (`System Serial`) has its row and no longer depends on the license.

2023-05-24 10:40 UTC, denysbutenko commented on src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
> +    if (!this.isIxHardware) return;
Fixed

2023-05-24 15:02 UTC, dszidi approved these changes
Looks good. Now these should all make sense to the user

<img width="420" alt="image" src="https://github.com/truenas/webui/assets/29865743/efb4934d-899a-4900-88b0-bd91fa5e4399">


<img width="400" alt="image" src="https://github.com/truenas/webui/assets/29865743/65739e48-92fd-46c6-957d-465f11cc2f56">



<img width="400" alt="image" src="https://github.com/truenas/webui/assets/29865743/45b41273-eeab-404f-88f2-cc108d1afbab">

2023-05-25 06:01 UTC, merged