NAS-122198: Fix active state for Reporting menu item
truenas/webui pull request #8243
Opened 2023-05-29 07:58 UTC by denysbutenko

For more context, follow the original ticket.

For testing, go to Reporting and check if the side nav menu item is active, then change the report type using the dropdown menu and check it again.

2023-05-29 07:58 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122198

2023-05-29 08:16 UTC, AlexKarpov98 requested changes
Seems to be ok.
But now we have another problem -- clicking on the `Reporting` tab (like double click) - right hand switcher disapears.

<img width="1728" alt="Screenshot 2023-05-29 at 11 16 10" src="https://github.com/truenas/webui/assets/22980553/0eb158c4-2a72-4b31-b1ee-5a79b0ce2c89">


Please check my video:
https://github.com/truenas/webui/assets/22980553/bccc7ed6-107b-4761-b3bf-3a8f52299bfa

2023-05-30 00:56 UTC, RehanY147 approved these changes

2023-05-31 07:51 UTC, denysbutenko commented
@AlexKarpov98 I haven't found a way to prevent the toolbar from disappearing. Let's keep it as is.

2023-05-31 07:51 UTC, closed without merging