NAS-122206: Investigate `dataset does not exist` when selecting source in Replication Wizard
truenas/webui pull request #8263
Opened 2023-06-02 11:01 UTC by AlexKarpov98

2023-06-02 11:01 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122206

2023-06-02 12:28 UTC, undsoft commented
@AlexKarpov98 Have you looked into why there are non-existing dataset available in ix-explorer here?

2023-06-07 12:07 UTC, AlexKarpov98 commented
@undsoft - it's the data which comes from the middleware, not sure why it grabs non datasets.
`filesystem.listdir`

with such parameters:
`/mnt/tank [] {order_by: Array(1), limit: 1000}`

I see that middleware sends `file.is_mountpoint` property, if we filter by it - we only see available datasets.

2023-06-07 12:29 UTC, AlexKarpov98 commented
@undsoft - make sense!

2023-06-08 10:59 UTC, undsoft requested changes
I get errors when I try to use it.

https://github.com/truenas/webui/assets/1481270/cfa89c43-ac9a-4845-acad-0643e81964f2

2023-06-08 10:59 UTC, undsoft commented on src/app/services/filesystem.service.ts
> +            if (
Previous version was more readable to me.

2023-06-08 12:43 UTC, AlexKarpov98 commented
@undsoft - are you sure that you are checking on the correct branch with latest updates? (I tested it and it works fine)

2023-06-09 08:42 UTC, merged