NAS-122373: Create vdev inspector in new pool creation
truenas/webui pull request #8290
Opened 2023-06-09 16:32 UTC by undsoft

Testing: see Inspect Vdevs button on Review step in new pool creation.

2023-06-09 16:33 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122373

2023-06-13 08:24 UTC, RehanY147 requested changes
Works Ok. But I think the types column on the left can be made to look a bit more clickable. It's not immediately obvious that those items are selectable.

2023-06-13 10:32 UTC, undsoft commented
Added some hover effects.

2023-06-15 08:56 UTC, AlexKarpov98 approved these changes
Works as expected ✅

2023-06-15 10:45 UTC, merged