NAS-122352: Improve loading state on detail view page
truenas/webui pull request #8302
Opened 2023-06-14 09:33 UTC by denysbutenko

Minor adjustments to improve loading state.

As it now:
![Kapture 2023-06-14 at 16 28 50](https://github.com/truenas/webui/assets/351613/dff8318b-3b71-40f4-a260-e1f84e4eeab1)

How it will look like:
![Kapture 2023-06-14 at 15 58 07](https://github.com/truenas/webui/assets/351613/d90497c6-bc8c-48cf-9bc1-495e5508d1e8)

2023-06-14 09:33 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122352

2023-06-16 07:36 UTC, RehanY147 requested changes

2023-06-16 07:52 UTC, denysbutenko commented on src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
> +      expect(spectator.query('.app-version')).toHaveText('App Version: 1.0.0');
Ok, you caught me. I'll take a look at how to do it better.

2023-06-19 08:10 UTC, RehanY147 approved these changes

2023-06-19 09:32 UTC, merged