NAS-122477: Warnings in pool creation wizard
truenas/webui pull request #8318
Opened 2023-06-18 20:46 UTC by AlexKarpov98

DRAFT

2023-06-18 20:46 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122477

2023-06-19 12:06 UTC, undsoft reviewed
Approach works so far, but I don't know if it's going to be scalable once more rules as added. For example, such orange warnings as using stripe vdevs. It may be better to just look at store and return an error/warning map grouped by step.

Let's also make Warnings a separate row in review step.

2023-06-19 12:06 UTC, undsoft commented on src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
> +  wizardRequiredStepsValidityForm = this.fb.group({
I don't think we should use form for this. It's more like a Map really.

2023-06-21 20:32 UTC, dszidi commented
> Approach works so far, but I don't know if it's going to be scalable once more rules as added. For example, such orange warnings as using stripe vdevs. It may be better to just look at store and return an error/warning map grouped by step...

@undsoft  If the potential for validation errors is going to be this numerous, wouldn't it be better to force the user to deal with them in the step in which they occur? Seems unhelpful to let the user to proceed through numerous steps and hoard validation errors as they go. This way the final step would only need to have warnings

2023-06-21 21:15 UTC, AlexKarpov98 commented
@dszidi - not sure if in real life someone would make as much errors as I did for this demo image :D

2023-06-22 09:24 UTC, undsoft commented
@dszidi The idea is to have warnings in both places – first when they occur and then on review step.

2023-06-22 12:45 UTC, undsoft requested changes
> A stripe data vdev is highly discouraged and will result in data loss if it fails

This is not a type of error that should prevent wizard from being submitted.

> The following disks have exported pools on them. Using those disks will make existing pools on them unable to be imported. You will lose any and all data in selected disks.

Doesn't list disks. We should list disks or make a generic warning.

2023-06-22 12:45 UTC, undsoft commented on src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
> +  readonly poolCreationErrors$ = combineLatest([
I think it would be easier to test if warnings related to logic is extracted into a separate service that uses PoolManagerStore.

2023-06-22 12:45 UTC, undsoft commented on src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
> +  wizardRequiredStepsValidity: {
I don't think we need to take data from components to be able to validate this. Name and settings used for data vdevs are already in state.

2023-06-22 12:57 UTC, undsoft commented on src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
> +              firstDataVdevType = typologyCategory.layout;
I think warnings related to editing a pool, such as `First vdev has {n} disks, new vdev has {m}` and `First vdev is a {vdevType}, new vdev is {newVdevType}` can be removed for now. We should prevent user from doing something like when editing.

2023-06-22 12:58 UTC, undsoft commented on src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
> +                severity: PoolCreationSeverity.Error,
That was likely a warning before.

2023-06-22 12:59 UTC, undsoft commented on src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
> +  disknumExtendConfirmMessage = helptext.manager_disknumExtendConfirmMessage;
This one and above are unused and can be removed.

2023-06-26 15:11 UTC, merged