Add tests harnesses for new tables
truenas/webui pull request #8344
Opened 2023-06-26 08:37 UTC by bvasilenko

Code review should be enough

2023-06-26 08:37 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122527

2023-06-27 08:37 UTC, denysbutenko requested changes

2023-06-30 07:26 UTC, bvasilenko commented
Since there's no major requests and I have multiple PRs based on this PR, I'll merge this PR now and address these typos in my next PR

2023-06-30 08:06 UTC, denysbutenko approved these changes

2023-06-30 08:59 UTC, merged