Add tests to ix-table2
truenas/webui pull request #8345
Opened 2023-06-26 08:38 UTC by bvasilenko

Code review should be enough

2023-06-26 08:38 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122528

2023-06-26 12:03 UTC, RehanY147 requested changes
Tests are failing. Waiting for a build that passes tests

2023-07-04 19:05 UTC, bvasilenko commented
@RehanY147 now it's fixed, and ready for review

2023-07-05 06:57 UTC, undsoft approved these changes
Empty `ix-table2.component.spec.ts` needs to be removed. Otherwise looks good.

2023-07-06 07:16 UTC, RehanY147 approved these changes

2023-07-07 04:46 UTC, merged