Display `Last scrub`
truenas/webui pull request #8415
Opened 2023-07-10 17:20 UTC by bvasilenko

### Testing

Run "scrub" at least once.

**Expected result:**

   On **Dashboard** in the **Pool** widget, new label "Last scrub" should:
    - display the status of the last scrub,
    -  and tooltip should contain the date and time of the last scrub

2023-07-10 17:20 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122664

2023-07-11 18:58 UTC, bvasilenko commented
@AlexKarpov98 error should be fixed now

2023-07-12 05:46 UTC, AlexKarpov98 requested changes
Changes didn't resolve all the issues.

Problem 1: 
I was not able to see immediately Last Scrub Field on fresh machine (latest nightly)
Only after page reload it appeared.

Problem 2:
During scrub in progress, widget shows only one value and not updating
<img width="597" alt="Screenshot 2023-07-12 at 08 34 57" src="https://github.com/truenas/webui/assets/22980553/49703890-6435-4680-8e95-30685f3a8707">
(In progress 15.85%)

Problem 3:
I added new pool via new wizard, returned to dashboard page, errors again (that's latest nightly machine):
<img width="1728" alt="Screenshot 2023-07-12 at 08 40 43" src="https://github.com/truenas/webui/assets/22980553/0afbec66-7f16-4b4a-9008-c0a2e3012c58">

Errors only disappear once I run SCRUB for newly created pool.

I expect to see no errors and real time updates for pool scrub progress on widget and immediately see Last Scrub message on pool once it's available.

2023-07-13 15:09 UTC, AlexKarpov98 approved these changes
It works now, good job.
Only problem found:
<img width="375" alt="Screenshot 2023-07-13 at 18 08 03" src="https://github.com/truenas/webui/assets/22980553/25fb1dd6-699a-4d8b-990b-21bb1e36b991">

Seems `pools` value is undefined
`const updatedPool = this.pools.find((pool) => pool.name === poolScan.name);`

2023-07-14 12:20 UTC, merged