Refactor Cronjob table
truenas/webui pull request #8447
Opened 2023-07-17 11:49 UTC by denysbutenko

2023-07-17 11:50 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122923

2023-07-17 15:43 UTC, undsoft requested changes
Looks good so far.

I think we should:
1. Prevent user from unselecting all columns.
2. Do not select all columns by default, and select limited set like we used to have.

2023-07-17 15:43 UTC, undsoft commented on src/app/pages/system/advanced/cron/cron-list/cron-list.component.html
> +    <ix-table-columns-selector [columns]="columns" (changed)="columnsChanged()"></ix-table-columns-selector>
If you rename `(changed)` to `(columnsChange)` we may be able to use [two way binding](https://angular.io/guide/two-way-binding) here.

2023-07-17 15:43 UTC, undsoft commented on src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
> +    // }),
Let's keep to one column/row.

2023-07-17 15:43 UTC, undsoft commented on src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
> +          const cronSchedule = `${job.schedule.minute} ${job.schedule.hour} ${job.schedule.dom} ${job.schedule.month} ${job.schedule.dow}`;
There is `scheduleToCrontab` that you can use.

2023-07-19 15:50 UTC, undsoft approved these changes
When new cron job is added list is not updated.

Other than that looks good.

2023-07-19 15:50 UTC, undsoft commented on src/app/modules/ix-table2/components/ix-table-columns-selector/ix-table-columns-selector.component.ts
> +  ngOnInit(): void {
Still valid. Best to make sure this component properly responds to `ngOnChanges`.

2023-07-19 15:50 UTC, undsoft commented on src/app/modules/ix-table2/components/ix-table-columns-selector/ix-table-columns-selector.component.ts
> +  @Input() columns!: Column<T, ColumnComponent<T>>[];
Exclamation mark doesn't do much in our codebase.

2023-07-19 15:50 UTC, undsoft commented on src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
> +  styleUrls: ['./cron-list.component.scss'],
changeDetection: onPush

2023-07-19 18:14 UTC, denysbutenko commented on src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-schedule/ix-cell-schedule.component.spec.ts
> +      } as Partial<IxCellScheduleComponent<TestTableData>>,
Other specs are used this way too. `setRow` is being used below in test case.

2023-07-19 18:32 UTC, merged

2023-07-20 09:22 UTC, undsoft commented on src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-schedule/ix-cell-schedule.component.spec.ts
> +      } as Partial<IxCellScheduleComponent<TestTableData>>,
Other specs are incorrect too :)