NAS-123274: Remove usages of CoreService for getting disk temperatures
truenas/webui pull request #8503
Opened 2023-07-31 13:57 UTC by bvasilenko

**Testing**

Emulating "Enclosure":
1. run `yarn ui mock -e`
2. run `yarn ui mock-enclosure -e`
3. navigate to **System Settings > Enclosure**

**Expected result:** Disk temperatures should still be fetched every N seconds, according to the new approach. So please test the closure page to make sure that temperatures are still updated properly. `

2023-07-31 13:57 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123274

2023-08-03 13:38 UTC, RehanY147 requested changes
This logic is very complicated to understand. I think since we are in the area, we can do a refactor of the `DiskUpdateService` and make it a store. Also, make the logic in `DiskTemperaturesService` a bit more easier to understand.

2023-08-03 13:38 UTC, RehanY147 commented on src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
> +    this.diskTemperatureService.temperature$.pipe(untilDestroyed(this)).subscribe((data) => {
We shouldn't make the subject public. Instead, let's make the subject private and make an observable of the subject public.

2023-08-03 13:45 UTC, RehanY147 commented
@bvasilenko You can disregard my last review. I will create a new ticket for that.
Also, can you give me a more specific instructions on what to test for? I have a mock system, so I don't know how I am going to check for changing temperature updates etc.

2023-08-04 14:58 UTC, bvasilenko commented
> You can disregard my last review. I will create a new ticket for that.

Ok!

> Also, can you give me a more specific instructions on what to test for? I have a mock system, so I don't know how I am going to check for changing temperature updates etc.

3. navigate to **System Settings > Enclosure**

![image](https://github.com/truenas/webui/assets/20611516/165e4667-2d13-4cb4-a905-a028a285e763)

4. switch to **Temperature** view
<img width="127" alt="image" src="https://github.com/truenas/webui/assets/20611516/37c51f84-f751-4691-980d-d77ffa22f243">

2023-08-08 18:35 UTC, RehanY147 approved these changes

2023-08-08 18:40 UTC, RehanY147 requested changes
Same request is being made twice every N seconds. Plase review.

2023-08-09 05:50 UTC, bvasilenko commented
@RehanY147 now requested changes should be done

2023-08-11 01:18 UTC, RehanY147 approved these changes

2023-08-11 05:25 UTC, merged

2023-08-11 05:26 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-123274 is targeted to the following versions which have not received their corresponding PRs: 24.04