NAS-123278 / 24.04 / `zfs.snapshot.query` `REMOVED` event will not include child snapshots
truenas/webui pull request #8529
Opened 2023-08-03 15:00 UTC by AlexKarpov98

I checked that this ticket will not break anything on the UI since we don't use `{"recursive": true}` option.
But I found out that subscribing to updates, will not update the list
// event.fields is not sent for some reason and that's why list is not updated, so this gonna help

So I came up with an idea. (check code changes)

2023-08-03 15:01 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123278

2023-08-07 07:57 UTC, denysbutenko approved these changes
The ticket requirements and PR content are confusing. So, I checked if the snapshot list is updating in different scenarios:

The snapshot list is updated when:

- a new snapshot is added
- an existing snapshot is deleted

The snapshot list is NOT updated when:

- snapshot is cloned

Also, there is [a middleware PR#11797](https://github.com/truenas/middleware/pull/11797) that addresses missing fields for `zfs.snapshot.query` event.

2023-08-07 10:12 UTC, undsoft requested changes
Appears to be not needed after recent middleware changes.

2023-08-11 10:37 UTC, AlexKarpov98 commented
It's tested with latest MiddleWare updates --> and is working fine now.
`event.fields` are included.

<img width="577" alt="Screenshot 2023-08-11 at 13 37 07" src="https://github.com/truenas/webui/assets/22980553/e6f9f4da-1dc4-453b-8cfc-d885c71ed510">

2023-08-11 10:37 UTC, closed without merging