NAS-123351: Takeout `checkForUpdate`
truenas/webui pull request #8537
Opened 2023-08-07 06:58 UTC by bvasilenko

**Summary**

After refactoring, the `checkForUpdate` was moved to a place in code, which was out of reach of `untilDestroy` pipe.

Moveover, the call `checkForUpdate` was waiting for the sys info to be fetched, without need to do so.

**Testing**

1. Tweak the code to simulate delayed error in `checkForUpdate`
2. Drop update-related keys from your `sessionStorage`
3. Go to Dashboard, not stay too long
4. Quickly navigate from Dashboard to any other page (/system/services, /storage/, ...)

**Expected result:**
Once you left Dashboard page, you should never see an pop-up with an error from Pt "1"

2023-08-07 06:58 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123351

2023-08-07 12:09 UTC, undsoft requested changes
I think there is another problem. This error doesn't have error handling, yet error is shown.
We do this in `handleError` in `ErrorHandlerService`, I think it is too much.

2023-08-07 17:40 UTC, bvasilenko commented
@undsoft now requested changes should be addressed

2023-08-08 08:04 UTC, undsoft requested changes
It is better to remove showing dialog in `ErrorHandlerService.handleError()`. I think it's better not to show error dialog on every JS error.

2023-08-09 10:43 UTC, undsoft approved these changes
Looks good.

2023-08-09 10:43 UTC, undsoft commented on src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
> +      error: (err) => {
Error handler can be removed, uncaught errors will be logged to sentry automatically.

2023-08-10 12:42 UTC, merged