NAS-123426: Fix default home path
truenas/webui pull request #8621
Opened 2023-08-18 03:55 UTC by bvasilenko

**Testing**

1. Setup a home share
   1. On the **Shares** page, at the **Windows SMB Shares** block, click **Add*
   2. Expand **Advanced Options** and put a check into **Use As Home Share** checkbox
2. On the **Credentials > Local Users** page, click **Add**
**Expected result:**
- I*Home directory** field automatically updated with the path to your share and the username
- Form can be submitted without errors

2023-08-18 03:56 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123426

2023-08-18 09:50 UTC, RehanY147 requested changes
The form can be submitted and the home directly is filled in but I'm confused about what you said

> Home directory field automatically updated with the path to your share and the username

What about the username? I don't see anything about a username. Please elaborate.

2023-08-21 09:18 UTC, bvasilenko commented
@RehanY147 I've rewritten the testing instructions, please check the updated steps

2023-08-24 11:10 UTC, RehanY147 approved these changes

2023-08-24 19:23 UTC, merged