NAS-121614: Add usage columns to apps
truenas/webui pull request #8763
Opened 2023-09-05 21:19 UTC by AlexKarpov98

Testing: see installed apps usage columns

2023-09-05 21:19 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121614

2023-09-08 10:38 UTC, RehanY147 requested changes
<img width="1493" alt="image" src="https://github.com/truenas/webui/assets/24204846/dacd0d28-8ce0-4838-bc68-abc057d040df">
The values are mushed together

2023-09-08 10:39 UTC, AlexKarpov98 commented
> <img alt="image" width="1493" src="https://user-images.githubusercontent.com/24204846/266583702-dacd0d28-8ce0-4838-bc68-abc057d040df.png"> The values are mushed together

tell me which machine did you use

2023-09-08 22:10 UTC, RehanY147 approved these changes
Looks good but tests failing

2023-09-11 08:51 UTC, merged