NAS-124066: Refactor Cloud Sync Tasks in Data Protection
truenas/webui pull request #8880
Opened 2023-09-19 10:33 UTC by AlexKarpov98

Testing: check Data protection -> Cloud Sync tasks

2023-09-19 10:34 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124066

2023-09-21 08:01 UTC, denysbutenko requested changes
Observed unexpected glitches on the state button.

https://github.com/truenas/webui/assets/351613/56b5e84a-3c5c-4270-961c-ab1caf0970d4

When clicked on the `Running` state it shows Logs dialog instead of job progress.

![image](https://github.com/truenas/webui/assets/351613/754540ef-97b1-4b32-9309-385a88e135c3)

2023-09-21 08:22 UTC, denysbutenko commented
There also color mismatch between `Running` state on Dashboard and full page table:

![image](https://github.com/truenas/webui/assets/351613/3edd109f-5ef5-4a55-a065-0129bad4fc7e)
![image](https://github.com/truenas/webui/assets/351613/0b864343-2c54-488b-9fdc-4beb75b13bb2)

2023-09-21 08:26 UTC, AlexKarpov98 commented
> There also color mismatch between `Running` state on Dashboard and full page table:
> 
> 
> 
> ![image](https://github.com/truenas/webui/assets/351613/3edd109f-5ef5-4a55-a065-0129bad4fc7e)
> 
> ![image](https://github.com/truenas/webui/assets/351613/0b864343-2c54-488b-9fdc-4beb75b13bb2)
> 
> 

I think running looks better with the primary color rather than with orange, i will check

2023-09-21 11:15 UTC, AlexKarpov98 commented
`When clicked on the Running state it shows Logs dialog instead of job progress.`
@denysbutenko - I believe that this should be handled as separate ticket.
This button was developed separately. [https://ixsystems.atlassian.net/browse/NAS-124146]

2023-09-21 11:51 UTC, AlexKarpov98 commented
@denysbutenko - please have a look at it now

2023-09-21 12:26 UTC, denysbutenko approved these changes
Other looks good.

2023-09-21 12:26 UTC, denysbutenko commented on src/app/modules/ix-table2/interfaces/table-column.interface.ts
> +  type?: new (matDialog?: MatDialog, translate?: TranslateService, dialogService?: DialogService) => C;
Following this approach does not looks good. For every specific need it is extending common component. Maybe [inject](https://angular.io/api/core/inject) function can help to get necessary services in the state button component and keep this clean?

2023-09-21 16:02 UTC, merged