ES102S enclosure support in CORE
truenas/webui pull request #8907
Opened 2023-09-21 13:41 UTC by dszidi

Testing:

Find an iXsystems controller with ES102S attached and check to see that enclosure management UI works for that enclosure

2023-09-21 13:41 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122712

2023-09-25 14:42 UTC, denysbutenko requested changes
Tested on m40 system from ticket.

![image](https://github.com/truenas/webui/assets/351613/4c681e04-1541-4da1-94ec-5cbc3b42689c)

Getting this error on view enclosure page.

Also, from console:
![image](https://github.com/truenas/webui/assets/351613/1896190c-dbfa-468f-9329-b639f0278478)

2023-09-26 18:05 UTC, dszidi commented
Sorry for the confusion. Middleware was missing. I had to install 13.1 nightlies onto the box. Please test again with UI pointing to `10.220.16.62`

2023-09-27 05:49 UTC, denysbutenko approved these changes
![image](https://github.com/truenas/webui/assets/351613/93eff0bd-3cb9-40b5-8514-99c4c240fdd2)

LGTM

2023-09-27 10:10 UTC, merged