NAS-124183: Unsubscribe from 'reporting.realtime' after leaving the dashboard
truenas/webui pull request #8928
Opened 2023-09-24 18:28 UTC by bvasilenko

**Testing**

Please see ticket

2023-09-24 18:28 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124183

2023-09-25 11:32 UTC, RehanY147 requested changes
We can make the service module scoped and add the `untilDestroyed` pipe in the subscriptions on the service.

2023-09-26 19:06 UTC, bvasilenko commented
@RehanY147 I suggest to keep the code as it is, for the sake of simplicity

2023-09-27 06:39 UTC, RehanY147 approved these changes

2023-09-27 06:39 UTC, RehanY147 commented on src/app/pages/dashboard/components/dashboard/dashboard.component.ts
> +    this.resourcesUsageStore$.subscribeToResourceUsageUpdates().pipe(untilDestroyed(this)).subscribe();
I think the previous method name still works and is better than this one.

2023-09-28 19:00 UTC, merged