NAS-124306: Show explicit values in columns with relative dates in ix-tables2
truenas/webui pull request #8945
Opened 2023-09-26 13:15 UTC by AlexKarpov98

Testing: 
See some of the changes in code and in app.

<img width="1727" alt="Screenshot 2023-09-26 at 16 03 30" src="https://github.com/truenas/webui/assets/22980553/247b2463-ac13-46c0-b77b-eeca999a108a">

2023-09-26 13:15 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124306

2023-09-27 06:12 UTC, bvasilenko requested changes
Looks good overall.

Please look for a way to shorten the "time ago" text. For example, by omitting the "about"  word in the beginning of the phrase.

```
5 hours ago
```

instead of "about 5 hours ago"

2023-09-27 09:00 UTC, bvasilenko approved these changes
LGTM

2023-09-27 10:03 UTC, undsoft approved these changes
Looks good.

2023-09-28 08:37 UTC, merged