NAS-124232: Added query param to fetch `display_available` attribute
truenas/webui pull request #8956
Opened 2023-09-27 12:51 UTC by RehanY147

Wait for https://github.com/truenas/middleware/pull/12200 to be ported to `cobia` before testing

2023-09-27 12:51 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124232

2023-09-27 13:46 UTC, yocalebo requested changes

2023-09-27 13:46 UTC, yocalebo commented on src/app/pages/vm/vm-list/vm-list.component.ts
> +      retrieve_display_available_info: true,
Hold off on this change. I've asked the middleware PR to remove the extra query params as I don't believe it's helpful. We should just show the `display_available` key by default.

2023-09-28 16:45 UTC, yocalebo commented on src/app/pages/vm/vm-list/vm-list.component.ts
> +      retrieve_display_available_info: true,
Okay, you don't need to specify these extra params in the query. The `display_available` key will be there by default now.

2023-10-01 10:31 UTC, denysbutenko commented
@RehanY147 do we have Cobia nightly builds for testing or perhaps there is a system available with the changes?

2023-10-02 06:07 UTC, RehanY147 commented
@denysbutenko I'm not sure. You'd have to ask Evgeny

2023-10-03 04:38 UTC, denysbutenko approved these changes
No luck to find a system with a build includes the changes and VM support for testing. Let's move on.

2023-10-03 14:28 UTC, undsoft requested changes
So what about other usage of `checkDisplay` where it is used to decide whether port number is shown?

2023-10-04 09:29 UTC, undsoft approved these changes

2023-10-04 11:12 UTC, merged