NAS-124362: Simplify data loading boilerplate for ix-table2
truenas/webui pull request #8985
Opened 2023-10-02 06:23 UTC by bvasilenko

**Testing**

Check the described functionality in the table2 on user's page, 
Also please check other pages, where the table2 is used.

2023-10-02 06:24 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124362

2023-10-02 13:06 UTC, undsoft requested changes
I think there are conceptual issues with this approach.
1. I don't think `setEmptyType` or `isLoading$` belongs to `ArrayDataProvider`. `ArrayDataProvider` doesn't really know about loading rows.
2. You've integrated empty directive inside of `ix-table2`. I'd prefer to keep it out and to simplify the directive (or create a new one). Not every table will need a loading indication or a message for empty rows, so it's not really part of the core package.
3. It may be a good idea to use some other page as an example. User list takes loading states and errors from the store, which is unusual when compared to most other pages. Most other pages just load something from `ws.call`.

I would try to implement a new async data provider to have loading statuses in it and I would try to create new/simplify the ix-empty directive.

2023-10-10 07:08 UTC, undsoft requested changes
Requesting changes as per our discussion. Let's experiment with creating a new `AsyncDataProvider` alongside with `ArrayDataProvider`. They both will derive from common interface, but AsyncDataProvider will know about loading data and loading status. It will take in an observable and spit out information necessary to render empty state.

Empty state should be a separate directive or component and should not be a part of ix-table core, because not every table will need it.

2023-10-11 19:53 UTC, bvasilenko commented
@undsoft the requested changes should be addressed now

2023-10-12 07:52 UTC, undsoft requested changes
Direction is correct overall.

2023-10-12 07:52 UTC, undsoft commented on src/app/modules/ix-table2/async-data-provider.ts
> +  private _subscription = new Subscription();
underscore in front of the property name is not recommended.

2023-10-12 07:52 UTC, undsoft commented on src/app/modules/ix-table2/async-data-provider.ts
> +  get emptyType$(): Observable<EmptyType> {
BehaviourSubject is already an observable. Can you use it directly and just mark property as `readonly`?

2023-10-12 07:52 UTC, undsoft commented on src/app/modules/ix-table2/async-data-provider.ts
> +  private _emptyType$ = new BehaviorSubject<EmptyType>(EmptyType.Loading);
Should we also expose `isLoading$` and `error$`? What do you think.

2023-10-13 16:08 UTC, undsoft requested changes
I think I forgot to write all my comments last time. I think we shouldn't do:
```
this.dataProvider.emptyType$.pipe(untilDestroyed(this)).subscribe(() => this.cdr.markForCheck());
```
This feels like a workaround. I'd rather table would handle change detection on its own. If we need to update `TableProvider` interface to use observables for rows, we can do that.
Array data provider can still have `setRows(rows)` as it currently has.

2023-10-16 10:14 UTC, bvasilenko commented
@undsoft the last remark should be fixed now, and this PR now includes other pages

2023-10-16 10:37 UTC, undsoft approved these changes
The only issue that I see is that with new approach calling `refresh()` will have a side effect of executing everything in the original observable chain.
The way its currently written it may not be immediately obvious to the developer that calling `refresh` in say `getCronJobs` will execute `tap((cronjobs) => this.cronjobs = cronjobs)` in a different method.

But it's still an improvement over what we previously had and we can fix this in other tickets. Thanks.

2023-10-17 07:29 UTC, bvasilenko commented
> The way its currently written it may not be immediately obvious to the developer that calling refresh in say getCronJobs will execute tap((cronjobs) => this.cronjobs = cronjobs) in a different method.

@undsoft Ok, I will address this request in my next table2 ticket

2023-10-17 07:29 UTC, merged