NAS-124423: Add client_id and client_secret to Google Photos cloud credentials
truenas/webui pull request #9014
Opened 2023-10-04 13:21 UTC by AlexKarpov98

Testing:
For Google Photos Cloud Credentials - form should be without `Login To Provider` button and `Client ID` and `Client Secret` should be required.
<img width="485" alt="Screenshot 2023-10-04 at 16 20 10" src="https://github.com/truenas/webui/assets/22980553/cf146c23-2403-4b98-af7c-53a95f52ab76">

2023-10-04 13:21 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124423

2023-10-04 15:47 UTC, bvasilenko requested changes
The UI looks good.
However I wasn't able to submit the form by following this documetation: https://www.truenas.com/community/resources/creating-custom-google-photos-api-credentials-for-cloud-sync-task.188/

1. fill client ID
2. fill client Secret 
3. run`rclone` to generate token
4. fill Token
5. Click "save"

**Expected result:** form submitted

**Actual result:** data not submitted to middleware , progress indicator displayed forever


https://github.com/truenas/webui/assets/20611516/88bbcc8a-946e-4e8c-8923-53c1203a6772

2023-10-04 15:49 UTC, AlexKarpov98 commented
> The UI looks good.
> 
> However I wasn't able to submit the form by following this documetation: https://www.truenas.com/community/resources/creating-custom-google-photos-api-credentials-for-cloud-sync-task.188/
> 
> 
> 
> 1. fill client ID
> 
> 2. fill client Secret 
> 
> 3. run`rclone` to generate token
> 
> 4. fill Token
> 
> 5. Click "save"
> 
> 
> 
> **Expected result:** form submitted
> 
> 
> 
> **Actual result:** data not submitted to middleware , progress indicator displayed forever
> 
> 
> 
> 
> 
> https://github.com/truenas/webui/assets/20611516/88bbcc8a-946e-4e8c-8923-53c1203a6772
> 
> 
> 
> 

I tested this form without my changes on master and cobia. It's not submitting as well.
@undsoft - do you know what can it be?

2023-10-04 18:34 UTC, undsoft requested changes
There is a regression in base-provider-form. You need to rollback last changes in `beforeSubmit`.

2023-10-04 18:34 UTC, undsoft commented on src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.html
> +          [disabled]="areActionsDisabled || !isFormValid || isLoading"
Additional conditions should be part of `areActionsDisabled`.

2023-10-04 18:34 UTC, undsoft commented on src/app/pages/credentials/backup-credentials/cloud-credentials-form/oauth-provider/oauth-provider.component.ts
> +  get isGooglePhotosProvider(): boolean {
No point in changing this component since it's very different from the original implementation. You need to create a new component.

2023-10-04 18:34 UTC, undsoft commented on src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts
> +      return Boolean(this.submissionAttributes.client_secret && this.submissionAttributes.client_id);
Doesn't belong here, validation belongs to provider form.

2023-10-04 19:11 UTC, AlexKarpov98 commented
@undsoft @bvasilenko - please check it now

2023-10-05 07:47 UTC, bvasilenko approved these changes
UI works good for me.

@undsoft However middleware has a bug, **cloudsync.credentials.verify** returns `valid: true` for invalid credentials  `ID = 1, Secret = 2, Token = {}`

2023-10-05 13:28 UTC, undsoft approved these changes
Form works correctly.

2023-10-05 13:28 UTC, merged