Sync email validation rules WebUI/Middleware
truenas/webui pull request #9021
Opened 2023-10-06 06:06 UTC by bvasilenko

2023-10-06 06:06 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-113941

2023-10-06 08:03 UTC, denysbutenko requested changes
Let's add unit tests for new validator.

2023-10-06 09:43 UTC, denysbutenko reviewed
However, it works well while basic checking. Consider of replacing builtin validator with new one for other components.

2023-10-06 09:46 UTC, denysbutenko commented
As final point would be good to prevent using built-in validator in the future. Take a look on eslint config, specifically at `no-restricted-syntax` that allows add linter rule for this case.

2023-10-09 14:28 UTC, bvasilenko commented
Ok, requested changes should be addressed now

2023-10-11 07:50 UTC, undsoft approved these changes
Looks good.

2023-10-11 07:50 UTC, undsoft commented on src/app/modules/ix-forms/validators/email-validation/email-validation.spec.ts
> +  it('should return an error when value is valid email', () => {
when value is invalid email.

2023-10-16 04:42 UTC, denysbutenko approved these changes
Looks good. Thanks for adding tests and linter rule.

2023-10-16 06:11 UTC, merged