NAS-124608: Add a note explaining how to configure session timeout
truenas/webui pull request #9045
Opened 2023-10-13 11:30 UTC by AlexKarpov98

Testing: 
Check Session expiring modal and see an updated like below:

<img width="470" alt="Screenshot 2023-10-13 at 14 12 00" src="https://github.com/truenas/webui/assets/22980553/da84ef5d-4e4a-4943-9e32-2d19b43be561">

Click `Advanced Settings → Sessions`, you shall be redirected to the card (highlighted)

<img width="832" alt="Screenshot 2023-10-13 at 14 29 40" src="https://github.com/truenas/webui/assets/22980553/eb99f2dd-287c-4926-9aa0-e920e3f53fba">

2023-10-13 11:30 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124608

2023-10-13 14:55 UTC, undsoft commented on src/app/modules/common/dialog/session-expiring-dialog/session-expiring-dialog.component.html
> +      <b (click)="viewSessionsCard()">
Needs to look like a link so that people know to click it.

2023-10-13 23:17 UTC, RehanY147 requested changes
The link takes out straight to the settings page. Was the session extended in that case? Or not? It's vague. We should also mention what will happen if they just click the link right away.

2023-10-14 08:19 UTC, AlexKarpov98 commented
@RehanY147 

yes, session is extended in this case.
We may add Text about it but I don't think it's necessary (my opinion). 
Can you provide a text in this case if you think it's needed?

2023-10-16 12:24 UTC, AlexKarpov98 commented
@RehanY147 
<img width="610" alt="Screenshot 2023-10-16 at 15 22 44" src="https://github.com/truenas/webui/assets/22980553/c0d1353d-33e5-4d70-9612-dc1102d2d7b5">

2023-10-20 12:00 UTC, undsoft approved these changes
Looks good.

2023-10-21 00:57 UTC, RehanY147 approved these changes

2023-10-21 00:57 UTC, merged