NAS-124670: Reporting disks view improvements for large disk systems
truenas/webui pull request #9076
Opened 2023-10-19 14:56 UTC by AlexKarpov98

Testing: See updated select component with "Select All" option.

<img width="259" alt="Screenshot 2023-10-19 at 17 41 41" src="https://github.com/truenas/webui/assets/22980553/39e93070-e07d-47cd-90e0-8714740f480f">

<img width="1728" alt="Screenshot 2023-10-19 at 17 41 32" src="https://github.com/truenas/webui/assets/22980553/43172efc-d8d8-44ad-bd3d-3653b419526e">

2023-10-19 14:57 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124670

2023-10-25 19:01 UTC, undsoft requested changes
It works, but 1) icon doesn't match the result of the select options 2) I don't think we need it by default

2023-10-26 22:02 UTC, AlexKarpov98 commented
> It works, but 1) icon doesn't match the result of the select options 2) I don't think we need it by default

I agree, PR is updated now 😺 (and images descriptions)

2023-10-27 11:07 UTC, undsoft approved these changes
Looks good, thanks.

2023-10-27 11:07 UTC, merged