NAS-124740: Refactoring InitShutdownListComponent
truenas/webui pull request #9092
Opened 2023-10-21 13:39 UTC by undsoft

Testing: test InitShutdownListComponent.
Timeout column removed deliberately.

2023-10-21 13:39 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124740

2023-10-23 06:17 UTC, bvasilenko requested changes
Works good overall.

Noticed an issue with **Delete script > Cancel** : It still deletes , despite that Cancel was clicked.

2023-10-23 14:42 UTC, undsoft commented
@bvasilenko Good catch, but I think you tested the wrong table. This one is the one you get to by clicking on table header.

2023-10-25 07:48 UTC, bvasilenko approved these changes
Works good!

2023-10-25 07:53 UTC, merged