NAS-124948: Add warning to Sync setting
truenas/webui pull request #9148
Opened 2023-11-01 12:47 UTC by AlexKarpov98

Testing: 
See ticket
<img width="877" alt="Screenshot 2023-11-01 at 14 47 23" src="https://github.com/truenas/webui/assets/22980553/976a8831-25a0-4eab-ad12-082c6fa311f6">

2023-11-01 12:47 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124948

2023-11-02 08:53 UTC, undsoft requested changes
If you create a dataset with Sync = Disabled and then try to edit it, you'll get a warning again.

2023-11-02 08:53 UTC, undsoft commented on src/app/modules/common/dialog/confirm-dialog/confirm-dialog.component.html
> +    *ngIf="options.buttonText"
I don't think it's necessary. We already have `hideCancel`. The button in the dialog should say something like `Okay` instead of `Cancel`.

2023-11-02 17:46 UTC, undsoft approved these changes
👍🏻

2023-11-03 08:54 UTC, merged

2023-11-03 08:55 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-124948 is targeted to the following versions which have not received their corresponding PRs: 23.10.1

2023-11-04 07:39 UTC, AlexKarpov98 commented
backport-23.10.1