NAS-124962 / 24.04 / Fix scrolling on pane-details layout
truenas/webui pull request #9159
Opened 2023-11-02 13:39 UTC by AlexKarpov98

Testing:
Check ticket and all related pages with similar layout:
- Datasets
- Devices
- Apps
- Audit

Upon scroll you should see search & table header sticked to the top while scrolling.
There should be less scrollbars or only one (to control the page scroll)

2023-11-02 13:40 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124962

2023-11-03 09:33 UTC, undsoft requested changes
Details side panel also need to stick to the top and not just scroll through:
<img width="1792" alt="Снимок экрана 2023-11-03 в 10 24 12" src="https://github.com/truenas/webui/assets/1481270/895dffeb-54e1-4f08-9d06-2da38be48cfd">

This may be outside of the scope of this ticket because of virtual scrolling, but I think scrolling on Datasets page can be improved. Try with `APPS/a-lot-of-datasets` on our m40.

2023-11-03 09:33 UTC, undsoft commented on src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.html
>      [hidden]="isLoading"
Perhaps somebody was trying to write `[class.hidden]` the line below?

2023-11-03 12:24 UTC, AlexKarpov98 commented
@undsoft - separate ticket is created to handle virtual scroll behaviour.
https://ixsystems.atlassian.net/browse/NAS-125044

2023-11-06 13:36 UTC, undsoft requested changes
Seems like I shouldn't have scrolling in details panel here, since there is enough space to render everything when scrolled up.

https://github.com/truenas/webui/assets/1481270/d2c8e697-01f9-41a3-addb-6407e884b345

2023-11-07 10:00 UTC, undsoft approved these changes
Let's add a little more space here, so that it's not so up there. 
<img width="1023" alt="Снимок экрана 2023-11-07 в 10 59 50" src="https://github.com/truenas/webui/assets/1481270/debeb9d3-79f0-452d-b9c6-0d2cc67ad023">

Otherwise looks good.

2023-11-07 11:53 UTC, merged