NAS-123593: New AlertSettings page
truenas/webui pull request #9166
Opened 2023-11-04 10:17 UTC by RehanY147

2023-11-04 10:17 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123593

2023-11-07 03:53 UTC, denysbutenko requested changes
Good mockup. I posted feedback in the Slack channel.

2023-11-18 12:37 UTC, RehanY147 commented
@denysbutenko  The designs are approved. I've added another ticket to adjust and refactor Alert Services table. With that ticket, the old Alert Settings page will be replaced with the new Alert Settings Component

2023-11-20 13:49 UTC, denysbutenko approved these changes

2023-11-20 13:49 UTC, merged