NAS-124985: Removing mutability of state object
truenas/webui pull request #9167
Opened 2023-11-04 14:17 UTC by RehanY147

2023-11-04 14:17 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124985

2023-11-07 18:32 UTC, dszidi requested changes
Spares step should be hidden if data vdevs type is draid

<img width="2224" alt="image" src="https://github.com/truenas/webui/assets/29865743/f869f0a8-3289-42b2-b005-c7bf497287d8">

2023-11-09 23:28 UTC, dszidi approved these changes
LGTM

<img width="1873" alt="image" src="https://github.com/truenas/webui/assets/29865743/e8b447b5-d25e-4b50-a597-af9bcb411706">

2023-11-10 06:05 UTC, merged

2023-11-10 06:06 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-124985 is targeted to the following versions which have not received their corresponding PRs: 23.10.1

2023-11-10 06:06 UTC, RehanY147 commented
backport