Privileges management UI
truenas/webui pull request #9194
Opened 2023-11-13 05:56 UTC by bvasilenko

**Testing**

See ticket

2023-11-13 05:56 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125090

2023-11-13 09:03 UTC, undsoft requested changes
Looks good overall and works okay, but I think we should make improvements for some of the fields in the form.

2023-11-13 09:03 UTC, undsoft commented on src/app/pages/account/groups/privilege/privilege-form/privilege-form.component.html
> +          [label]="'Web Shell' | translate"
Let's call it 'Web Shell Access'

2023-11-13 09:03 UTC, undsoft commented on src/app/pages/account/groups/privilege/privilege-list/privilege-list.component.scss
> +    background: var(--bg2);
Seems very specific.

2023-11-13 09:03 UTC, undsoft commented on src/app/pages/account/groups/group-list/group-list.component.html
> +      color="primary"
Let's make it a non-primary button and move it after Add button.

2023-11-15 08:43 UTC, bvasilenko commented
@undsoft requested changes should be addressed now

2023-11-15 11:49 UTC, undsoft approved these changes
Overall looks good. Two small items before we can merge:
1. Some built-in groups cannot be removed. Trying to remove them will result in an API error. We can hide delete button for those items based on whether `builtin_name` is set.
2. Privileges button needs to be in gray and go after `Show Built-in Groups` on groups page.

2023-11-15 14:33 UTC, AlexKarpov98 commented on src/app/pages/account/groups/privilege/privilege-form/privilege-form.component.ts
> +    map((roles) => roles.map((role) =>({ label: role.title, value: role.name }))),
**=>({**
Space is missing **=> ({**

2023-11-16 10:00 UTC, merged