NAS-124826: Using rawvalue instead of value
truenas/webui pull request #9195
Opened 2023-11-13 07:34 UTC by RehanY147

When editing a dataset, set value for the `Metadata (Special) Small Block Size` field in the `Advanced Fields`. Save the form successfully and then edit it again. The field should be populated with the last saved value.

2023-11-13 07:35 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124826

2023-11-13 08:03 UTC, undsoft requested changes
It looks good, but while testing I've noticed another bug not related to your changes.
If I set field to 512B and then switch back to Inherit (0), it will not be correctly shown as inheriting.

2023-11-13 09:08 UTC, RehanY147 commented
@undsoft If I set that value to Inherit and send that with the payload to middleware, later on, when the dataset is fetched again, it just reports the value to be 0. No mention that it was inherited.

2023-11-13 09:23 UTC, undsoft requested changes
Middleware correctly reports value source as Default when you do this.
See `getFieldValue`.

2023-11-15 11:37 UTC, undsoft approved these changes
Works correctly now.

2023-11-15 11:37 UTC, undsoft commented on src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts
> +    if (specialSmallBlockSize !== 'INHERIT') {
It seems you are only interested in whether value was inherited. It's worth extracting relevant code from `valueOrInherit` into a new method.

2023-11-15 13:08 UTC, RehanY147 commented
The value changes based on if it is inherited or not. So, that code needs to stay I think.

2023-11-15 14:46 UTC, merged