Create new tickets with FeedbackDialog
truenas/webui pull request #9205
Opened 2023-11-15 10:48 UTC by denysbutenko

- Add new component IxButtonGroup to ix-forms
- Merge FileTicketForm into Feedback Dialog
- Merge FileTicketLicensedForm into Feedback Dialog

For testing, ensure no regressions for feedback and ticket creation.

2023-11-15 10:48 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124666

2023-11-18 13:49 UTC, RehanY147 requested changes
The two forms are large enough that they should be their own smaller components to be used inside of the dialog component.

2023-11-28 10:37 UTC, denysbutenko commented
> The two forms are large enough that they should be their own smaller components to be used inside of the dialog component.

I wonder if that suggestion is a good idea. However, there is another PR with implementation using multiple components approach #9256. Please take a look at it.

2023-12-05 17:36 UTC, denysbutenko commented
Closing this PR since is outdated. See https://github.com/truenas/webui/pull/9256

2023-12-05 17:36 UTC, closed without merging