NAS-125141: Add support for options suggestions
truenas/webui pull request #9217
Opened 2023-11-18 12:00 UTC by AlexKarpov98

Testing: 
Visit Audit Logs page "Advanced Search"
http://localhost:4200/audit

https://github.com/truenas/webui/assets/22980553/394c6abd-b771-432a-8a27-2546af8682b7

2023-11-18 12:01 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125141

2023-11-20 13:06 UTC, undsoft requested changes
I like the look and feel.
I would prefer to connect to our grammar instead of tokenizing string again.
The following does not get correct suggestions: `Event IN ("UNLINK")`.

1. As you type you won't get suggestions for `IN` until it's too late and it does not understand `()`.
2. Can we show options right when person is about to type something instead of waiting for the first letter? I.e. as I focus on the field – show autocomplete for properties.
3. I think we can only show suggestions by beginning of the string. E.g. `Se` should not match `Username`.

2023-11-20 13:13 UTC, AlexKarpov98 commented on src/app/pages/audit/components/audit/audit.component.ts
> +          Object.values(AuditEvent).map((value) => `"${value}"`),
@undsoft  - I think we need suggestions per field, where can we put them then?

2023-11-20 13:17 UTC, undsoft commented on src/app/pages/audit/components/audit/audit.component.ts
> +          Object.values(AuditEvent).map((value) => `"${value}"`),
The initial idea was that we would create search properties for them. So `searchProperty` != column.
E.g. we would create a property called `SMB File` that would point to `event.event_data.host`.

2023-11-20 13:24 UTC, undsoft commented on src/app/pages/audit/components/audit/audit.component.ts
> +          Object.values(AuditEvent).map((value) => `"${value}"`),
Note that this may not be currently supported in other places.

2023-11-20 16:31 UTC, AlexKarpov98 commented on src/app/modules/search-input/components/advanced-search/advanced-search.component.ts
> +  private tokenizeQuery(query: string): string[] {
I can move it to the Query Parser for now (as additional method for getting data by cursor position)

2023-11-20 20:08 UTC, dszidi requested changes
So far it's coming along nicely. It correctly detects field and operator. However it doesn't seem to detect complete conditions. After I type in `Service=SMB ` it should be suggesting `AND` or `OR` but it instead suggests field values

<img width="806" alt="image" src="https://github.com/truenas/webui/assets/29865743/f84907f1-f079-4e7e-9d46-cd7439f9bc75">

2023-11-21 11:12 UTC, AlexKarpov98 commented on src/app/modules/search-input/components/advanced-search/advanced-search.component.ts
> +  private tokenizeQuery(query: string): string[] {
We need a way to get tokens one by one in one array, we have a query cursor and we need to get last tokens by cursor.

2023-11-21 11:13 UTC, AlexKarpov98 commented on src/app/pages/audit/components/audit/audit.component.ts
> +          auditEntries.map((log) => `"${log.address}"`),
> Do we need quotes here? Are they for if we want to have suggestions for numbers/booleans?
Values should be quoted in query, I did it to make values valid on autocompletion

Service=SMB --> invalid
Service="SMB" --> valie

2023-11-21 14:40 UTC, AlexKarpov98 commented on src/app/pages/audit/components/audit/audit.component.ts
> +          Object.values(AuditEvent).map((value) => `"${value}"`),
for now I leave them as part of textProperty
```
export function textProperty<T>(
  property: keyof T,
  label: string,
  valueSuggestions$?: Observable<Option[]>,
): SearchProperty<T> {
  return { label, property, valueSuggestions$ };
}
```

2023-11-21 15:54 UTC, AlexKarpov98 commented
@dszidi @undsoft  - please check the updated functionality now.


https://github.com/truenas/webui/assets/22980553/6cadfe02-abbd-4ed2-a72a-5d884723e96e

2023-11-21 18:27 UTC, dszidi reviewed
Looking good. It's now giving hints for value as well as `AND` and `OR`. 

The hint for timestamp only gives us `Tomorrow` which populates a value of 22. @undsoft we at one point discussed having a datepicker here. Are we still wanting to do that and is that in the scope of this ticket?

<img width="618" alt="image" src="https://github.com/truenas/webui/assets/29865743/01a5ed57-1d52-45a7-a601-71ab0524529c">

<img width="618" alt="image" src="https://github.com/truenas/webui/assets/29865743/ee4deab7-bc33-4010-a74c-9ccef0e68fb0">

2023-11-21 18:29 UTC, AlexKarpov98 commented
@dszidi - currently I added only one option for Timestamp in order to show custom label and value.
I think date picker should be out of the scope of this ticket I think
@undsoft

2023-11-22 11:43 UTC, AlexKarpov98 commented
getting tokens from lezer in needed format is complicated and requires more code to deal with all needed structure.

```
tokenizeQueryAsOneArray(input: string): string[] {
    const regex = /"[^"]*"|'[^']*'|\b(IN|in|NIN|nin|AND|OR)\b|!=|>=|<=|!^|!$|\^|\$|~=|>|<|=|\w+|\(\s*[^)]*/gi;
    return input.match(regex) || [];
  }
```

Current tokenizer is better and works fine.

I asked chat.gpt to exract tokens from lezer, and code it way more complex:
```
import { parser, SyntaxNode } from './your-generated-parser'; // Adjust the import to your parser file

function extractTokens(query: string): (string | number)[] {
  const tree = parser.parse(query);
  let tokens: (string | number)[] = [];

  function explore(node: SyntaxNode, isWithinParens: boolean = false): void {
    if (node.name !== 'space' && node.name !== '') {
      if (node.name === 'leftParenthesis') {
        // Start of a parenthetical group
        const endIndex = findClosingParenIndex(node);
        const groupText = query.slice(node.from, endIndex);
        tokens.push(groupText);
        skipToIndex(node, endIndex);
      } else if (!isWithinParens && !node.firstChild()) {
        // Process terminal nodes only outside of parentheses
        const text = query.slice(node.from, node.to);
        if (node.name === 'Number') {
          tokens.push(parseInt(text, 10)); // Convert numbers to integer
        } else {
          tokens.push(text); // Add the text of the node to the tokens array
        }
      } else {
        do {
          // Recursively explore child nodes
          explore(node, isWithinParens || node.name === 'leftParenthesis');
        } while (node.nextSibling());
        node.parent();
      }
    }
  }

  function findClosingParenIndex(node: SyntaxNode): number {
    let depth = 0;
    let currentNode = node;
    do {
      if (currentNode.name === 'leftParenthesis') {
        depth++;
      } else if (currentNode.name === 'rightParenthesis') {
        depth--;
      }
      if (depth === 0) {
        return currentNode.to;
      }
    } while (currentNode.nextSibling());
    return node.to; // Fallback, should not occur
  }

  function skipToIndex(node: SyntaxNode, index: number): void {
    while (node.from < index && node.nextSibling()) {}
    node.parent();
  }

  explore(tree.cursor());

  return tokens;
}

// Example usage
const query = 'Event IN ("AUTHENTICATION", "WRITE") AND ID = 1';
const tokens = extractTokens(query);
console.log(tokens);
```

2023-11-22 15:55 UTC, AlexKarpov98 commented
@dszidi  I added more useful data for Timestamp autocompletion 😄

2023-11-22 16:07 UTC, undsoft requested changes
It works okay for most cases, but I don't think it's a good idea to support another tokenizer. It's a bit like adding a new table component because there is an issue with one we already have. Lezer grammar was specifically used so that we could integrate it with codemirror.

Here's how you can get tokens in lezer:
```
private getQueryContext(query: string, cursorPosition: number): QueryContext {
    const tree = parser.parse(query);
    let condition: SyntaxNode;
    const stackDemo: string[] = [];
    let stackIterator = tree.resolveStack(cursorPosition, -1);
    while (stackIterator.next) {
      const node = stackIterator.node;
      stackDemo.push(node.name);
      if (node.name === ParsedToken.Condition) {
        condition = node;
      }

      stackIterator = stackIterator.next;
    }

    const comparator = condition?.getChild(ParsedToken.Comparator);
    const lastElement = tree.topNode.resolve(cursorPosition, -1);
    const lastInCondition = condition?.childBefore(cursorPosition);
    const hasProperty = condition?.getChild(ParsedToken.Property);
    const hasComparator = condition?.getChild(ParsedToken.Comparator);
    const hasValue = condition?.getChild(ParsedToken.Value);

    console.log(
      `Stack: ${stackDemo.toString()}`,
      '\n',
      `Current Condition: ${query.substring(condition?.from, condition?.to)}`,
      '\n',
      `Comparator: ${comparator ? query.substring(comparator.from, comparator.to) : 'No'}`,
      '\n',
      `Last typed element: ${lastElement?.name}`,
      '\n',
      `Last in condition: ${lastInCondition?.name}`,
      '\n',
      `Condition has: ${hasProperty ? 'Property' : ''} ${hasComparator ? 'Comparator' : ''} ${hasValue ? 'Value' : ''}`,
    );
```

Current usability issues:
* Doesn't suggest correctly in braces, e.g. `(Username = `
* When you type `Username = ` and add quotes yourself, it will insert another set of quotes if you select a suggestion.
* Would be good to start suggesting property name immediately after cursor is in search field.

2023-11-23 17:20 UTC, AlexKarpov98 commented
@undsoft  - please give it a shout now 😄

2023-11-24 09:15 UTC, undsoft approved these changes
Token parsing is not exactly how I saw it. We are still only using grammar to split string into string parts without actually relying on grammar to determine which token is underneath the cursor.
But it works nicely, so it's good to merge.
I will create other tickets for further UI improvements and may try to refactor to use grammar more.
Thanks.

2023-11-24 09:15 UTC, undsoft commented on src/app/modules/search-input/components/advanced-search/advanced-search.component.ts
> +    this.inputArea?.nativeElement?.removeEventListener('click', this.handleClickAndFocusEvent.bind(this), true);
Can we use native Angular (event)s?

2023-11-24 09:15 UTC, undsoft commented on src/app/modules/search-input/services/advanced-search-autocomplete.service.ts
> +                let updatedValue = suggestion.value.toString();
Would be good to extract this to a separate function.

2023-11-24 09:15 UTC, undsoft commented on src/app/modules/search-input/services/query-parser/query-parser.service.ts
> +    const tokenTypes = ['Property', 'Comparator', 'Value', 'Or', 'And', '⚠'];
ParsedToken enum

2023-11-24 17:18 UTC, merged