NAS-124897: Fix verify credentials in Cloud Credentials form
truenas/webui pull request #9218
Opened 2023-11-18 13:47 UTC by denysbutenko

For testing, go to Backup Credentials, edit SFTP credentials, and ensure that `cloudsync.credentials.verify` is sent to middleware.

2023-11-18 13:47 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124897

2023-11-21 17:56 UTC, RehanY147 requested changes
I opened an already existing SFTP credential to edit it, changed the host ip and clicked save. The request to verify was seen in the websocket calls.

2023-11-22 06:50 UTC, denysbutenko commented
@RehanY147 what would you like to change?

2023-11-22 11:14 UTC, denysbutenko commented
> Sorry, I meant to say the request was NOT seen in the websocket responses.

To ensure, it is when you've pressed the `Verify Credentials` button, right?

2023-11-22 11:23 UTC, RehanY147 approved these changes

2023-11-22 11:27 UTC, merged