NAS-125303: Differentiate between datasets and directories in file picker
truenas/webui pull request #9254
Opened 2023-11-28 07:29 UTC by bvasilenko

2023-11-28 07:29 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125303

2023-11-30 21:44 UTC, dszidi approved these changes
Seems to be working correctly and the new directory icon matches our designs.
LGTM

<img width="509" alt="image" src="https://github.com/truenas/webui/assets/29865743/3b42c9f4-ade3-491f-abd8-139565229040">


<img width="933" alt="image" src="https://github.com/truenas/webui/assets/29865743/4d4c6394-e14b-4867-8128-a077bab43f91">

2023-12-01 16:48 UTC, undsoft requested changes
`a`, `b` and `a-lot-of-datasets` appear to be datasets, not folders as shown in screenshot.

2023-12-04 06:18 UTC, bvasilenko commented
@undsoft @dszidi would you please provide output of these 3 commands 

```
call "filesystem.listdir" "/mnt/APPS/APPS/a"
call "filesystem.listdir" "/mnt/APPS/APPS/b"
call "filesystem.listdir" "/mnt/APPS/APPS/a-lot-of-datasets"
```

from the machine from where your screenshot is taken from?

2023-12-11 06:09 UTC, bvasilenko commented
@undsoft in that particular case it’s impossible to distinguish this particular dataset from a directory. 

Taking into account that
- this is rare edge case (replicated read-only file system)
- the problem exists in the middleware query `pool.dataset.query` which does not return these read-only replicated datasets in the list of datasets
- common user's expectations are that icon is rather cosmetical hint then a strict indication of whether this a directory or a dataset

I'd suggested to proceed with the merge

2023-12-11 08:57 UTC, undsoft requested changes
Mixing icons is confusing. We shouldn't do it.
Let's push middleware to try to solve this, if not we can discuss whether this is something we can solve on frontend.
The alternative is not to have this feature at all – it's better not to confuse the user.

2023-12-11 13:57 UTC, anodos325 commented on src/app/services/filesystem.service.ts
> +        this.ws.call('pool.dataset.query', [[], { select: ['mountpoint'] }]),
The filesystem.listdir output is correct. If the dataset is not mounted, then that component is not a dataset. It is a directory.

2023-12-13 14:37 UTC, undsoft requested changes
Okay, I've tested on m40. The old dataset is gone, so I cannot reproduce the original issue. It seems to work fine with old version (where it didn't query for datasets).
Let's see if we can incorporate https://ixsystems.atlassian.net/browse/NAS-125555?atlOrigin=eyJpIjoiMWY0YmUzMGEzZmI0NGQ4ZmI1ZjY0MmQ2NTJkZDFhNmUiLCJwIjoiaiJ9 in some way.

2023-12-14 05:35 UTC, bvasilenko commented
> Let's see if we can incorporate https://ixsystems.atlassian.net/browse/NAS-125555?atlOrigin=eyJpIjoiMWY0YmUzMGEzZmI0NGQ4ZmI1ZjY0MmQ2NTJkZDFhNmUiLCJwIjoiaiJ9 in some way.

@undsoft this is already done at commit https://github.com/truenas/webui/pull/9254/commits/2781a6debd1efe2457657c58e229033104289514#diff-bc2d1338cf9a61ec3d6f90e024f22dc0a955ee60106b3c1a5a1b93e0f9b60c3dR44

So I suppose it's ready to be merged

2023-12-15 06:10 UTC, bvasilenko commented
encrypted directory with "lock" icon:

<img width="336" alt="image" src="https://github.com/truenas/webui/assets/20611516/226823a1-f53d-48a0-bf9d-99ad7a4845d2">

2023-12-15 12:52 UTC, undsoft approved these changes
Looks good, thanks.

2023-12-17 19:24 UTC, merged