NAS-125305 / 24.04 / Create Dataset button in SMB form
truenas/webui pull request #9264
Opened 2023-11-30 06:28 UTC by bvasilenko

**Testing**
See ticket

2023-11-30 06:29 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125305

2023-11-30 08:56 UTC, undsoft requested changes
It works, but we can make some improvements.

1. I should only be able to create a dataset when what I have currently selected is a dataset and not a folder (created via mkdir for example) or a file (with getFilesystemNodeProvider directoriesOnly = false).
2. Let's add background to the area underneath Create Dataset like in screenshot in the ticket.
3. Let's make the dialog a bit wider.
4. If I select /mnt/parent and not expand it, after dataset is created via dialog, it would be good to expand, so that I can see my selection.

2023-11-30 08:56 UTC, undsoft commented on src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> +    acltype: DatasetAclType.Nfsv4,
There is a ShareType property to be used here instead. It's like a preset.
For SMB it should be `DatasetShareType.Smb` and for NFS - `DatasetShareType.Multiprotocol`.

2023-11-30 08:56 UTC, undsoft commented on src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
> +  @Input() canCreateDataset = false;
Also needs a test case for new properties.

2023-12-05 18:37 UTC, bvasilenko commented
@undsoft the look and feel of the button is closer to the design now:

<img width="379" alt="image" src="https://github.com/truenas/webui/assets/20611516/a4720982-ece9-44ab-921f-4dbaa46e5aba">

2023-12-06 09:04 UTC, undsoft approved these changes
Looks good, let's maybe do something about progressbar styles so that content doesn't jump when it appears.

2023-12-11 13:25 UTC, merged