Corrected test attribute for ix-table2 columns
truenas/webui pull request #9299
Opened 2023-12-09 09:43 UTC by RehanY147

2023-12-09 09:43 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124716

2023-12-11 09:11 UTC, undsoft requested changes
The direction is good. There are some things to improve to make various tables differentiate between themselves.

2023-12-11 09:11 UTC, undsoft commented on src/app/pages/account/users/user-list/user-list.component.ts
> +    rowTestId: (row: User) => row.uid.toString(),
We should also include what it is in test id, e.g. `user-1`, not just `1`

2023-12-11 14:34 UTC, denysbutenko reviewed
CI checks are stopped - I need the latest docker image for testing.

2023-12-12 10:06 UTC, undsoft approved these changes
Looks good, thanks. I'm sure automation engineers will appreciate it.

2023-12-12 10:06 UTC, merged