Storj Backup Widget
truenas/webui pull request #9306
Opened 2023-12-11 14:26 UTC by bvasilenko

**Summary**

4 states of the widget according to specs in the ticket:

<img width="440" alt="image" src="https://github.com/truenas/webui/assets/20611516/54e3bb50-6e76-4500-a9da-02265ddaee46">

<img width="435" alt="image" src="https://github.com/truenas/webui/assets/20611516/c037b12e-779c-4e7d-8b7e-1533700cf6c8">

<img width="426" alt="image" src="https://github.com/truenas/webui/assets/20611516/10bb722b-77f1-40ac-8d75-f615dde394c1">

<img width="438" alt="image" src="https://github.com/truenas/webui/assets/20611516/f3f28475-ffe2-4bbc-8cff-215a3c6fc036">

**Testing**

1. Test the widget with different types of data protection jobs ensure that widget displays correct set of tiles, and  the summarized stats are also correct.

2. Test the hyperlinks to create new jobs.

2023-12-11 14:26 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125571

2023-12-13 16:19 UTC, denysbutenko requested changes
![image](https://github.com/truenas/webui/assets/351613/f4a2d63b-46ab-4670-8eb8-6dc4117c5ddd)

It looks good but requires some improvements.
The backup widget is missing on mobile screens.

2023-12-13 16:19 UTC, denysbutenko commented on src/app/pages/dashboard/components/widget-backup/widget-backup.component.html
> +                {{ '{failed} of {all} tasks failed' | translate : { failed: failedCount, all: allCount } }}
I think variable names are better self-explanatory than placeholders.
Let's update placeholder names to match variables.

Also, `{all} tasks` need plural support.

2023-12-13 16:22 UTC, denysbutenko commented on src/app/pages/dashboard/components/widget-backup/widget-backup.component.html
> +                {{ '{failed} of {all} tasks failed' | translate : { failed: failedCount, all: allCount } }}
Plural support seems required for each occurrence of `tasks` in this PR. Please take a look.

2023-12-14 10:00 UTC, bvasilenko commented
@denysbutenko the requested changes should be addressed now

2023-12-14 13:52 UTC, denysbutenko approved these changes
Looks good, except few things:

The widget is still missing on mobile screens.

It's unclear why the text is being truncated. If there is something that should appear on the opposite side – let's add a title for links, at least. 
![image](https://github.com/truenas/webui/assets/351613/d7b34ec4-0e9b-422c-9a65-4fa4e323194a)

2023-12-15 08:18 UTC, bvasilenko commented
@denysbutenko now widget is optimized for mobile:

![image](https://github.com/truenas/webui/assets/20611516/880db230-fe6d-4660-89cb-a8f08b9f7b44)

other requested changes should be addressed as well

2023-12-15 08:23 UTC, denysbutenko commented
> @denysbutenko now widget is optimized for mobile:
> 
> ![image](https://private-user-images.githubusercontent.com/20611516/290765593-880db230-fe6d-4660-89cb-a8f08b9f7b44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2Mjg2MTgsIm5iZiI6MTcwMjYyODMxOCwicGF0aCI6Ii8yMDYxMTUxNi8yOTA3NjU1OTMtODgwZGIyMzAtZmU2ZC00NjYwLTg5Y2ItYThmMDhiOWY3YjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA4MTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjN2Q3ZDg4N2EwMmM3ZWJjZWJjOTFiMjIyNjc5NDk0ZmI4MTY4MTg2YmQwNTE2MDYyM2E5Mzg1YjYxZjA5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bI9_WKrhhLPBBa15NAlpq2EmJQd1TA11daa7IdMvZn8)
> 
> other requested changes should be addressed as well

PR is approved. Thanks!

2023-12-15 10:48 UTC, merged