NAS-125655: Submit additional fields when submitting a feedback
truenas/webui pull request #9308
Opened 2023-12-12 06:27 UTC by bvasilenko

**Testing**

1. Click Feedback indicator in the top bar
2. Fill in Feedback Dialog and submit

**Expected:** New fields `product_type` and `product_model` are submitted to  `/api/reviews/add/`

2023-12-12 06:28 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125655

2023-12-12 10:00 UTC, undsoft requested changes
I've submitted feedback on one of the machines from CI and saw `Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz` in product model.
Looks like we're using something incorrect here. I would basically like to see what is said in Platform field in System Information card on main dashboard.

2023-12-13 11:49 UTC, bvasilenko commented
@undsoft requested changes should be addressed now

2023-12-13 12:22 UTC, undsoft approved these changes
Looks good, thanks.

2023-12-14 05:21 UTC, merged