NAS-125654: Make `Rate this page` to be conditional
truenas/webui pull request #9312
Opened 2023-12-13 08:54 UTC by denysbutenko

It is currently blocked for testing due to a lack of access to the API endpoint without auth. However, it is ready for code review.

2023-12-13 08:54 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125654

2023-12-13 10:41 UTC, undsoft requested changes
It works, but there are some things to improve:
1. UI jumps when you open it when feedback is disabled. We need to solve this somehow, for example by not showing feedback options by default and showing a loading indicator, or by loading blacklist status beforehand.
2. When feedback is allowed, form still starts on Report a bug. It should start with feedback screen.

2023-12-13 10:41 UTC, undsoft commented on src/app/modules/ix-feedback/ix-feedback.service.ts
> +      this.ws.call('system.info'),
Some of this info should be already in the store.

2023-12-13 14:39 UTC, denysbutenko commented
> It works, but there are some things to improve:
> 
> 1. UI jumps when you open it when feedback is disabled. We need to solve this somehow, for example by not showing feedback options by default and showing a loading indicator, or by loading blacklist status beforehand.
> 2. When feedback is allowed, form still starts on Report a bug. It should start with feedback screen.

Okay, I changed its behavior to check blacklist status beforehand (on feedback-service initialization). The second issue is fixed.

2023-12-14 09:47 UTC, undsoft approved these changes
Looks good, tested with mocks.

2023-12-14 13:53 UTC, merged