NAS-125754: Fixed injection of `KubernetesStore` to `SetupPoolDialogComponent`
truenas/webui pull request #9331
Opened 2023-12-17 07:23 UTC by RehanY147

Go to the App details page and click on the Setup Pool button to make the dialog appear.

Expected: The dialog opens
Actual: nothing shows up. The screen goes a bit dark. Errors in the browser console.

2023-12-17 07:23 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125754

2023-12-17 09:23 UTC, undsoft requested changes
Not sure what adding `viewContainerRef` does, but I still get an error about missing KubernetesStore when I click Settings -> Choose Pool.

2023-12-17 17:03 UTC, RehanY147 commented
@undsoft That was a different instance of the dialog where the update was also needed. Adding the viewContainerRef gives the same injector context as the component that opened the dialog.

2023-12-18 09:15 UTC, undsoft approved these changes
Dialogs open now.

2023-12-18 13:10 UTC, merged