NAS-125756: Hide Restart and other options from limited users
truenas/webui pull request #9332
Opened 2023-12-17 10:42 UTC by undsoft

Testing: create a limited role and observe that Restart, Power Off and Reset to defaults option from General settings are not there.

2023-12-17 10:42 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125756

2023-12-18 07:27 UTC, RehanY147 requested changes
Soon as I login with root, UI crashes with these errors in the console
<img width="921" alt="image" src="https://github.com/truenas/webui/assets/24204846/12d66d8a-7352-4d88-829c-af412fb93afa">

2023-12-18 08:54 UTC, undsoft commented
Are you on fresh middleware?

2023-12-21 13:33 UTC, RehanY147 approved these changes
<img width="213" alt="image" src="https://github.com/truenas/webui/assets/24204846/44c6b353-b39a-42a3-a0dd-901dbc66e96d">
The styles are a little messed up but looks good otherwise

2023-12-21 13:33 UTC, RehanY147 commented on src/app/modules/layout/components/topbar/power-menu/power-menu.component.html
> +    *ngIf="isSysAdmin$ | async"
We could put both buttons with the same `ngIf` into one `ng-container`

2023-12-21 16:09 UTC, merged

2023-12-21 16:09 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.