NAS-125727: Make it easier to create shares from Dataset page
truenas/webui pull request #9345
Opened 2023-12-19 07:01 UTC by bvasilenko

**Testing**

Test the new buttons at **Datasets > (Choose a dataset) > "Roles" card**
- **Create SMB share**
- **Create NFS share**

2023-12-19 07:01 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125727

2023-12-19 10:06 UTC, undsoft approved these changes
It looks good.

One issue though – previously in SMB Share form when dataset was selected, we would auto-populate the name. This does not happen now when sharing from Roles card.

2023-12-19 10:06 UTC, undsoft commented on src/app/pages/datasets/components/roles-card/roles-card.component.spec.ts
> +  });
and test cases for opening modals

2023-12-21 07:43 UTC, bvasilenko commented
`WebUI / Run tests (pull_request)` step is failing for unknown reason. Locally it works:

```
Test Suites: 585 passed, 585 total
Tests:       7 skipped, 2434 passed, 2441 total
Snapshots:   0 total
Time:        1134.046 s
Ran all test suites.
✨  Done in 1143.03s.
```

2023-12-21 12:28 UTC, undsoft requested changes
Well, you'd have to debug tests.
You can try updating package.json to only run tests from this folder and create multiple variations of the tests.
For example, it's possible that tests are failing because `SmbFormComponent` are no defined in the test.

2023-12-21 12:28 UTC, undsoft commented on src/app/pages/datasets/components/roles-card/roles-card.component.spec.ts
> +    const createNfsShareLink = spectator.queryAll('.details-item .action')[1] as HTMLLinkElement;
It's an `HTMLAnchorElement`

2023-12-21 12:28 UTC, undsoft commented on src/app/pages/datasets/components/roles-card/roles-card.component.ts
> +    slideInRef.componentInstance.form.patchValue({ path: this.dataset.mountpoint });
Form is a private property in spirit. It would be better to pass in additional params via `data` in constructor.

2023-12-26 06:31 UTC, bvasilenko commented
@undsoft now tests are passing, so it's ready to be merged

2023-12-26 12:13 UTC, undsoft approved these changes
It looks good, but I've noticed that when I click to create an SMB share, the Name is prepopulated, but the Save button is disabled until I click on the Name field.

2023-12-27 20:06 UTC, merged

2023-12-27 20:06 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.