Disable restricted controls for Shares and Data Protection pages
truenas/webui pull request #9368
Opened 2023-12-26 07:04 UTC by bvasilenko

**Testing**

1. Create a new local group on our server, with `READONLY` role and another group with `SHARING_MANAGER` role at **Credentials > Local Groups > Privileges**.

2. Log in with this user, and visit the **Shares** page, click through every button and clickable icon. 
   - **Expected result:** if action is illogical, or corresponding API call results in an error, then this action should not be available in WebUI for the current user

5. Do the same for **Data Protection** page.

2023-12-26 07:04 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125806

2023-12-26 13:12 UTC, AlexKarpov98 requested changes
Let's fix all of the 🔴 RED checks first: 👇 

<img width="552" alt="Screenshot 2023-12-26 at 15 11 22" src="https://github.com/truenas/webui/assets/22980553/a8254731-2ab4-474c-b46a-c9d1756bdb78">

2023-12-28 05:10 UTC, denysbutenko commented on src/app/pages/services/components/service-smb/service-smb.component.ts
> +  readonly requiresRoles = [Role.SharingNfsWrite, Role.SharingManager, Role.SharingWrite];
`Role.SharingNfsWrite` seems like a wrong role here

2024-01-02 12:24 UTC, AlexKarpov98 approved these changes
It works as expected. 👍

2024-01-02 13:43 UTC, denysbutenko approved these changes
👍🏻

2024-01-04 13:12 UTC, merged