NAS-125870: New endpoint for system info card on main dashboard
truenas/webui pull request #9370
Opened 2023-12-26 13:08 UTC by AlexKarpov98

Testing: See ticket.

See that Dashboard Widget works for `HA systems` as well for the non-iX hardware system

I used: 
- Latest nightly (machine) for non-iX hardware system
- f60-146... (machine) for HA systems

<img width="1115" alt="Screenshot 2023-12-26 at 15 07 24" src="https://github.com/truenas/webui/assets/22980553/e9dace59-4d62-4fc8-8d38-7c356519a144">

These ones should have latest API on it.
As well the idea is not use `'failover.call_remote'` endpoint.

2023-12-26 13:09 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125870

2023-12-27 10:29 UTC, bvasilenko requested changes
@AlexKarpov98 while testing with the nightly build, getting errors on browser's console:

```
Cannot read properties of undefined (reading '$date')
    at WidgetSysInfoComponent_div_39_Template (widget-sys-info.component.html:242:27)
```

JSON response from `webui.main.dashboard.sys_info` might be helpful as well.

```
{
    "platform": "Generic",
    "version": "TrueNAS-SCALE-24.04.0-MASTER-20231227-033853",
    "license": null,
    "system_serial": "None",
    "hostname": "uitest93049",
    "uptime": "1:20:46.851000",
    "remote_info": null
}
```

2023-12-27 10:31 UTC, AlexKarpov98 commented
@bvasilenko 

Maybe because API is not up to date there.
You should see it's up to date, when it includes `uptime_seconds` instead of `uptime` at least.
I will talk to @yocalebo 

Updated version should be like:
```
{
  "platform": "Generic",
  "version": "TrueNAS-SCALE-24.04.0-MASTER-20231220-233026",
  "license": null,
  "system_serial": "4f2f1bf0-b56d-547e-fa6f-c90dbc8b8462",
  "hostname": "truenas",
  "uptime_seconds": 766519.97864525,
  "datetime": {
    "$date": 1703593084000
  }
  "remote_info": null
}
```

2023-12-27 12:54 UTC, AlexKarpov98 commented
@bvasilenko - ask @yocalebo for latest nightly with latest update, it wasn't pushed yet fully.

2023-12-28 07:15 UTC, bvasilenko commented
@AlexKarpov98 the final JSON format was merged into middleware and works, approving

2023-12-28 07:15 UTC, bvasilenko approved these changes
Works as expected

2023-12-28 10:35 UTC, merged

2023-12-28 10:35 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.