NAS-125918: Do not use `core.download and filesystem.get` to download job logs
truenas/webui pull request #9388
Opened 2024-01-02 10:35 UTC by AlexKarpov98

Testing: 
The main idea is to replace Job Download Logs calls (`core.download` with `filesystem.get`) with `core.job_download_logs`
<img width="931" alt="Screenshot 2024-01-02 at 12 34 17" src="https://github.com/truenas/webui/assets/22980553/cfc31340-eb9c-4768-8e83-dbbc9a3f2088">

2024-01-02 10:36 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125918

2024-01-03 22:41 UTC, RehanY147 requested changes
There is a untilDestroy being called without the decorator error in show-logs-dialog.component.ts
<img width="1283" alt="image" src="https://github.com/truenas/webui/assets/24204846/ced3a5c5-44a2-4983-95bb-59e727e42b1c">

2024-01-08 10:53 UTC, AlexKarpov98 commented
@RehanY147  - are you able to test it after all updates? 😃

2024-01-08 19:29 UTC, RehanY147 approved these changes

2024-01-08 20:06 UTC, merged

2024-01-08 20:07 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.