NAS-125611: Truncated display of IPv6 address in Network screen
truenas/webui pull request #9392
Opened 2024-01-03 16:09 UTC by AlexKarpov98

Testing: see ticket and result 👇 

Before:
<img width="376" alt="Screenshot 2024-01-03 at 17 21 44" src="https://github.com/truenas/webui/assets/22980553/67e59ec8-df13-4615-9950-faf313339520">

After:
<img width="378" alt="Screenshot 2024-01-03 at 17 21 50" src="https://github.com/truenas/webui/assets/22980553/8b75058d-1a65-46a6-801c-9a06d137b433">

Before:
<img width="373" alt="Screenshot 2024-01-03 at 17 20 58" src="https://github.com/truenas/webui/assets/22980553/f528e66f-d9bb-4e40-ab35-557f342fe7a8">

After:
<img width="376" alt="Screenshot 2024-01-03 at 17 20 20" src="https://github.com/truenas/webui/assets/22980553/02c307bc-152e-4f9a-9e95-348a6e24b6b4">

2024-01-03 16:09 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125611

2024-01-03 22:27 UTC, RehanY147 requested changes
In the after screenshots, the IPv4 address is truncated still. Also, for the iPhone 11 Pro screen (available in Firefox browser by default), the addresses are also truncated. See below
<img width="367" alt="image" src="https://github.com/truenas/webui/assets/24204846/90a2e086-9466-4a67-a95d-08d80ffea705">

2024-01-04 12:12 UTC, AlexKarpov98 commented
@RehanY147 - nice catch, please check it once again please.

2024-01-04 21:00 UTC, RehanY147 approved these changes

2024-01-05 08:15 UTC, merged

2024-01-05 08:15 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.