Fixed network traffic units on both dashboard widgets and reports dashboard
truenas/webui pull request #9427
Opened 2024-01-11 00:24 UTC by RehanY147

On the dashboard on NIC Widget and Network Widget, check network traffic units and conversion.
Also check units and conversion on the reports dashboard for interfaces.

2024-01-11 00:24 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125453

2024-01-11 12:51 UTC, undsoft requested changes
1. Values in network card in In/Out section lack `/s` suffix.
2. I was trying to compare values in the interface with values coming from reporting subscription and I couldn't get numbers to work. Please re-check them.

2024-01-12 14:21 UTC, RehanY147 commented
`fileSize` assumes you're passing in Bytes always. That was causing wrong conversions

2024-01-17 11:15 UTC, undsoft requested changes
1. I see 'kb/s/s' in interface card.
2. I see too many decimal places in network chart tooltip.
<img width="580" alt="Снимок экрана 2024-01-17 в 12 04 58" src="https://github.com/truenas/webui/assets/1481270/b9eacfd1-e645-47e4-9bb8-c6d530307e7c">
3. I still see unexpected numbers compared to when I calculate them on my own.
My expectation is that `update.interfaces.eno1.received_bytes_rate / 8 / 1000` would yield me kilobits per second.
4. There's code duplication and I'd rather we figure out how to work with `filesize` pipe instead of doing our own thing. If we need to, we can create our own pipe that would wrap around `filesize` with additional settings.

2024-01-17 11:15 UTC, undsoft commented on src/app/pages/dashboard/components/widget-network/widget-network.component.ts
> +    let bits = Math.abs(value);
Can we not get filesize pipe to work? I'd rather we not build our own code for this.

2024-01-22 10:38 UTC, undsoft requested changes
Looks better, but still some things to fix:
1. In reporting I get `expected a finite number, got number: NaN` when hovering over network chart.
2. Reporting also shows `mb/s` in table, while dashboard shows `mbits`. Should pick one.
3. Main dashboard -> Network chart. When hovering over outgoing values there is a minus sign in tooltip, that shouldn't be there.

2024-01-22 10:38 UTC, undsoft commented on src/app/core/pipes/bit-size.pipe.ts
> +}
Let's add a couple of simple tests to prevent regressions.

2024-01-22 10:38 UTC, undsoft commented on src/app/pages/dashboard/components/widget-nic/widget-nic.component.ts
> +      case multiplier < 1000 * 1000 * 1000 * 1000 * 1000:
Is this something that is still needed? Can we use the pipe here?

2024-01-26 14:45 UTC, undsoft approved these changes
Looks mostly correct. The only issue I could find was a lowercase 'mb/s' in Reporting section.
![Uploading Снимок экрана 2024-01-26 в 15.41.48.png…]()

2024-01-29 14:00 UTC, merged

2024-01-29 14:01 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.