NAS-125762: Installed apps sorting unsorts itself
truenas/webui pull request #9449
Opened 2024-01-16 10:05 UTC by AlexKarpov98

Testing: see ticket, bug only exists for Cobia, not for Dragonfish.

2024-01-16 10:06 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125762

2024-01-16 21:01 UTC, RehanY147 requested changes
If an app is running, and you click stop, the status changes, however the sorting doesn't fix itself. I sorted by Status. Clicked on "Stop" icon. The app status changed to "Stopping" but now, since the table is sorted by status, this app should move with the other apps with the same status. However, it still stays where it is until the whole table updates when the apps are reloaded.

2024-01-16 21:27 UTC, AlexKarpov98 commented
> If an app is running, and you click stop, the status changes, however the sorting doesn't fix itself. I sorted by Status. Clicked on "Stop" icon. The app status changed to "Stopping" but now, since the table is sorted by status, this app should move with the other apps with the same status. However, it still stays where it is until the whole table updates when the apps are reloaded.

I think this is fine, because we rely on the STATUS which comes from the middleware, but not our local status.
Do you think we should rely on local status as well for this? (for me it's not critical)

@undsoft - what do you think?

2024-01-16 21:45 UTC, RehanY147 commented
@AlexKarpov98 I think it's about the user expectation. The user wouldn't know what we are doing behind the scenes. They just see the status change without the sorting fixing itself. If the apps update takes a long while, the row stays there.

2024-01-18 08:57 UTC, RehanY147 approved these changes

2024-01-18 08:58 UTC, merged

2024-01-18 08:58 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.