NAS-126020: Adapt IPMI changes for UI
truenas/webui pull request #9450
Opened 2024-01-16 12:57 UTC by denysbutenko

Do not merge. It needs to be updated when middleware provides a way to query IPMI for remote systems.

2024-01-16 12:57 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126020

2024-01-31 10:59 UTC, undsoft requested changes
Cannot test as saving form results in `expected str, bytes or os.PathLike object, not int`

2024-01-31 10:59 UTC, undsoft commented on src/app/pages/network/components/ipmi-card/ipmi-form/ipmi-form.component.html
> +          *ixRequiresRoles="[Role.IpmiWrite, Role.FullAdmin]"
You can remove the check for FullAdmin then, as it will include IpmiWrite.

2024-02-01 05:24 UTC, denysbutenko commented
> Cannot test as saving form results in `expected str, bytes or os.PathLike object, not int`

This is fixed in https://github.com/truenas/middleware/pull/13045

2024-02-05 13:37 UTC, undsoft commented
No build available to test.

2024-02-07 06:13 UTC, denysbutenko commented
@undsoft ready to test on m40

2024-02-07 10:06 UTC, undsoft requested changes
When I select `Standby` I get `[EINVAL] ipmi.lan.update: Failed to apply IPMI config on remote controller: [EFAULT] [EINVAL] expected str, bytes or os.PathLike object, not int`

2024-02-07 10:53 UTC, denysbutenko commented
> When I select `Standby` I get `[EINVAL] ipmi.lan.update: Failed to apply IPMI config on remote controller: [EFAULT] [EINVAL] expected str, bytes or os.PathLike object, not int`

Ah, right. Only one node has the fix. Needs to repair HA to complete testing.

2024-02-07 16:36 UTC, undsoft approved these changes
Finished upgrading m40, form appears to be working correctly.

2024-02-07 16:38 UTC, merged

2024-02-07 16:39 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-126020 is targeted to the following versions which have not received their corresponding PRs: 24.10

2024-02-07 16:39 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.