NAS-126904: Directive for highlighting parts of UI
truenas/webui pull request #9507
Opened 2024-01-24 08:06 UTC by AlexKarpov98

Testing: see an example with `session-expiring-dialog.component`, it's basically the same as before, but now we have a directive.

2024-01-24 08:07 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126904

2024-01-24 12:38 UTC, undsoft requested changes
There was a misunderstanding about the task.
The task is not to have a directive for <a> styling, the task is to take out the behaviour we have for when we click on the link (focusing on a specific portion of the page).

2024-01-24 13:53 UTC, AlexKarpov98 commented
> There was a misunderstanding about the task. The task is not to have a directive for styling, the task is to take out the behaviour we have for when we click on the link (focusing on a specific portion of the page).

I'm sorry, please check it now :)

2024-01-25 14:57 UTC, merged

2024-01-25 14:57 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.