NAS-116358: Refactor Disks page to ix-tables
truenas/webui pull request #9516
Opened 2024-01-24 19:37 UTC by bvasilenko

**Testing**

Go to **Storage > Disks** and test disk filtering, selection and individual actions and batch actions.

2024-01-24 19:38 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-116358

2024-01-25 04:33 UTC, RehanY147 requested changes
Pagination missing on the table

2024-01-26 08:00 UTC, denysbutenko commented on src/assets/i18n/es.json
> -  "Edit Disk(s)": "Editar Disco(s)",
To be aware of existing translations being lost.

2024-01-31 00:27 UTC, RehanY147 approved these changes
Looks good

2024-01-31 05:25 UTC, merged

2024-01-31 05:26 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-01-31 11:43 UTC, AlexKarpov98 commented
@bvasilenko - I noticed that you missed .toLowerCase() when filtering disks, I gonna fix it here: https://github.com/truenas/webui/pull/9566