NAS-126983: Share Page: iSCSI Service Status Label and Configure button UI overlap in different browser window sizes
truenas/webui pull request #9557
Opened 2024-01-30 08:25 UTC by AlexKarpov98

Testing:
See Shares page on smaller screens and test other cards with toolbar headers.

result:
<img width="1297" alt="Screenshot 2024-01-30 at 10 17 23" src="https://github.com/truenas/webui/assets/22980553/9f475be1-e54b-49ca-b8e6-d7df1ff70839">

<img width="378" alt="Screenshot 2024-01-30 at 10 18 15" src="https://github.com/truenas/webui/assets/22980553/43cb0dc7-fc30-4030-a890-e61a246b6853">

INSTEAD OF something like:
<img width="379" alt="Screenshot 2024-01-30 at 10 24 25" src="https://github.com/truenas/webui/assets/22980553/59f23246-b3cd-43b0-9ac8-a7c6cd6c48af">

2024-01-30 08:25 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126983

2024-01-30 23:51 UTC, RehanY147 requested changes
Let's align buttons to the right instead of left. That seems more natural. Especially, with the three dots menu button.

2024-01-31 09:30 UTC, AlexKarpov98 commented
@RehanY147 - ready 😄

2024-02-02 03:30 UTC, RehanY147 approved these changes

2024-02-02 07:16 UTC, merged

2024-02-02 07:17 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.