NAS-127013 / 24.10 / Fix smart result table expanding
truenas/webui pull request #9562
Opened 2024-01-30 16:20 UTC by bvasilenko

**Testing**

1. Go to **Storage \> Pool Disk Health card \> View All S.M.A.R.T. tests**
2. Select to expand the view of 1 of the results

**Expected Result** Only selected row expands, regardless of other rows

2024-01-30 16:20 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127013

2024-01-30 23:49 UTC, RehanY147 requested changes
Still seeing the issue

https://github.com/truenas/webui/assets/24204846/aff86d56-82cd-4a81-ab4f-085a06783be5

2024-02-01 10:30 UTC, RehanY147 reviewed
Need a system to test this on. I can't see any results on a number of systems that I can try it on.

2024-02-04 20:46 UTC, bvasilenko commented
@RehanY147 actually previous solution wasn't working on the rest of the systems, so I've reworked it

2024-02-06 08:08 UTC, RehanY147 approved these changes

2024-02-06 18:08 UTC, merged

2024-02-06 18:08 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.