NAS-127060: Read only user able to edit Adv > Access Settings > token lifetime
truenas/webui pull request #9569
Opened 2024-01-31 13:27 UTC by AlexKarpov98

Testing: 
see ticket & use readonly user

2024-01-31 13:27 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127060

2024-02-01 09:47 UTC, RehanY147 approved these changes

2024-02-01 09:49 UTC, AlexKarpov98 commented on src/app/pages/system/advanced/access/access-form/access-form.component.ts
> +  readonly requiresRoles = [Role.FullAdmin];
@RehanY147 - I agree, I just use same naming as we have, but I can update all of them easily.

<img width="405" alt="Screenshot 2024-02-01 at 11 48 24" src="https://github.com/truenas/webui/assets/22980553/e897c715-c89e-47b9-968f-d45218f3de81">

2024-02-01 09:53 UTC, AlexKarpov98 commented on src/app/pages/system/advanced/access/access-form/access-form.component.ts
> +    this.authService.hasRole(this.requiresRoles).pipe(filter(Boolean), untilDestroyed(this)).subscribe(() => {
> We can break this down into a separate method. So it looks something like the following `this.canProceed().pipe(switchMap(() => this.isEnterprise ? this.updateSystem() : of())).subscribe(...)`

don't forget that empty `of()` will not emit any data. 😄

2024-02-01 09:57 UTC, RehanY147 requested changes
I see different values on the form for `FullAdmin` user or `ReadOnly` user.
See 300 for `ReadOnly` user and 300000 for `FullAdmin` user.

2024-02-01 09:58 UTC, AlexKarpov98 commented
> I see different values on the form for `FullAdmin` user or `ReadOnly` user. See 300 for `ReadOnly` user and 300000 for `FullAdmin` user.
@RehanY147 
It's not possible for NON ADMIN user to submit the form at all!
How is that possible? (cache?)

2024-02-01 10:04 UTC, AlexKarpov98 commented
> I see different values on the form for `FullAdmin` user or `ReadOnly` user. See 300 for `ReadOnly` user and 300000 for `FullAdmin` user.

@RehanY147 - I see it as well, but I think it's out of the scope for this ticket and maybe it's a Middleware Bug?

<img width="744" alt="Screenshot 2024-02-01 at 12 03 12" src="https://github.com/truenas/webui/assets/22980553/36c6adf2-3496-4fc7-b584-8f8d0bc55374">
<img width="758" alt="Screenshot 2024-02-01 at 12 03 21" src="https://github.com/truenas/webui/assets/22980553/24145e47-06c0-4ae0-80bd-2ca88e41e120">

2024-02-01 12:18 UTC, AlexKarpov98 commented
@RehanY147 - that's fine. Confirmed by @yocalebo!
**Caleb St. John  [2:15 PM]**
Hi, what is the issue? That’s not a global value, it’s tied to each credential I’m pretty sure

2024-02-02 03:35 UTC, RehanY147 approved these changes

2024-02-02 07:56 UTC, merged

2024-02-02 07:56 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.