NAS-127062 / 24.04-RC.1 / Dragonfish: Fix Enclosure pool/disk UI info incorrect when disk is pulled
truenas/webui pull request #9580
Opened 2024-02-01 12:48 UTC by bvasilenko

**Testing**

For testing machine - see ticket

**Expected result:** Enclosure page to identify sanity as the degraded pool with triangle "!"  icon in the legend on the right side

2024-02-01 12:50 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127062

2024-02-03 13:46 UTC, undsoft requested changes
Do I need to mock something to see that machine? All I see is a blank page when I go to `View Enclosure`.

2024-02-04 21:01 UTC, bvasilenko commented
@undsoft Yes, I've forgot to mention that you'll have to make a code adjustment at **system-info.effects.ts** shown below:

![image](https://github.com/truenas/webui/assets/20611516/d50c2dde-3aa8-46db-a0d5-8be5a32ea24c)

2024-02-05 11:55 UTC, undsoft approved these changes
The icon is correctly placed now.

2024-02-05 17:55 UTC, merged

2024-02-05 17:55 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.