NAS-127130: Fix duplicated text on Dashboard Backup Tasks widget
truenas/webui pull request #9620
Opened 2024-02-05 18:06 UTC by bvasilenko

**Testing**

See ticket

2024-02-06 07:54 UTC, RehanY147 requested changes
We don't need to say "Successfully". Just say "Sent tasks" and "Received Tasks"

2024-02-10 10:26 UTC, RehanY147 approved these changes

2024-02-11 17:55 UTC, merged

2024-02-11 17:55 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-127130 is targeted to the following versions which have not received their corresponding PRs: 24.04-RC.1

2024-02-11 17:55 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-02-11 17:56 UTC, bvasilenko commented
backport