NAS-126774: Add aria-label for ix-explorer input to make it easier for voice over type tools
truenas/webui pull request #9659
Opened 2024-02-10 11:22 UTC by RehanY147

2024-02-10 11:22 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126774

2024-02-12 16:26 UTC, undsoft requested changes
Looks good, but let's do this for other ix-controls.

2024-02-13 19:04 UTC, undsoft approved these changes
Looks pretty good. Please also check why Safari thinks that normal inputs (i.e. is SMB for are treated as autocompletes). It also reads some extra about stale data or something similar.

2024-02-13 19:04 UTC, undsoft commented on src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.html
>    </button>
Also needs label on the input above.

2024-02-14 09:03 UTC, RehanY147 commented on scripts/ui/ui.ts
> +  return url;
Whoops

2024-02-14 10:44 UTC, merged

2024-02-14 10:44 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-126774 is targeted to the following versions which have not received their corresponding PRs: 24.04-RC.1

2024-02-14 10:44 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-02-22 12:22 UTC, RehanY147 commented
backport