Refactor VmListComponent
truenas/webui pull request #9677
Opened 2024-02-14 11:00 UTC by denysbutenko

2024-02-14 11:00 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127208

2024-02-14 12:51 UTC, AlexKarpov98 commented on src/app/pages/vm/vm-list/vm-list.component.spec.ts
> +const virtualMachines: VirtualMachine[] = [
please remove unused props from the object.

2024-02-14 12:52 UTC, AlexKarpov98 commented on src/app/pages/vm/vm-list/vm-details-row/vm-details-row.component.spec.ts
> +const virtualMachine = {
make it smaller, removed unused props from the object.

2024-02-14 13:24 UTC, AlexKarpov98 requested changes
@denysbutenko - good job, please fix issues I've found.

1. Page title is missing when there is no data available:
<img width="1728" alt="Screenshot 2024-02-14 at 14 56 09" src="https://github.com/truenas/webui/assets/22980553/f8e2f7ec-c844-4ba7-b374-ca661d724f1d">

2. When State action failed, toggler is not returned to previous state.

https://github.com/truenas/webui/assets/22980553/51448603-258d-41d5-9c11-4b57f885f23e



3. I change `Start on Boot` toggler and nothing changes, if I reload the page - it stays at default values.
<img width="1728" alt="Screenshot 2024-02-14 at 15 02 50" src="https://github.com/truenas/webui/assets/22980553/9bfa702f-2fc4-456a-9c44-98e892cb2171">

4. No checks for Readonly user.
<img width="1728" alt="Screenshot 2024-02-14 at 15 14 30" src="https://github.com/truenas/webui/assets/22980553/4d91e634-e43a-4912-a787-bd5d9e17e486">

5. Sorting is not always working, see video:

https://github.com/truenas/webui/assets/22980553/8a3b5701-61b9-4c1a-80c7-b9f243ad5cc6



6. State toggler is not updated once I `Start`ed VM, see:

https://github.com/truenas/webui/assets/22980553/a9570ef5-18a0-492c-942c-faa3967282b5

7. Search is working not fully as expected, I find VM which has nothing related to the search at the first glance.

https://github.com/truenas/webui/assets/22980553/693212c1-4b37-4dc5-a64a-d5a97e5eb2db

8. On mobile (details row) buttons are not looking good and overlapping main content.
<img width="388" alt="Screenshot 2024-02-14 at 15 23 08" src="https://github.com/truenas/webui/assets/22980553/79c0fb0e-e980-4263-8566-aa3a8ac12a13">
<img width="382" alt="Screenshot 2024-02-14 at 15 23 49" src="https://github.com/truenas/webui/assets/22980553/fe0a536f-585a-4c44-af3e-38b3aeb0c365">

2024-02-15 11:50 UTC, denysbutenko commented
@AlexKarpov98 Most of the regressions are fixed. Basic role support was added. For advanced cases – I'll create a ticket to revisit roles for VM forms and dialogs.

2024-02-15 12:33 UTC, AlexKarpov98 commented
@denysbutenko - you can remove sorting from `Display Port` as well.

https://github.com/truenas/webui/assets/22980553/62684322-f6bb-4ea1-a62e-f76e8a4c5692

2024-02-15 12:36 UTC, AlexKarpov98 commented
@denysbutenko  <img width="894" alt="Screenshot 2024-02-15 at 14 36 21" src="https://github.com/truenas/webui/assets/22980553/e6c80419-3f3e-4548-b3d5-26bf111a03b2">
For `Running` and `Start on Boot` - please add `ixRequiresRoles` as well.

2024-02-15 12:38 UTC, AlexKarpov98 approved these changes
Looks good, thanks 👍

2024-02-15 13:44 UTC, denysbutenko commented
Linked tickets:

- [NAS-127372 Add new endpoint to download VM logs](https://ixsystems.atlassian.net/browse/NAS-127373)
- [NAS-127373 WebUI: Add role support for VM components](https://ixsystems.atlassian.net/browse/NAS-127373)

2024-02-15 13:45 UTC, merged

2024-02-15 13:45 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.