NAS-127546: App Install Page Layout is incorrect
truenas/webui pull request #9751
Opened 2024-02-28 08:32 UTC by AlexKarpov98

Testing: see result

https://github.com/truenas/webui/assets/22980553/ccf731bd-9aab-433d-b59d-bfcd6411e743

2024-02-28 08:32 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127546

2024-02-28 23:01 UTC, RehanY147 requested changes
Tests failing

2024-02-29 07:21 UTC, AlexKarpov98 commented
@RehanY147 - sorry, where did you see tests failing?
<img width="430" alt="Screenshot 2024-02-29 at 09 21 25" src="https://github.com/truenas/webui/assets/22980553/c079337b-cf25-4fe6-96cc-38ee7d1fb817">

only this one:
<img width="517" alt="Screenshot 2024-02-29 at 09 21 33" src="https://github.com/truenas/webui/assets/22980553/ebd61c80-e248-41a0-baba-8d482642a12e">

2024-03-05 20:00 UTC, RehanY147 approved these changes

2024-03-05 20:13 UTC, RehanY147 approved these changes

2024-03-05 21:32 UTC, merged

2024-03-05 21:32 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.