Timezone conversion corrections
truenas/webui pull request #9772
Opened 2024-03-05 03:59 UTC by RehanY147

Removes "time zone conversion" functionality from `FormatDateTimePipe` and removes "format date" functionality from `LocaleService`. Also, updates the `cron-parser` package. Adds timezone conversion in the `TaskService` method. Check for regressions.

2024-03-05 03:59 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126795

2024-03-05 10:59 UTC, undsoft requested changes

2024-03-05 10:59 UTC, undsoft commented on src/app/core/pipes/format-datetime.pipe.spec.ts
> +  const inputValue = utcToZonedTime(1709604204732 + (11 * 1 * 60 * 60 * 1000), 'Europe/London').getTime();
I don't quite understand the conversion here and why it is better than a simple timestamp.

2024-03-05 10:59 UTC, undsoft commented on src/app/modules/scheduler/components/scheduler-modal/scheduler-date-examples/scheduler-date-examples.component.html
> +  {{ date | formatDateTime }}
1. Not due to this PR, but I cannot test this as scheduler modal won't open.
2. This looks like this is going to show timestamps in browser timezone. In this component this is incorrect as we want to show dates in server timezone.
I would suggest adding another `serverTime` directive to be used like so `date | serverTime | formatDateTime`.
I have not checked other places, but other places like Audit and Reporting look suspicious.

2024-03-11 11:08 UTC, undsoft requested changes
Scheduler doesn't look correct.
I expect 12:00, not 16:00.

![Uploading Снимок экрана 2024-03-11 в 12.05.33.png…]()

2024-03-11 11:11 UTC, undsoft commented
As part of this ticket, let's also create a PR for dragonfish to just update the cron package.

2024-03-11 11:28 UTC, undsoft commented
FYI, I've created a ticket for later to add verbose explanations when there is a timezone mismatch: https://ixsystems.atlassian.net/browse/NAS-127768

2024-03-13 00:24 UTC, RehanY147 commented
> Scheduler doesn't look correct. I expect 12:00, not 16:00.

`master` shows the same thing.

2024-03-13 11:44 UTC, RehanY147 commented
@undsoft This is `master`
![Uploading image.png…]()

2024-03-13 12:10 UTC, RehanY147 commented
@undsoft I can't reproduce the bug where you saw `16:00` instead of `12:00`. Can you provide steps to reproduce?

2024-03-13 14:49 UTC, undsoft requested changes
Go to any place where there is a schedule selection (for example Data Protection -> Scrub Tasks), use Custom schedule, select daily preset.

2024-03-25 11:26 UTC, undsoft reviewed
Is the intent to replace all dates in this PR?
We should check what's happening in reporting, because it explicitly states machine timezone near time axis.

2024-03-25 11:26 UTC, undsoft commented on src/app/modules/ix-date/ix-date.component.html
> +  [matTooltip]="'Machine Time\n {time}, {tz}' | translate: { time: (serverTime | formatDateTime: dateFormat: timeFormat), tz: machineTimezone }"
I think we should only show tooltip when there is a mismatch between server time and browser time.

2024-03-25 11:26 UTC, undsoft commented on src/app/modules/ix-date/ix-date.component.ts
> +  @Input() machineTimezone: string = Intl.DateTimeFormat().resolvedOptions().timeZone;
Not really a machine timezone then.

2024-03-25 11:27 UTC, undsoft requested changes
👆🏻

2024-04-02 11:58 UTC, undsoft requested changes

2024-04-02 11:58 UTC, undsoft commented on src/app/modules/ix-date/ix-date.component.html
> +  {{ machineTime | formatDateTime }}, {{ machineTimezone }}
I don't think we need to show machine timezone on every date.

2024-04-02 11:58 UTC, undsoft commented on src/app/modules/ix-date/ix-date.component.ts
> +  @Input() machineTimezone: string;
I would try to read machine zone in this component, because otherwise you'd need to be passing it in in every place where ix-date is used.

2024-04-09 08:01 UTC, undsoft requested changes
Audit appears to be showing times in browser time instead of machine time.

2024-04-12 02:18 UTC, RehanY147 commented on src/app/modules/scheduler/classes/cron-schedule-preview/cron-schedule-preview.ts
> +      const machineToUtc = zonedTimeToUtc(exampleDate, timezone);
`timezone` is the machine timezone and the other one is the browser timezone.

2024-04-12 23:04 UTC, RehanY147 commented on src/app/pages/audit/components/audit/audit.component.spec.ts
> +      ['SMB', 'Administrator', '2024-03-05 04:30:01', 'Authentication', 'Account: Administrator'],
Yes, the `ix-cell-date` component hadn't been converted. That's what was being used by audit component.

2024-04-12 23:04 UTC, RehanY147 commented on src/app/pages/system/advanced/cron/cron-form/cron-form.component.spec.ts
> +        Schedule: '0 0 * * *',
The version change is making this test fail for some reason. Don't know why.

2024-04-15 07:38 UTC, undsoft approved these changes
Mission accomplished.

2024-04-15 07:38 UTC, undsoft commented on src/app/modules/ix-date/ix-date.component.ts
> +  /** Must be in browser timezone */
Let's update comment to `Date must be in browser timezone`, because a number (timestamp) is always UTC.

2024-04-15 07:38 UTC, undsoft commented on src/app/pages/reports-dashboard/components/report/report.component.html
> +              <strong>{{ 'Time22' | translate }}:</strong>
👆🏼 
(And you need to pull translations from master to recover translations for "Time" that got deleted)

2024-04-16 13:41 UTC, merged

2024-04-16 13:41 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.