NAS-127794: Dashboard - Backup Tasks - Infinite loading on m40
truenas/webui pull request #9799
Opened 2024-03-12 10:32 UTC by AlexKarpov98

Testing: see ticket
Result - no more infinite `spinner`:
<img width="570" alt="Screenshot 2024-03-12 at 12 31 44" src="https://github.com/truenas/webui/assets/22980553/2351fdb0-bb77-42e1-8dcd-57e20d231bb9">

2024-03-12 10:33 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127794

2024-03-12 16:40 UTC, undsoft requested changes
Wouldn't it be better to show an error message if any of the tasks were not loaded.
This could theoretically result in user seeing 0 tasks when having connectivity issues – an unexpected result.

2024-03-12 20:33 UTC, AlexKarpov98 commented
> Wouldn't it be better to show an error message if any of the tasks were not loaded. This could theoretically result in user seeing 0 tasks when having connectivity issues – an unexpected result.

then it would be good to show "Block" but with some error text instead, I mean not use modal, because it's an error in the card.

2024-03-13 08:49 UTC, AlexKarpov98 commented
This issue was fixed on the middleware side.

2024-03-13 08:49 UTC, closed without merging