NAS-127574: Hard to stop active cloudsync task on full width page
truenas/webui pull request #9800
Opened 2024-03-12 13:59 UTC by AlexKarpov98

Testing: 
See ticket, check if there are any regressions.
Details panel shall remain opened after update.

2024-03-12 14:00 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127574

2024-03-13 11:03 UTC, AlexKarpov98 commented on src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.ts
> +    const possibleIdProperties = ['id', 'audit_id', 'gid', 'identifier'] as (keyof T)[];
I agree, let's use

`@Input() identifier: keyof T = 'id' as keyof T;`

2024-03-15 10:25 UTC, RehanY147 requested changes
Not all the row objects will have an ‘id’ attribute. That’s something we should check. We might get some undefined errors. We should be adding the `identifier` input property manually wherever the table is used.

2024-03-15 10:28 UTC, AlexKarpov98 commented
> Not all the row objects will have an ‘id’ attribute. That’s something we should check. We might get some undefined errors. We should be adding the `identifier` input property manually wherever the table is used.

Well - it’s ONLY used for `ix-table-details-row` logic.
so - not all tables are using it.

2024-03-15 10:33 UTC, AlexKarpov98 commented
@undsoft @RehanY147 - BTW, I noticed, we have `identifier` prop for a Column.
```
export abstract class ColumnComponent<T> {
  identifier?: boolean;
}
```

It's used for getting test attr for the table `[ixTest]="getTestAttr(row)"`

```
  getTestAttr(row: T): string {
    const idColumn = this.columns.find((column) => column.identifier);
    return idColumn ? row[idColumn.propertyName].toString() : '';
  }
```

Maybe we should remove that prop and use @Input I added, because we should be able to provide only one `identifier`.
Using it in columns array - we can provide it for each property if we want - but that's incorrect and no error highlight is present:

example:

```
    textColumn({
      identifier: true,
      title: this.translate.instant('Name'),
      propertyName: 'name',
      sortable: true,
    }),
    textColumn({
      identifier: true,
      title: this.translate.instant('Roles'),
      getValue: (row) => row.roles.map((role) => {
        return roleNames.has(role) ? this.translate.instant(roleNames.get(role)) : role;
      }).join(', ') || this.translate.instant('N/A'),
    }),
```

2024-03-15 12:03 UTC, undsoft reviewed
There are several things mixed-in here.
I agree that checking `isExpanded` by a provided `id` instead of the object is a good idea, so `identifier` there makes sense.
However it won't work for `getTestAttr`, because QA dept relies on semi-stable human readable test ids instead of auto-generated numeric ids. Long story short they prefer  `row-bob` instead of `row-1` for users for example.

You can keep the `identifier` input and maybe rename `identifier` in `column` to something else.

2024-03-15 12:06 UTC, AlexKarpov98 commented
> There are several things mixed-in here. I agree that checking `isExpanded` by a provided `id` instead of the object is a good idea, so `identifier` there makes sense. However it won't work for `getTestAttr`, because QA dept relies on semi-stable human readable test ids instead of auto-generated numeric ids. Long story short they prefer `row-bob` instead of `row-1` for users for example.
> 
> You can keep the `identifier` input and maybe rename `identifier` in `column` to something else.

okay, got it.
The only thing - is that there are only few tables currently which are using `identifier: true`, probably I'll create a new ticket to add column test ids to all tables (`ix-table2`)

2024-03-18 07:25 UTC, RehanY147 requested changes
I think we should do both things in the same way. Either add both as input properties to the component or make both flags in column definitions as a best practice. I lean towards making them both component input properties.

2024-03-19 09:46 UTC, AlexKarpov98 commented
@RehanY147 I found another good solution, we already have `rowTestId: (row: T) => string;` which is used for row cells.
I used it for row test id as well 💪 

Whole RowTestId -> `data-test="row-card-nfs-share-mnt-tank-gg-123"`

RowCellTestId -> `data-test="text-path-card-nfs-share-mnt-tank-gg-123-row-text"`
RowCellTestId -> `data-test="text-description-card-nfs-share-mnt-tank-gg-123-row-text"`
...so...on...

2024-03-20 11:21 UTC, RehanY147 requested changes
While it's Ok to use string based row properties for test ids, they have the potential to be repeated (description, comment etc). However, the QA team demands that the test ids are kept humanly readable instead of using numeric or alphanumeric ids. That constraint doesn't apply to unique row ids that we need to identify the row table. It's not good to leave room for potential duplicate detailsRowIdentifier. I think we should keep the two separate. `rowTestId` is a readable string preferably. `detailsRowIdentifier` is preferably a unique identifier that doesn't have the potential to be repeated.

2024-03-20 11:23 UTC, AlexKarpov98 commented on src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.ts
> +    return this.columns[0]?.rowTestId(row) ?? '';
> Why is the index hard coded to 0? Any column could be the identifier column.

because formula is the same for each.

2024-03-20 11:24 UTC, AlexKarpov98 commented on src/app/pages/account/groups/group-list/group-list.component.ts
> -      identifier: true,
> After removing this identifer, no additional changes are made. How is group-list row going to get the identifier now?

I described earlier.
WE have `rowTestId: (row) => 'group-' + row.group,`

2024-03-20 12:08 UTC, RehanY147 approved these changes
As discussed, my concerns were addressed.

2024-03-20 12:11 UTC, merged