NAS-127811: Request:  Update help text for "Application name" of Custom App to reference name restriction of lower case letters
truenas/webui pull request #9826
Opened 2024-03-15 11:26 UTC by AlexKarpov98

Testing: 
Check updated validation rules and text. Text is taken from the middleware response.

2024-03-15 11:26 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127811

2024-03-18 09:26 UTC, RehanY147 requested changes
Let's show only the first validator that is failing out of the three conditions at a time. Also, let's add a tooltip that explains all of the rules together.

2024-03-18 09:28 UTC, AlexKarpov98 commented
> Let's show only the first validator that is failing out of the three conditions at a time. Also, let's add a tooltip that explains all of the rules together.

@RehanY147  - we have a pattern validator. 
I talked to ticket creator, we decided to change text to smth that we already have:
![image](https://github.com/truenas/webui/assets/22980553/50a5862e-a23c-4fe8-8245-9bc70a8dc756)

2024-03-20 12:12 UTC, RehanY147 approved these changes

2024-03-21 06:27 UTC, merged

2024-03-21 06:28 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.