NAS-127841: Readonly Admin UI Issues
truenas/webui pull request #9870
Opened 2024-03-22 09:20 UTC by AlexKarpov98

Testing: see ticket & try with readonly user.

2024-03-22 09:20 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127841

2024-03-24 07:33 UTC, RehanY147 requested changes
The buttons on empty tables are not locked. See  "Add Replication Tasks" button on the table.
<img width="1500" alt="image" src="https://github.com/truenas/webui/assets/24204846/642bae3c-b3c8-449f-bbab-766eb8efdd45">

2024-03-25 07:28 UTC, AlexKarpov98 commented
@RehanY147 - updated now.
<img width="1484" alt="Screenshot 2024-03-25 at 09 27 54" src="https://github.com/truenas/webui/assets/22980553/74c382ee-424b-4bd4-b17f-ceb8bce724fb">

2024-03-26 21:54 UTC, RehanY147 approved these changes

2024-03-26 22:46 UTC, merged

2024-03-26 22:47 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.