Fix reporting units again
truenas/webui pull request #9916
Opened 2024-04-02 15:35 UTC by bvasilenko

**Testing**

Check units at **Reporting > Network** and at **Dashboard > Network Widget**

**Expected result:**

* Network speeds - **bits** per second `b`, `Kb/s`, `Mb/s`, `Gb/s` etc.\
* Memory  - **bytes** `B`, `KiB`, `MiB`, `GiB`, etc.
* Disk - **bytes** per second `B/s`, `KiB/s`, `MiB/s`, `GiB/s`.

2024-04-02 15:35 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127963

2024-04-02 16:45 UTC, denysbutenko requested changes
![image](https://github.com/truenas/webui/assets/351613/36f4cf58-e47d-4a5e-9a26-566351eb44be)

`/s` missing in the tooltip
`Sent/Received` order is swapped between `In/Out`. 
Maybe let's do something like `Received .../s / Sent .../s`

Other than that, it looks good to me

2024-04-02 16:45 UTC, denysbutenko commented on src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
> +      if (numero < 1000) {
`< Kb`?

2024-04-03 09:24 UTC, undsoft requested changes
Lower case for network units was correct.
If we have time to fix spacing between "k" in decimals to make it consistent, it would good. I'd prefer 100k written together.
<img width="1790" alt="Снимок экрана 2024-04-03 в 11 22 48" src="https://github.com/truenas/webui/assets/1481270/2ead1f55-2b63-4c81-b631-42a69395ebe9">

2024-04-03 09:24 UTC, undsoft commented on src/app/helpers/file-size.utils.ts
> +    case Kb:
This is incorrect.
https://en.wikipedia.org/wiki/Data-rate_units#:~:text=Kilobit%20per%20second%20(symbol%20kbit,1%2C000%20bits%20per%20second

2024-04-03 09:24 UTC, undsoft commented on src/app/pages/reports-dashboard/utils/report.utils.spec.ts
> +});
👍🏼

2024-04-03 14:08 UTC, undsoft approved these changes
I think it's pretty good for now.
There are some minor issues that we can improve later.

2024-04-03 14:38 UTC, merged

2024-04-03 14:39 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.