NAS-128005: Main dashboard architecture
truenas/webui pull request #9917
Opened 2024-04-02 16:48 UTC by undsoft

Changes:
* Renames current dashboard to dashboard-old
* Adds new dashboard module with general architecture for new widgets.
* Adds two dummy widgets.

How to review:
Review description for the new main dashboard in comments here https://ixsystems.atlassian.net/browse/NAS-127217 and see if new proposed architecture will be able to support designs.

2024-04-02 16:48 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128005

2024-04-04 10:11 UTC, RehanY147 requested changes
It looks fine. I do feel like from the screenshots, each widget group needs a grid of columns and rows. And each widget will need to remember it's placement in the group grid. We should decide the grid size in this phase as well. Max rows x columns. 2 x 2 seems like the way to go but we should decide that and add it to the architecture.

2024-04-04 10:23 UTC, undsoft commented
See `WidgetGroup`. Each will have 4 slots with either a widget or null. For order of slots see `WidgetGroupLayout`.

2024-04-05 09:58 UTC, RehanY147 approved these changes

2024-04-08 13:31 UTC, merged

2024-04-08 13:31 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.