NAS-128045: [Dragonfish RC1] Apps Install UI Dropdown field show "x" instead of dropdown indicator
truenas/webui pull request #9929
Opened 2024-04-08 10:45 UTC by AlexKarpov98

Testing, see:
<img width="459" alt="Screenshot 2024-04-08 at 13 43 23" src="https://github.com/truenas/webui/assets/22980553/538770fb-9586-42f5-9a83-b18d32330459">

instead of 
<img width="443" alt="Screenshot 2024-04-08 at 13 44 28" src="https://github.com/truenas/webui/assets/22980553/f6e6a510-d4a2-4985-abd9-c1e645de3dea">

2024-04-08 10:45 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128045

2024-04-11 12:27 UTC, RehanY147 requested changes
This input is not meant to be a dropdown. It's an autocomplete input. It is not supposed to show dropdown options like a select or a combobox. If it acts so much like a combobox, maybe we should just use a combobox in its place.
@undsoft Opinion?

2024-04-11 12:28 UTC, RehanY147 commented
Google search example
<img width="837" alt="image" src="https://github.com/truenas/webui/assets/24204846/6b536e52-bf33-4bf1-a03b-e6e9f5c48b45">

2024-04-11 13:47 UTC, RehanY147 commented
@AlexKarpov98 I think we should resist this change. We want the input for combobox or autocomplete input to feel like an input. We want it to behave like a searchable field. You are supposed to have to type something into it for options to show up. It doesn't make sense even in a combobox to not show the `x` icon. Besides, just clicking inside the input already shows all of the available options. So, it's not like the down icon is needed. I think we should just switch to combobox maybe and leave the icon as is. So, it can be used like a scrollable, searchable select.

2024-04-14 18:29 UTC, AlexKarpov98 commented
@undsoft - let us now the final decision please 👍

2024-04-15 07:04 UTC, undsoft commented
Makes sense to use combobox instead of adding combobox functionality into `ix-input`.

2024-04-15 07:06 UTC, AlexKarpov98 commented
@undsoft - what about the dropdown icon instead of "x" ?
This ticket is about it 🤔

2024-04-15 07:43 UTC, undsoft commented
Would ix-select work here?

2024-04-15 07:45 UTC, AlexKarpov98 commented
> Would ix-select work here?
@undsoft 
no, it's required to have a searchable component, like `ix-combobox`

2024-04-15 08:03 UTC, undsoft commented
What happens if you click the (x) on this field? Is this field required? Should it be?
I don't know if I want to globally replace (x) icon with a dropdown icon in all comboboxes right now.

2024-04-15 08:04 UTC, AlexKarpov98 commented
@undsoft it will cleanup the field, if it's required- you'll see required error message, so no problem at all for me.

2024-04-16 00:45 UTC, RehanY147 commented
@ksimm1 There's a misunderstanding I think. With that example, what I meant to show was the behavior for the autocomplete-input that we have as it is meant to be used.

-Intended uses
input with `autocomplete="true"` - An input where you can type your value in but it will also show you complete values as you are typing so you don't have to type the whole thing. You can either type into the input field to search for a complete value or to enter a new value. This is what we currently use. The Google search is an example of this input type. If we indicate in anyway that it is a dropdown (with icons for example), then it becomes too similar to a combobox.

combobox - A drop-down where you cannot type in a new value. You have to select from one of the options already made available by the system. You can search the options by typing into the input field. But only the options already available are accepted as a value for said field.

My opinion regarding this issue is that we should be using a combobox instead of an autocomplete-input here as that seems more appropriate and how the input field is meant to be handled. But the PR has updated since my comment so consider the original comment outdated.

2024-04-16 00:52 UTC, RehanY147 requested changes
@undsoft  @AlexKarpov98 My point here is that `<ix-input autocomplete="true">` is exactly the same to `<ix-combobox>` visually. And the problem that the user described is still there if we switch to a `<ix-combobox>`. The ticket is about replacing `x` with a down arrow. That remains to be addressed.

2024-04-16 00:53 UTC, RehanY147 commented
To be clear, I'm not saying that we should do that. I'm saying that that's what the ticket is about. So, while this PR addresses the issue of the wrong input field being used, it doesn't address the original gripe that the user had.

2024-04-16 06:56 UTC, undsoft commented
@AlexKarpov98 Can you figure out why we are not using a simple dropdown (instead of a combobox) for those fields?

2024-04-16 08:08 UTC, AlexKarpov98 commented
> @AlexKarpov98 Can you figure out why we are not using a simple dropdown (instead of a combobox) for those fields?
@RehanY147 
@undsoft we use it because there may be a lot of elements on the ENUM array, this is the original ticket where it was required https://ixsystems.atlassian.net/browse/NAS-123257
The only problem is that I updated `ix-input` instead of using `ix-combobox` 

But the problem with `x` still remains though. 
I guess that's NOT a problem at all, we can add input prop to ix-combobox to show input with dropdown icon instead of x.

`@Input() showWithDropdown` for example.

2024-04-16 08:36 UTC, undsoft commented
No, we shouldn't add obscure inputs to our core components.

Here's what I think we can do:
1. If the field is empty and we are going to show select with all options on focus, show arrow icon.
2. If the field has full value and we are going to show select will all the options on focus, show arrow icon.
3. If user started typing and list of suggestions shows partial matches, show (x) icon.

2024-04-16 12:42 UTC, AlexKarpov98 commented
@RehanY147 @ksimm1 - Result 👇 

https://github.com/truenas/webui/assets/22980553/9125591f-8ebf-4975-aa1b-be72fefc8486

2024-04-16 13:20 UTC, RehanY147 approved these changes
Looks good to me.

2024-04-16 13:20 UTC, RehanY147 commented on src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts
> +  hasExactValueSelected(value: string): boolean {
Can be renamed to `isValueFromOptions`

2024-04-17 08:47 UTC, merged

2024-04-17 08:48 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.