Added error catch methodology for forms
truenas/webui pull request #9935
Opened 2024-04-09 00:50 UTC by RehanY147

Check the "Dataset Form" and "GUI Form". Both have different methods of causing failure. The pages should show fallback html.

2024-04-09 00:51 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127551

2024-04-09 07:36 UTC, undsoft requested changes
Looks promising, some things to consider:
1. We should still call global error handler to report this error to Sentry.
2. Some errors may be expected, e.g. backend errors. We may need to try to differentiate whether this was a rendering error or something else.
3. How would it work if we have multiple elements that can throw an error, e.g. 3 cards on the same page?
4. It would be ideal to still implement the error boundary component/directive, so that it's easier to reuse.

2024-04-09 07:36 UTC, undsoft commented on src/app/services/ix-graceful-updater.service.ts
> +export class IxGracefulUpdaterService {
Seems like we can live without this extra service.

2024-04-09 09:40 UTC, RehanY147 commented
@undsoft 
> We should still call global error handler to report this error to Sentry.
We are still using the global ErrorHandlerService. We're just creating a new instance on a component level to localize the context of the error state. So, it is still reporting to Sentry.

> How would it work if we have multiple elements that can throw an error, e.g. 3 cards on the same page?
The way it works is by creating a new instance of the ErrorHandlerService for each component and a new instance of the "Updater" service. So, each component will only handle its own errors. So, you would just need to break it down into smaller components in this scenario, and give each component it's own error handler.

2024-04-10 10:59 UTC, denysbutenko requested changes
![image](https://github.com/truenas/webui/assets/351613/57ff7fb5-2288-4b6a-8844-f8e3668b674a)
![image](https://github.com/truenas/webui/assets/351613/54f5cc5c-9d31-48fb-b110-2b4f2c1cb1d1)

Looks like working solution. However, I'd like to minimize the code changes as much as possible to add support for new error handler for every component (e.g. avoid error template definition). Perhaps it worth to consider retry mechanism if error occurs.

2024-04-10 10:59 UTC, denysbutenko commented on src/app/pages/datasets/components/dataset-form/dataset-form.component.html
> +<mat-card *ngIf="!guiService.hasError">
It would be nice to keep templates clean and handle error cases using directive.

2024-04-10 13:21 UTC, undsoft commented
> We are still using the global ErrorHandlerService. We're just creating a new instance on a component level to localize the context of the error state. So, it is still reporting to Sentry.

Are you sure it doesn't override global handler for the component?

2024-04-12 01:06 UTC, RehanY147 commented
This approach is also flawed and unreliable. Closing PR for now.

2024-04-12 01:06 UTC, closed without merging