Ensure multiline App "Section help" can be rendered
truenas/webui pull request #9987
Opened 2024-04-23 12:40 UTC by StevenMcElligott

Currently we cannot write multi-line section-help for the App install/edit GUI.
As those get removed, leading to one big blob of text.

This fix, ensures that multiline descriptions get respected accordingly.

Fixes the following issue:

![image](https://github.com/truenas/webui/assets/89483932/2d4c4308-7425-4d56-b1d4-1f05b21b4b0a)

To render as:

![image](https://github.com/truenas/webui/assets/89483932/552e1dc1-eca3-4f36-8e83-6cb2c5a6473d)

Thanks for your attention!

2024-04-23 13:17 UTC, AlexKarpov98 requested changes
Thanks for it.

One note - We need to add some styling here:

```
    white-space: pre-wrap;
    font-family: var(--font-family-body);
```
we need this:
<img width="875" alt="Screenshot 2024-04-23 at 16 12 39" src="https://github.com/truenas/webui/assets/22980553/19c490ed-9686-4a76-a7a1-5e456216a861">

Currently it looks like this:
<img width="826" alt="Screenshot 2024-04-23 at 16 11 53" src="https://github.com/truenas/webui/assets/22980553/e91662ea-8a74-461c-b37c-ab138b4ec6f4">

2024-04-23 14:31 UTC, AlexKarpov98 approved these changes
Works good! Thank You. 👍

2024-04-23 15:06 UTC, StevenMcElligott commented
> Works good! Thank You. 👍

Np!

2024-04-23 15:09 UTC, undsoft requested changes
Hi,
Thank you for your contribution.
Unfortunately this is the file with global styles, we are trying to get away from setting styles globally.
It's better to set those styles in `ix-dynamic-wizard.component.scss`.

2024-04-23 15:10 UTC, AlexKarpov98 commented
I'm sorry, I missed that this is a global change, I was in `ix-dynamic-wizard.component.scss` context. 
Thanks @undsoft .

2024-04-24 08:19 UTC, AlexKarpov98 commented
@undsoft - now it is fine.

2024-04-24 12:14 UTC, undsoft approved these changes
Thanks.

2024-04-24 12:15 UTC, merged